### ISSUE TITLE
"AWT-EventQueue-0" java.lang.ClassCastException: 

### ISSUE THREAD

**Issue by gerroon** [UniversalMediaServer/UniversalMediaServer#1063]
Hi

I see this regularly in my logs. I thought I would share it.

I am using Debian testing with Java 

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode

```

19:55:46 INFO  Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
19:55:46 INFO  	at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:145)
19:55:46 INFO  	at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:353)
19:55:46 INFO  	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
19:55:46 INFO  	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
19:55:46 INFO  	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:86)
19:55:46 INFO  	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1030)
19:55:46 INFO  	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:196)
19:55:46 INFO  	at sun.java2d.SunGraphics2D.copyImage(SunGraphics2D.java:3229)
19:55:46 INFO  	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3270)
19:55:46 INFO  	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3214)
19:55:46 INFO  	at sun.awt.X11.XTrayIconPeer$IconCanvas.paint(XTrayIconPeer.java:601)
19:55:46 INFO  	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
19:55:46 INFO  	at sun.awt.X11.XRepaintArea.paintComponent(XRepaintArea.java:64)
19:55:46 INFO  	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
19:55:46 INFO  	at sun.awt.X11.XComponentPeer.handleEvent(XComponentPeer.java:584)
19:55:46 INFO  	at java.awt.Component.dispatchEventImpl(Component.java:4965)
19:55:46 INFO  	at java.awt.Component.dispatchEvent(Component.java:4711)
19:55:46 INFO  	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
19:55:46 INFO  	at java.awt.EventQueue.access$500(EventQueue.java:97)
19:55:46 INFO  	at java.awt.EventQueue$3.run(EventQueue.java:709)
19:55:46 INFO  	at java.awt.EventQueue$3.run(EventQueue.java:703)
19:55:46 INFO  	at java.security.AccessController.doPrivileged(Native Method)
19:55:46 INFO  	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
19:55:46 INFO  	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
19:55:46 INFO  	at java.awt.EventQueue$4.run(EventQueue.java:731)
19:55:46 INFO  	at java.awt.EventQueue$4.run(EventQueue.java:729)
19:55:46 INFO  	at java.security.AccessController.doPrivileged(Native Method)
19:55:46 INFO  	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
19:55:46 INFO  	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
19:55:46 INFO  	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
19:55:46 INFO  	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
19:55:46 INFO  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
19:55:46 INFO  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
19:55:46 INFO  	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
19:55:46 INFO  	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by Nadahar** [comment]
@gerroon I'm afraid there's nothing in there that give us any clue about what's causing this, none of the classes in the stack trace is from UMS. A full trace log containing these errors might help. 

The only I can see is that the error is from the GUI drawing system, and it seems like it has to do with repainting the tray icon.

**Comment by gerroon** [comment]
@Nadahar 

I will see what I can do. Maybe some issue related to gtk theme. I will reopen it later.
