### ISSUE TITLE
ConcurrentModificationException in RendererConfiguration.loadRendererConfigurations()

### ISSUE THREAD

**Issue by Nadahar** [UniversalMediaServer/UniversalMediaServer#1092]
While doing some testing in #1053 after syncing it up with latest master, I randomly get the below stack trace during startup. I don't see how #1053 could have affected this, and I've never seen it before I synced up with master, so I'm assuming this doesn't come from #1053. 

@UniversalMediaServer/developers Have any of you done any recent modifications to ```RendererConfiguration``` or ```FileWatcher``` that could lead to this? ```ConcurrentModificationException``` is generally caused by thread unsafety and especially since this happens by random (that is, in somewhere between 10% and 20% of startups in my configuration).

Whatever introduced it, it should be fixed.

```LogTalk
ERROR 19:02:31.631 [main] A serious error occurred during Universal Media Server initialization: null
TRACE 19:02:31.637 [main] 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$ValueIterator.next(HashMap.java:950)
	at net.pms.util.FileWatcher$WatchMap.contains(FileWatcher.java:174)
	at net.pms.util.FileWatcher.add(FileWatcher.java:138)
	at net.pms.configuration.RendererConfiguration.load(RendererConfiguration.java:1008)
	at net.pms.configuration.RendererConfiguration.init(RendererConfiguration.java:1019)
	at net.pms.configuration.RendererConfiguration.<init>(RendererConfiguration.java:967)
	at net.pms.configuration.RendererConfiguration.<init>(RendererConfiguration.java:950)
	at net.pms.configuration.RendererConfiguration.loadRendererConfigurations(RendererConfiguration.java:273)
	at net.pms.PMS.init(PMS.java:609)
	at net.pms.PMS.createInstance(PMS.java:1101)
	at net.pms.PMS.main(PMS.java:1261)
```

Edit: After taking a quick look at it, it seems more than likely that the static ```Map``` ```keys``` is the culprit. Having unprotected mutable static class fields called by multiple threads is frankly asking for it. My guess is that ```FileWatcher``` has been taken more in use lately, thereby increasing the chance of this bug manifesting itself? @SubJunk Are the "automatic" media library update functions merged into master? If so, that's probably what causes the increased chance..

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/664

**Comment by Nadahar** [comment]
It turns out this is a feature.
