### ISSUE TITLE
NumberFormatException: For input string: "2456835065" (OGG audio file)

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1271]
```logtalk
WARN  2017-05-05 04:03:18.078 [Library Scanner] Unhandled exception while resolving Tim_Berners-Lee_16bit.oga: For input string: "2456835065"
DEBUG 2017-05-05 04:03:18.078 [Library Scanner] 
java.lang.NumberFormatException: For input string: "2456835065"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at net.pms.dlna.LibMediaInfoParser.getSpecificID(LibMediaInfoParser.java:800)
	at net.pms.dlna.LibMediaInfoParser.parse(LibMediaInfoParser.java:227)
	at net.pms.configuration.FormatConfiguration.parse(FormatConfiguration.java:413)
	at net.pms.formats.Format.parse(Format.java:312)
	at net.pms.dlna.RealFile.resolve(RealFile.java:208)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1485)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1284)
	at net.pms.dlna.RealFile.isValid(RealFile.java:71)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:576)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:536)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:113)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:169)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:260)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:270)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:218)
	at net.pms.dlna.DLNAMediaDatabase.run(DLNAMediaDatabase.java:938)
	at java.lang.Thread.run(Unknown Source)
```

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/AACfix/src/main/java/net/pms/dlna/LibMediaInfoParser.java#L788-L800

[Tim_Berners-Lee_16bit.oga.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/977969/Tim_Berners-Lee_16bit.oga.txt)

```logtalk
General
Complete name                            : F:\!MEDIA_TEST_FILES\AUDIO\OGA\Tim_Berners-Lee_16bit.oga
Format                                   : Ogg
Format/Info                              : Free Lossless Audio Codec
File size                                : 3.45 MiB
Duration                                 : 47 s 985 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 603 kb/s
FileExtension_Invalid                    : ogg ogm opus

Audio
ID                                       : 2456835065 (0x927053F9)
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 47 s 985 ms
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Writing library                          : Lavf55.22.102
```

**Comment by Sami32** [comment]
Fixed
