### ISSUE TITLE
NPE in newgui.StatusTab

### ISSUE THREAD

**Issue by ezpuzz** [UniversalMediaServer/UniversalMediaServer#1283]
I'm receiving the following stacktrace when connecting with BubbleUPNP.
UMS is running on Windows 10 / Java 7

```
TRACE 2017-05-23 14:17:00.843 [New I/O worker #7] Received on socket: User-Agent: BubbleUPnP UPnP/1.1
TRACE 2017-05-23 14:17:00.843 [New I/O worker #6] Received on socket: Connection: Keep-Alive
TRACE 2017-05-23 14:17:00.843 [New I/O worker #7] Received on socket: Accept-Encoding: gzip,deflate
TRACE 2017-05-23 14:17:00.843 [New I/O worker #6] Received on socket: User-Agent: BubbleUPnP UPnP/1.1
TRACE 2017-05-23 14:17:00.843 [New I/O worker #6] Received on socket: Accept-Encoding: gzip,deflate
DEBUG 2017-05-23 14:17:00.843 [New I/O worker #7] Reading MediaInfo: true (default: false)
DEBUG 2017-05-23 14:17:00.844 [New I/O worker #6] Reading MediaInfo: true (default: false)
DEBUG 2017-05-23 14:17:00.844 [New I/O worker #7] Adding status button for Unknown renderer
DEBUG 2017-05-23 14:17:00.844 [New I/O worker #6] Purging renderer Unknown renderer as invalid
DEBUG 2017-05-23 14:17:00.845 [AWT-EventQueue-0] Deleting renderer Unknown renderer
DEBUG 2017-05-23 14:17:00.849 [New I/O worker #7] Marking renderer "Unknown renderer" at /192.168.1.4 as unrecognized
DEBUG 2017-05-23 14:17:00.849 [New I/O worker #6] Adding status button for Unknown renderer
TRACE 2017-05-23 14:17:00.850 [New I/O worker #7] Using default media renderer: Unknown renderer
INFO  2017-05-23 14:17:00.850 [New I/O worker #7] Media renderer was not recognized. Possible identifying HTTP headers:User-Agent: BubbleUPnP UPnP/1.1
DEBUG 2017-05-23 14:17:00.860 [New I/O worker #6] Marking renderer "Unknown renderer" at /192.168.1.4 as unrecognized
DEBUG 2017-05-23 14:17:00.860 [New I/O worker #7] Adding status button for Unknown renderer
TRACE 2017-05-23 14:17:00.860 [New I/O worker #6] Using default media renderer: Unknown renderer
INFO  2017-05-23 14:17:00.860 [New I/O worker #6] Media renderer was not recognized. Possible identifying HTTP headers:User-Agent: BubbleUPnP UPnP/1.1
DEBUG 2017-05-23 14:17:00.867 [New I/O worker #7] Caught exception: null
TRACE 2017-05-23 14:17:00.868 [New I/O worker #7]
java.lang.NullPointerException: null
	at net.pms.newgui.StatusTab$RendererItem.<init>(StatusTab.java:88)
	at net.pms.newgui.StatusTab.addRenderer(StatusTab.java:331)
	at net.pms.newgui.LooksFrame.addRenderer(LooksFrame.java:620)
	at net.pms.PMS.setRendererFound(PMS.java:205)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:232)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Sami32** [comment]
`rendererProgressBar.setString(r.getAddress().getHostAddress());`

@ezpuzz What build/version of UMS are you using ?

**Comment by ezpuzz** [comment]
6.6.0

**Comment by Nadahar** [comment]
The NPE is easy enough to fix: 4d548f7e4f6dee0d7725f84a7479aee87cd2fc81. The question is why the address is "unknown". 

@ezpuzz Are you by any chance only using IPv6 on the device running BubbleUPnP? We need debug files to see what's really going on here. Please go to the "Log" tab, restart in trace mode, reproduce the error and create debug files. Attach the .zip here.

**Comment by ezpuzz** [comment]
I think it was failing to connect due to a denial of service protection
setting on my router which was hampering multicast packet delivery.  I'm
not able to reproduce now and I'm connecting fine now that the setting is
disabled.

**Comment by Nadahar** [comment]
@ezpuzz Good, that means we probably have to underlying reason. We'll just fix the NPE then.
