### ISSUE TITLE
Database exception not handled

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1312]
From UMS 6.7.1 and Windows 10 64-bit:
```logtalk
TRACE 2017-06-18 14:10:41.753 [HTTPv2 Request Worker 3] net.pms.formats.FormatFactory Matched format MPG to "G:\Movies\Terminators\6218023_-_Terminator_1_(1984)_Uncut\Terminator.1.1984.Uncut.DTS.DL.1080p.BluRay.x264-HQE_x264.mp4"
DEBUG 2017-06-18 14:10:41.753 [HTTPv2 Request Worker 3] net.pms.dlna.RealFile Error while getting cached information about Terminator.1.1984.Uncut.DTS.DL.1080p.BluRay.x264-HQE_x264.mp4, reparsing information: Column "IMAGEINFO" not found [42122-193]
TRACE 2017-06-18 14:10:41.753 [HTTPv2 Request Worker 3] net.pms.dlna.RealFile 
org.h2.jdbc.JdbcSQLException: Column "IMAGEINFO" not found [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3148)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3236)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:529)
	at net.pms.dlna.DLNAMediaDatabase.getData(DLNAMediaDatabase.java:367)
	at net.pms.dlna.RealFile.resolve(RealFile.java:178)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1495)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1296)
	at net.pms.dlna.RealFile.isValid(RealFile.java:71)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:586)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:113)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:169)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1256)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.network.RequestV2.answer(RequestV2.java:778)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:392)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:266)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
TRACE 2017-06-18 14:10:41.753 [HTTPv2 Request Worker 3] net.pms.formats.Format Parsing results for file "Terminator.1.1984.Uncut.DTS.DL.1080p.BluRay.x264-HQE_x264.mp4": Container: MP4, Size: 299974540, Mime Type: video/mpeg
ERROR 2017-06-18 14:10:41.753 [HTTPv2 Request Worker 3] net.pms.dlna.RealFile Database error while trying to add parsed information for "G:\Movies\Terminators\6218023_-_Terminator_1_(1984)_Uncut\Terminator.1.1984.Uncut.DTS.DL.1080p.BluRay.x264-HQE_x264.mp4" to the cache: Column "IMAGEINFO" not found; SQL statement:
SELECT ID, FILENAME, MODIFIED, TYPE, DURATION, BITRATE, WIDTH, HEIGHT, SIZE, CODECV, FRAMERATE, ASPECT, ASPECTRATIOCONTAINER, ASPECTRATIOVIDEOTRACK, REFRAMES, AVCLEVEL, IMAGEINFO, THUMB, CONTAINER, MUXINGMODE, FRAMERATEMODE, STEREOSCOPY, MATRIXCOEFFICIENTS, TITLECONTAINER, TITLEVIDEOTRACK, VIDEOTRACKCOUNT, IMAGECOUNT, BITDEPTH FROM FILES WHERE FILENAME = ? [42122-193]
TRACE 2017-06-18 14:10:41.753 [HTTPv2 Request Worker 3] net.pms.dlna.RealFile SQL error code: 42122
TRACE 2017-06-18 14:10:41.753 [HTTPv2 Request Worker 3] net.pms.dlna.RealFile 
org.h2.jdbc.JdbcSQLException: Column "IMAGEINFO" not found; SQL statement:
SELECT ID, FILENAME, MODIFIED, TYPE, DURATION, BITRATE, WIDTH, HEIGHT, SIZE, CODECV, FRAMERATE, ASPECT, ASPECTRATIOCONTAINER, ASPECTRATIOVIDEOTRACK, REFRAMES, AVCLEVEL, IMAGEINFO, THUMB, CONTAINER, MUXINGMODE, FRAMERATEMODE, STEREOSCOPY, MATRIXCOEFFICIENTS, TITLECONTAINER, TITLEVIDEOTRACK, VIDEOTRACKCOUNT, IMAGECOUNT, BITDEPTH FROM FILES WHERE FILENAME = ? [42122-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.command.dml.Select.prepare(Select.java:853)
	at org.h2.command.Parser.prepareCommand(Parser.java:259)
	at org.h2.engine.Session.prepareLocal(Session.java:561)
	at org.h2.engine.Session.prepareCommand(Session.java:502)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1203)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:676)
	at net.pms.dlna.DLNAMediaDatabase.insertOrUpdateData(DLNAMediaDatabase.java:578)
	at net.pms.dlna.RealFile.resolve(RealFile.java:222)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1495)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1296)
	at net.pms.dlna.RealFile.isValid(RealFile.java:71)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:586)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:113)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:169)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1256)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.network.RequestV2.answer(RequestV2.java:778)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:392)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:266)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by valib** [comment]
@Sami32 if you not reset the database or delete it when you change between different UMS branches you obviously get this error.

**Comment by Sami32** [comment]
@valib Me ? I guess that you're kidding, i'll never use Windows 10 :wink: 

Have a look at this user log: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/444#issuecomment-309297799

**Comment by valib** [comment]
@Sami32 I don't know how this user changed the UMS but @horrorman009 offred him the propper solution.

**Comment by Sami32** [comment]
@valib I'm not sure to understood you, but yes i agree that this exception should be correctly handled, or at least advertise clearly the users of such issue, IMO.

**Comment by Nadahar** [comment]
This shouldn't normally be possible because the database is recreated if the version is wrong. My guess is that this user has installed one of the 7.0.0 beta's and then installed 6.7.x. I think #1061 and #942 had the same "database version" number for a long time. That's the way it will be when changes are being made in different branches at the same time.

I don't think we need to do anything about this except to tell people to "Reset the database" if they have this problem. Maybe we should bump the database version again before the next version to make sure it will be recreated, but then the version in 7.0.0 must also be bumped so that 7.0.0 is "ahead" of master.
