### ISSUE TITLE
Error in parsing stream

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1314]
@nadahar Any idea ?
Original log from [here](http://www.universalmediaserver.com/forum/viewtopic.php?p=31695#p31695):
```

20:25:19 INFO Started playing XXXXXX.HDTV.HEVC.x265_xvid.avi on your KD-49XE9005
20:25:34 ERROR Error in parsing stream: http://podcasts.engadget.com/rss.xml
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 1: White spaces are required between publicId and systemId.
at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:198)
at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
at net.pms.dlna.Feed.parse(Feed.java:111)
at net.pms.dlna.Feed.resolveOnce(Feed.java:94)
at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1504)
at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1495)
at net.pms.dlna.DLNAResource.run(DLNAResource.java:1296)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: org.jdom.input.JDOMParseException: Error on line 1: White spaces are required between publicId and systemId.
at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:194)
... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: White spaces are required between publicId and systemId.
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
```

**Comment by Nadahar** [comment]
@Sami32 I have no idea what's happening, except that i can see that the links are from our default ```WEB.conf``` (which is filled with irrelevant and mostly outdated links). 

Maybe this renderer tries to start "everything" for some reason, and starts those as well? I really have no clue. Deleting ```WEB.conf``` and making a proper trace log seems like a start.

**Comment by Sami32** [comment]
This user didn't leaved full log, so as it's not a default web link, i suspect that he did mistyping.
That's said, as that UMS part is very weaky, i'm sure of nothing, and as you're skilled in XML parsing i prefered asked.
Thanks for your help :wink:

**Comment by Nadahar** [comment]
@Sami32 I don't know if I helped, but it *is* a default web link: https://github.com/UniversalMediaServer/UniversalMediaServer/blob/55e5f48fa450dd8edc376dc1d5d3bc441e3cdfd2/src/main/external-resources/WEB.conf#L35

I'm not "skilled" at XML parsing, but it seems obvious enough that the XML is invalid. The question is *why* it tries to process that while playing a completely different file.

**Comment by Sami32** [comment]
Correct. Thanks.
I didn't remember it, as i think the only time that i tried it was 1 year ago.

Never now, maybe more than one instance are running ?

**Comment by Nadahar** [comment]
@Sami32 Everything is possible, but you'd still think that *something* would need to ask for that resource to be played for it to try..?

**Comment by Sami32** [comment]
It's certainly possible, if he didn't modified the configuration file, as at the beginning UMS read them all.
