### ISSUE TITLE
Bravia XBR renderer config update request

### ISSUE THREAD

**Issue by lopopolo** [UniversalMediaServer/UniversalMediaServer#1325]
It appears the XBR config has not been touched since 2014. I don't know exactly what I'm looking for, but [this spec sheet](https://docs.sony.com/release//specs/XBR65X900E_mksp.pdf) indicates that the newer XBRs at least support mkv:VP8 and webm for video, JPEG images, and FLAC audio.

<img width="244" alt="screen shot 2017-06-26 at 8 33 57 pm" src="https://user-images.githubusercontent.com/860434/27569867-d883d720-5aae-11e7-9824-76722844bfba.png">

**Comment by lopopolo** [comment]
I have a FLAC, VP8 video in an MKV, and VP8 video in a webm.

**Comment by lopopolo** [comment]
Also, this TV is a 4K TV. If the older XBRs are not, does that warrant creating a renderer profile at higher priority for the E series? The suggestion in the pull request that i manually uncomment the max resolution configs seems user hostile.

**Comment by SubJunk** [comment]
Yes it would be good to create an E series profile. If you can provide us with logs we can make an attempt at that

**Comment by lopopolo** [comment]
What do I need to do to capture these logs?

**Comment by Nadahar** [comment]
@lopopolo Follow [these steps](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556). Under "reproduce bugs" try to play the file(s) in question. Attach the resulting zip file in a comment here.

**Comment by lopopolo** [comment]
I've tried my best to pick out the relevant logs. My network has 6 renderers so I wanted to spare you the noise.

My test folder contains the following:

```console
$ ls -1a
./
../
.DS_Store
Kanye West Ft_ DJ Khaled -- WAY TOO COLD.flac
vp8.mkv
vp8.webm
vp9.mkv

```

The XBR-65X900E does not natively support the VP9 codec; however, attempting to play vp9.mkv yields these logs, which indicate that the transcode has failed:

```
DEBUG 2017-06-30 14:47:12.619 [HTTPv2 Request Worker 16] Switching rendering context to 'XBR-65X900E Blue Ivy [FFmpeg]' from 'Chrome [FFmpeg]'
DEBUG 2017-06-30 14:47:12.619 [HTTPv2 Request Worker 16] Starting transcode/remux of vp9.mkv with media info: Container: MKV, Size: 2236847, Video Bitrate: 554842, Video Tracks: 1, Video Codec: vp9, Duration: 0:00:32, Video Resolution: 638 x 360, Frame Rate Mode: CFR (CFR), Audio Tracks: 1 [Audio Codec: AAC-LC, Bitrate: 0, Channels: 2, Sample Frequency: 44100 Hz], DLNAThumbnail: [Format = JPEG, Resolution = 319×180, Size = 6190, DLNA Profile = JPEG_RES_319_180], Mime Type: video/x-matroska
DEBUG 2017-06-30 14:47:12.626 [HTTPv2 Request Worker 16] Reading HalveBitrate: true (default: false)
DEBUG 2017-06-30 14:47:12.628 [HTTPv2 Request Worker 16] Starting mkfifo -m 777 /var/folders/w1/l8xvpngj3b3f6l7m8y2xgyjm0000gn/T/UMS-lopopolo/ffmpegvideo_145_1498859232627
DEBUG 2017-06-30 14:47:12.632 [HTTPv2 Request Worker 16] Unix process ID (mkfifo): 34779
DEBUG 2017-06-30 14:47:12.940 [ffmpeg-14] Starting "/Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg" -y -loglevel fatal -i /Users/lopopolo/Media-Server/xbr-test/vp9.mkv -bufsize 1835k -g 5 -q:v 1 -qmin 2 -qmax 3 -ab 448k -ar 48000 -c:a ac3 -c:v mpeg2video -f vob /var/folders/w1/l8xvpngj3b3f6l7m8y2xgyjm0000gn/T/UMS-lopopolo/ffmpegvideo_145_1498859232627
DEBUG 2017-06-30 14:47:12.946 [ffmpeg-14] Reading pipe: /var/folders/w1/l8xvpngj3b3f6l7m8y2xgyjm0000gn/T/UMS-lopopolo/ffmpegvideo_145_1498859232627
DEBUG 2017-06-30 14:47:12.985 [ffmpeg-14] Attaching thread: ffmpeg-14
DEBUG 2017-06-30 14:47:12.986 [ffmpeg-14] Unix process ID ("/Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg"): 34780
INFO  2017-06-30 14:47:12.987 [ffmpeg-14] Process "/Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg" has a return code of 1! Maybe an error occurred... check the log file
DEBUG 2017-06-30 14:47:12.987 [ffmpeg-14] Stopping Unix process 34779: mkfifo-15
```

running the command manually gives this error:

```console
$ "/Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg" -y -loglevel info -i /Users/lopopolo/Media-Server/xbr-test/vp9.mkv -bufsize 1835k -g 5 -q:v 1 -qmin 2 -qmax 3 -ab 448k -ar 48000 -c:a ac3 -c:v mpeg2video -f vob foo
ffmpeg version N-84607-g9bcc5e8-tessus Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --disable-ffplay --disable-indev=qtkit
  libavutil      55. 50.100 / 55. 50.100
  libavcodec     57. 86.102 / 57. 86.102
  libavformat    57. 67.100 / 57. 67.100
  libavdevice    57.  3.101 / 57.  3.101
  libavfilter     6. 78.100 /  6. 78.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, matroska,webm, from '/Users/lopopolo/Media-Server/xbr-test/vp9.mkv':
  Metadata:
    ENCODER         : Lavf56.1.0
  Duration: 00:00:32.25, start: 0.000000, bitrate: 554 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, smpte170m/unknown/unknown), 638x360, SAR 1:1 DAR 319:180, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(und): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      CREATION_TIME   : 2015-05-17 02:58:30
      LANGUAGE        : und
Stream mapping:
  Stream #0:0 -> #0:0 (vp9 (native) -> mpeg2video (native))
  Stream #0:1 -> #0:1 (aac (native) -> ac3 (native))
Press [q] to stop, [?] for help
[mpeg2video @ 0x7ff20500e800] Either both buffer size and max rate or neither must be specified
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
$ echo $?
1

```

changing the video codec to h264 with `-c:v h264` allows the video to be transcoded.

---
A flac file played fine on the TV
---
Some items in my test folder do not show up in the web ui

```
ERROR 2017-06-30 14:45:29.652 [pool-2-thread-6] Error adding child: "vp8.mkv"
java.lang.NullPointerException: null
	at net.pms.configuration.RendererConfiguration.calculatedSpeed(RendererConfiguration.java:2555)
	at net.pms.configuration.RendererConfiguration.getMaxVideoBitrate(RendererConfiguration.java:1843)
	at net.pms.configuration.RendererConfiguration.getMaxBandwidth(RendererConfiguration.java:1878)
	at net.pms.dlna.DLNAResource.resolvePlayer(DLNAResource.java:904)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:661)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:113)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:169)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1256)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:43)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:219)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
DEBUG 2017-06-30 14:45:29.653 [pool-2-thread-6] GlobalIdRepo: id not found: -1
ERROR 2017-06-30 14:45:29.677 [pool-2-thread-6] Error adding child: "vp8.webm"
java.lang.NullPointerException: null
	at net.pms.configuration.RendererConfiguration.calculatedSpeed(RendererConfiguration.java:2555)
	at net.pms.configuration.RendererConfiguration.getMaxVideoBitrate(RendererConfiguration.java:1843)
	at net.pms.configuration.RendererConfiguration.getMaxBandwidth(RendererConfiguration.java:1878)
	at net.pms.dlna.DLNAResource.resolvePlayer(DLNAResource.java:904)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:661)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:113)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:169)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1256)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:43)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:219)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
DEBUG 2017-06-30 14:45:29.677 [pool-2-thread-6] GlobalIdRepo: id not found: -1
```
As well as other folders in my tree:

```
15:08:02 ERROR Error adding child: "I love you and i miss you, so can you call me back-yzAS2vC5j-g.mp4"
java.lang.NullPointerException: null
	at net.pms.configuration.RendererConfiguration.calculatedSpeed(RendererConfiguration.java:2555)
	at net.pms.configuration.RendererConfiguration.getMaxVideoBitrate(RendererConfiguration.java:1843)
	at net.pms.configuration.RendererConfiguration.getMaxBandwidth(RendererConfiguration.java:1878)
	at net.pms.dlna.DLNAResource.resolvePlayer(DLNAResource.java:904)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:661)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.Playlist.discoverChildren(Playlist.java:120)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1387)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1250)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:43)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:219)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
15:08:02 ERROR Error adding child: "WHERESTHEDROP Karlie Kloss Serayah Calvin Harris-10153586824805369.mp4"
java.lang.NullPointerException: null
	at net.pms.configuration.RendererConfiguration.calculatedSpeed(RendererConfiguration.java:2555)
	at net.pms.configuration.RendererConfiguration.getMaxVideoBitrate(RendererConfiguration.java:1843)
	at net.pms.configuration.RendererConfiguration.getMaxBandwidth(RendererConfiguration.java:1878)
	at net.pms.dlna.DLNAResource.resolvePlayer(DLNAResource.java:904)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:661)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.Playlist.discoverChildren(Playlist.java:120)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1387)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1250)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:43)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:219)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
15:08:02 ERROR Error adding child: "painkiller-cats.mp4"
java.lang.NullPointerException: null
	at net.pms.configuration.RendererConfiguration.calculatedSpeed(RendererConfiguration.java:2555)
	at net.pms.configuration.RendererConfiguration.getMaxVideoBitrate(RendererConfiguration.java:1843)
	at net.pms.configuration.RendererConfiguration.getMaxBandwidth(RendererConfiguration.java:1878)
	at net.pms.dlna.DLNAResource.resolvePlayer(DLNAResource.java:904)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:661)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.Playlist.discoverChildren(Playlist.java:120)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1387)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1250)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:43)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:219)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
15:08:02 ERROR Error adding child: "Dj Premier - Classic Ft Rakim, Big L, Jay Z, Nas, Common, Slick Rick & Krs One-jGWUpNB2-xw.mp4"
java.lang.NullPointerException: null
	at net.pms.configuration.RendererConfiguration.calculatedSpeed(RendererConfiguration.java:2555)
	at net.pms.configuration.RendererConfiguration.getMaxVideoBitrate(RendererConfiguration.java:1843)
	at net.pms.configuration.RendererConfiguration.getMaxBandwidth(RendererConfiguration.java:1878)
	at net.pms.dlna.DLNAResource.resolvePlayer(DLNAResource.java:904)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:661)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:546)
	at net.pms.dlna.Playlist.discoverChildren(Playlist.java:120)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1387)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1250)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1171)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:43)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:219)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
---
Videos the renderer failed to play are still added to the recently played virtual folder

```
DEBUG 2017-06-30 15:08:23.093 [StopPlaying Event] adding "vp9" to playlist "Recently Played"
```

**Comment by Nadahar** [comment]
@lopopolo We need a full log file, lots of possible relevant stuff happens at other times than your snippets. The log also needs to be in ```TRACE``` mode, which is why you should first select "Create Trace logs" and restart UMS before "capturing" what fails.

**Comment by lopopolo** [comment]
sorry. thought i was being helpful. capturing a full log now

**Comment by lopopolo** [comment]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1116613/ums_dbg.zip)

- The TV has two renderers: the built in tv media server and a chromecast
- The chromecast plays more media and does it better

**Comment by Nadahar** [comment]
@lopopolo I'm not that into video codecs and transcoding, so @SubJunk better answer that part. I see multiple problems though:
* Since you're a mac user, the "Create Trace logs" function doesn't work. I fixed it in 0b3800d6b39c6b5d29933402df11361263603e98, but that was after the release of 6.71 so this fix isn't yet released. I don't know how you managed to create a trace log despite this, but I guess you simply set the log level to ```Trace``` manually and then restarted UMS? That will work too, but requires you to change it back when you're done "capturing", or your log will become very large and performance will suffer.
* The Chromecast support in UMS is extremely buggy and unmaintained. We currently have no developer that owns one, so its more or less impossible for us to fix it. Chromecast doesn't support UPnP or DLNA (which is what UMS use for all other renderers), which means that UMS doesn't really support Chromecast. Some effort was done to make it work by a previous developer that had one - which is what is still there, but it's very buggy and we can't do much about it. I think it would be better to simply disable Chromecast "support" than to use the buggy implementation we currently have, but that's another discussion. You can disable it manually by adding the line ```chromecast_extension = false``` to your ```UMS.conf```. It might make it easier to debug the other problems here, as I can see a lot of problems that seem to come from the chromecast code.
* The errors you had in your snippets above are no where to be seen in the full log.

The reason running the ffmpeg command manually doesn't work is because it uses an output pipe. UMS creates this pipe before starting FFmpeg - the pipe doesn't exist when you run it manually and it fails. You should be able to specify an output file instead to eliminate this.

The errors shown in your snippets above seems to be caused by the "automatic bandwidth" function, and it seems to be a bug that should be fixed - which is why I had hoped that they would be there in the full log as well. Disabling "automatic bandwidth" will probably eliminate those errors which will also make it easier to pin down the problem playing the files. I'd still like to figure out the bug in the automatic bandwidth code though.

**Comment by lopopolo** [comment]
[ums_dbg-2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1116766/ums_dbg-2.zip)

@Nadahar thank you for the config suggestions. I disabled chromecast support and automatic bitrate detection (I set `maximum_bitrate = 0`).

My FLAC failed to play and left a stacktrace in the logs. vp8.webm and vp8.mkv both began to play (video and sound appeared on TV) but cut out with a "connection reset by peer" message in the logs. My 4K h264 clip also failed to play (TV displays an error box that says "Cannot play video.").

Thank you!

**Comment by lopopolo** [comment]
Based on code diving from the [properties file](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e171dc3ae6fdb1413160bcbec767147d720ecb50/src/main/resources/i18n/messages.properties#L328), [through the UI](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e171dc3ae6fdb1413160bcbec767147d720ecb50/src/main/java/net/pms/newgui/GeneralTab.java#L390), to the [configuration](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/0b7bbe8a9adff458c035a921dd7612a4008ed354/src/main/java/net/pms/configuration/PmsConfiguration.java#L1689), I believe [`max_bitrate`](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/0b7bbe8a9adff458c035a921dd7612a4008ed354/src/main/java/net/pms/configuration/PmsConfiguration.java#L200) is the correct key.

I have an AC/N-only network and my laptop gets a symmetric (up & down) 500 mbps *to the Internet*. I hope that means things are fast enough.

**Comment by Nadahar** [comment]
@lopopolo Indeed, you're right. I thought there was a setting on the "Transcoding" tab that specified bitrate, and assumed that was what you'd changed. When I look now, I can't find any such setting though, so my mind is probably just playing tricks with me. The most important thing was to set ```automatic_maximum_bitrate = false``` though.

Even though your laptop -> router -> internet is fast (extremely fast internet line 😮), that doesn't mean that the link between the TV and the router is as fast. I doubt there's anyvway to measure the speed on the TV? Some online searches seems to indicate that the TV is N, but the signal strength rapidly kills the speed. Using "0" is too high in any case (as it's interpreted as 1000 mbps by UMS, much faster than even the theoretical maximum for N). I guess you'll just have to try different settings and see what works, but 150 should be the absolute maximum setting for a N connection.

**Comment by Nadahar** [comment]
@lopopolo Sorry, it seems like I was wrong again. According to [these specs](https://docs.sony.com/release//specs/XBR65X900E_mksp.pdf) the TV is AC too. I have no idea of what a "realistic" bandwidth for AC is, so forget about my 150 Mbps limit.

**Comment by Sami32** [comment]
@lopopolo You just need to use an appropriate renderer: (delete the fake _.txt_ extension before adding it into your UMS "renderer" folder.
[Sony-BraviaXBRX.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1118207/Sony-BraviaXBRX.conf.txt)

I added VP9 as well, so if you could test it and report back, that would be nice ;-)

**Comment by Nadahar** [comment]
@lopopolo I've tried to fix the errors you get while using automatic maximum bandwidth. I'd appreciate if you could try [this version](http://superbum.org/downloads/UMS-SpeedStatNPE.dmg) with automatic maximum bandwidth turned on. I haven't done anything with the actual calculation, so I still don't recommend using it, I simply want to get rid of the crashes/exceptions. This version also supports using "Create trace logs" on macOS.

**Comment by Sami32** [comment]
@lopopolo Did that solved your issue as expected ?

**Comment by lopopolo** [comment]
I am not intending on testing further as I am no longer using UMS
