### ISSUE TITLE
ERROR Failed to send action "GetPositionInfo"

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1329]
Recently I started getting an error when I stop playing a video:

```
ERROR 2017-06-30 23:08:12.873 [UPNP-VIERA VT60 Series] Failed to send action "GetPositionInfo" to VIERA VT60 Series: Error: Current state of service prevents invoking that action. Connection error or no response received.
TRACE 2017-06-30 23:08:12.877 [UPNP-VIERA VT60 Series] 
org.fourthline.cling.model.action.ActionException: Current state of service prevents invoking that action. Connection error or no response received.
	at org.fourthline.cling.protocol.sync.SendingAction.invokeRemote(SendingAction.java:77)
	at org.fourthline.cling.protocol.sync.SendingAction.executeSync(SendingAction.java:63)
	at org.fourthline.cling.protocol.sync.SendingAction.executeSync(SendingAction.java:51)
	at org.fourthline.cling.protocol.SendingSync.execute(SendingSync.java:54)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at org.fourthline.cling.controlpoint.ActionCallback.run(ActionCallback.java:151)
	at net.pms.network.UPNPControl.send(UPNPControl.java:681)
	at net.pms.network.UPNPControl.getPositionInfo(UPNPControl.java:823)
	at net.pms.network.UPNPControl$Renderer$1.run(UPNPControl.java:206)
	at java.lang.Thread.run(Unknown Source)
```

I don't notice anything other than the error - I'm still able to use the server fine afterwards.

**Comment by Nadahar** [comment]
@SubJunk I've improved the trace logging some places in ```UPNPControl``` when I did the work on ```protocolInfo```, so it's probably only that it was never logged before.

There are multiple bugs if the UPnP "control code" (the communication with the renderers about discovery, play state etc). The error is probably because UMS doesn't properly handle events/state and queries the position after the playback has stopped.

**Comment by SubJunk** [comment]
Ah ok. Well since nothing bad seems to happen, maybe we should log that one as DEBUG instead of ERROR, what do you think?

**Comment by Nadahar** [comment]
@SubJunk I prefer to fill oil the the oil lamp is lit instead of removing the bulb, but it's not that important to me. It's easy to change the log level, but it's probably also relatively easy to fix the code so that it doesn't keep sending queries about position after playback has stopped.

The problem is that the section that logs this doesn't just handle that situation, but any "command/action" being sent to a renderer that fails. My guess is that "GetPositionInfo" is used to update the player panel or some other similar non-critical feature. If the result of the action had more "serious" consequences, the error would be equally more serious.

**Comment by SubJunk** [comment]
I seem to get this after turning the TV off. Log snippet:

```
DEBUG 2019-02-16 10:41:53.975 [cling-1986] Subscription cancelled: AVTransport on uuid:4D454930-0100-1000-8001-000B977EA155: DEVICE_WAS_REMOVED
DEBUG 2019-02-16 10:41:53.975 [cling-1988] Subscription cancelled: RenderingControl on uuid:4D454930-0100-1000-8001-000B977EA155: DEVICE_WAS_REMOVED
DEBUG 2019-02-16 10:41:53.975 [cling-1986] VIERA VT60 Series is now offline.
DEBUG 2019-02-16 10:41:53.975 [cling-1990] Subscription cancelled: ConnectionManager on uuid:4D454930-0100-1000-8001-000B977EA155: DEVICE_WAS_REMOVED
ERROR 2019-02-16 10:41:55.670 [UPNP-VIERA VT60 Series] Failed to send action "GetPositionInfo" to VIERA VT60 Series: Error: Current state of service prevents invoking that action. Connection error or no response received.
TRACE 2019-02-16 10:41:55.670 [UPNP-VIERA VT60 Series] 
org.fourthline.cling.model.action.ActionException: Current state of service prevents invoking that action. Connection error or no response received.
	at org.fourthline.cling.protocol.sync.SendingAction.invokeRemote(SendingAction.java:77)
	at org.fourthline.cling.protocol.sync.SendingAction.executeSync(SendingAction.java:63)
	at org.fourthline.cling.protocol.sync.SendingAction.executeSync(SendingAction.java:51)
	at org.fourthline.cling.protocol.SendingSync.execute(SendingSync.java:54)
	at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
	at org.fourthline.cling.controlpoint.ActionCallback.run(ActionCallback.java:151)
	at net.pms.network.UPNPControl.send(UPNPControl.java:683)
	at net.pms.network.UPNPControl.getPositionInfo(UPNPControl.java:842)
	at net.pms.network.UPNPControl$Renderer$1.run(UPNPControl.java:207)
	at java.lang.Thread.run(Unknown Source)
```

The effect is just logspam but would be nice to fix still
