### ISSUE TITLE
The Master don't build anymore on Maven (WinXP 32-bit)

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1344]
Same with Java 7 or 8.
```logtalk
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (prepare-package-windows) on project ums: An Ant BuildException has occured: Failed to copy F:\UniversalMediaServer\target\bin\MediaInfo.dll to F:\UniversalMediaServer\MediaInfo.dll due to java.io.FileNotFoundException F:\UniversalMediaServer\MediaInfo.dll (Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus) and I couldn't delete the corrupt F:\UniversalMediaServer\MediaInfo.dll
[ERROR] around Ant part ...<copy todir="F:\UniversalMediaServer" file="F:\UniversalMediaServer/target/bin/MediaInfo.dll"/>... @ 5:98 in F:\UniversalMediaServer\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by Nadahar** [comment]
Try deleting ```F:\UniversalMediaServer\MediaInfo.dll```

**Comment by Sami32** [comment]
I already tried, and that didn't changed the result.

**Comment by Sami32** [comment]
```logtalk
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (prepare-package-windows) on project ums: An Ant BuildException has occured: Failed to copy F:\UniversalMediaServer\target\bin\MediaInfo.dll to F:\UniversalMediaServer\MediaInfo.dll due to java.io.FileNotFoundException F:\UniversalMediaServer\MediaInfo.dll (Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus) and I couldn't delete the corrupt F:\UniversalMediaServer\MediaInfo.dll
[ERROR] around Ant part ...<copy todir="F:\UniversalMediaServer" file="F:\UniversalMediaServer/target/bin/MediaInfo.dll"/>... @ 5:98 in F:\UniversalMediaServer\target\antrun\build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (prepare-package-windows) on project ums: An Ant BuildException has occured: Failed to copy F:\UniversalMediaServer\target\bin\MediaInfo.dll to F:\UniversalMediaServer\MediaInfo.dll due to java.io.FileNotFoundException F:\UniversalMediaServer\MediaInfo.dll (Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus) and I couldn't delete the corrupt F:\UniversalMediaServer\MediaInfo.dll
around Ant part ...<copy todir="F:\UniversalMediaServer" file="F:\UniversalMediaServer/target/bin/MediaInfo.dll"/>... @ 5:98 in F:\UniversalMediaServer\target\antrun\build-main.xml
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: Failed to copy F:\UniversalMediaServer\target\bin\MediaInfo.dll to F:\UniversalMediaServer\MediaInfo.dll due to java.io.FileNotFoundException F:\UniversalMediaServer\MediaInfo.dll (Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus) and I couldn't delete the corrupt F:\UniversalMediaServer\MediaInfo.dll
around Ant part ...<copy todir="F:\UniversalMediaServer" file="F:\UniversalMediaServer/target/bin/MediaInfo.dll"/>... @ 5:98 in F:\UniversalMediaServer\target\antrun\build-main.xml
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:342)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: F:\UniversalMediaServer\target\antrun\build-main.xml:5: Failed to copy F:\UniversalMediaServer\target\bin\MediaInfo.dll to F:\UniversalMediaServer\MediaInfo.dll due to java.io.FileNotFoundException F:\UniversalMediaServer\MediaInfo.dll (Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus) and I couldn't delete the corrupt F:\UniversalMediaServer\MediaInfo.dll
        at org.apache.tools.ant.taskdefs.Copy.doFileOperations(Copy.java:907)
        at org.apache.tools.ant.taskdefs.Copy.execute(Copy.java:563)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:313)
        ... 22 more
Caused by: java.io.FileNotFoundException: F:\UniversalMediaServer\MediaInfo.dll (Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at org.apache.tools.ant.types.resources.FileResource.getOutputStream(FileResource.java:259)
        at org.apache.tools.ant.types.resources.FileResource.getOutputStream(FileResource.java:234)
        at org.apache.tools.ant.util.ResourceUtils.getOutputStream(ResourceUtils.java:835)
        at org.apache.tools.ant.util.ResourceUtils.copyUsingStreams(ResourceUtils.java:811)
        at org.apache.tools.ant.util.ResourceUtils.copyResource(ResourceUtils.java:447)
        at org.apache.tools.ant.util.FileUtils.copyFile(FileUtils.java:559)
        at org.apache.tools.ant.taskdefs.Copy.doFileOperations(Copy.java:890)
        ... 35 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by Nadahar** [comment]
It's a simple file copy that fails. Either that's because the download fails first, or it's because the target file is locked or the file system is corrupt. Have you run a ```chkdsk F:```?

It's trying to copy ```F:\UniversalMediaServer\target\bin\MediaInfo.dll``` to ```F:\UniversalMediaServer\MediaInfo.dll```. Have you verified that the source file ```F:\UniversalMediaServer\target\bin\MediaInfo.dll``` is there?

**Comment by Sami32** [comment]
OK, sorry, i didn't deleted the good ones. I did with the ones inside the "target" folder only :flushed: 
Thank you for you help :+1:
