### ISSUE TITLE
NPE in SystemErrWrapper

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1362]
Taken from [this user log](http://www.universalmediaserver.com/forum/download/file.php?id=3971), that have nothing to do with his report.
Certainly happen because of that:
```logtalk
INFO  2017-08-12 22:35:18.637 [cling-12] net.pms.util.SystemErrWrapper [Fatal Error] :1:1: Fin prématurée du fichier.
DEBUG 2017-08-12 22:35:18.638 [cling-12] net.pms.network.UPNPControl Error parsing xml: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Fin prématurée du fichier.
```

```logtalk
TRACE 2017-08-12 22:35:18.531 [cling-11] net.pms.network.UPNPControl Received GetProtocolInfo from "1847868314": 
Sink:
  internal:192.168.0.2
  nds.com:dvb:MPEG:*
DEBUG 2017-08-12 22:35:18.531 [cling-11] net.pms.network.UPNPHelper Created upnp player for 1847868314
DEBUG 2017-08-12 22:35:18.559 [cling-12] net.pms.network.UPNPControl Subscription established: ConnectionManager on 1847868314
DEBUG 2017-08-12 22:35:18.563 [cling-9] net.pms.network.UPNPControl Subscription established: AVTransport on 1847868314
DEBUG 2017-08-12 22:35:18.566 [cling-6] net.pms.network.UPNPControl Subscription established: RenderingControl on 1847868314
INFO  2017-08-12 22:35:18.637 [cling-12] net.pms.util.SystemErrWrapper [Fatal Error] :1:1: Fin prématurée du fichier.
DEBUG 2017-08-12 22:35:18.638 [cling-12] net.pms.network.UPNPControl Error parsing xml: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Fin prématurée du fichier.
DEBUG 2017-08-12 22:35:18.638 [cling-6] net.pms.network.UPNPControl TransportState: NO_MEDIA_PRESENT
DEBUG 2017-08-12 22:35:18.639 [cling-6] net.pms.network.UPNPControl TransportStatus: OK
DEBUG 2017-08-12 22:35:18.639 [cling-6] net.pms.network.UPNPControl TransportPlaySpeed: 1
DEBUG 2017-08-12 22:35:18.639 [cling-6] net.pms.network.UPNPControl AbsoluteTimePosition: NOT_IMPLEMENTED
DEBUG 2017-08-12 22:35:18.639 [cling-6] net.pms.network.UPNPControl CurrentTransportActions: 
DEBUG 2017-08-12 22:35:18.639 [cling-6] net.pms.network.UPNPControl CurrentTrackURI: 
DEBUG 2017-08-12 22:35:18.639 [cling-6] net.pms.network.UPNPControl AVTransportURI: 
TRACE 2017-08-12 22:35:19.052 [cling-12] net.pms.network.UPNPControl Ignoring remote device: WFADevice (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:a10ffdf6-d83a-a36a-f32e-ab95f4da220e, Descriptor: http://192.168.0.1:1900/WFADevice.xml, Root: true
TRACE 2017-08-12 22:35:19.529 [main] net.pms.PMS Waiting 250 milliseconds...
DEBUG 2017-08-12 22:35:19.627 [ffmpeg64.exe-2-Cleanup] net.pms.io.ProcessWrapperImpl Stopping process: ffmpeg64.exe-2
TRACE 2017-08-12 22:35:19.627 [ffmpeg64.exe-2-Cleanup] net.pms.io.BufferedOutputFileImpl Destroying buffer
INFO  2017-08-12 22:35:19.639 [UPNP-1847868314] net.pms.util.SystemErrWrapper Exception in thread "UPNP-1847868314" java.lang.NullPointerException
INFO  2017-08-12 22:35:19.640 [UPNP-1847868314] net.pms.util.SystemErrWrapper 	at net.pms.network.UPNPControl.getPositionInfo(UPNPControl.java:818)
INFO  2017-08-12 22:35:19.640 [UPNP-1847868314] net.pms.util.SystemErrWrapper 	at net.pms.network.UPNPControl$Renderer$1.run(UPNPControl.java:206)
INFO  2017-08-12 22:35:19.640 [UPNP-1847868314] net.pms.util.SystemErrWrapper 	at java.lang.Thread.run(Unknown Source)
```

**Comment by Nadahar** [comment]
This log is from a non-standard UMS build (736b75e27).

**Comment by Nadahar** [comment]
While I can't test this or even check out this code, I've addressed what I think is the most likely cause in #1382.
