### ISSUE TITLE
RequestHandlerV2 Caught exception: Header values cannot be null

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#1366]
Taken from [this issue](http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=10508).
```logtalk
TRACE 2017-08-17 21:58:57.081 [HTTPv2 Request Worker 3] net.pms.network.RequestHandlerV2 
java.lang.NullPointerException: Header values cannot be null
	at org.jboss.netty.handler.codec.http.HttpHeaders.validateHeaderValue(HttpHeaders.java:1054)
	at org.jboss.netty.handler.codec.http.DefaultHttpHeaders.validateHeaderValue0(DefaultHttpHeaders.java:128)
	at org.jboss.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:228)
	at net.pms.network.RequestV2.answer(RequestV2.java:344)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:392)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:266)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
TRACE 2017-08-17 21:58:57.091 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil Converting byte array image source to SOURCE format and type DLNAThumbnail using the following parameters: PadToSize = False
TRACE 2017-08-17 21:58:57.096 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil Image conversion DLNA compliance check: The source image is compliant
TRACE 2017-08-17 21:58:57.096 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil No conversion is needed, returning source image with width = 320, height = 180 and output profile: JPEG_RES_320_180.
TRACE 2017-08-17 21:58:57.118 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil Converting byte array image source to SOURCE format and type DLNAThumbnail using the following parameters: PadToSize = False
TRACE 2017-08-17 21:58:57.122 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil Image conversion DLNA compliance check: The source image is compliant
TRACE 2017-08-17 21:58:57.122 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil No conversion is needed, returning source image with width = 320, height = 180 and output profile: JPEG_RES_320_180.
TRACE 2017-08-17 21:58:57.122 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil Converting byte array image source to JPEG_SM format and type DLNAThumbnail using the following parameters: PadToSize = False
TRACE 2017-08-17 21:58:57.125 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil Image conversion DLNA compliance check: The source image is compliant
TRACE 2017-08-17 21:58:57.126 [HTTPv2 Request Worker 2] net.pms.image.ImagesUtil No conversion is needed, returning source image with width = 320, height = 180 and output profile: JPEG_SM.
DEBUG 2017-08-17 21:58:57.126 [HTTPv2 Request Worker 2] net.pms.network.RequestHandlerV2 Caught exception: Header values cannot be null
TRACE 2017-08-17 21:58:57.127 [HTTPv2 Request Worker 2] net.pms.network.RequestHandlerV2 
java.lang.NullPointerException: Header values cannot be null
	at org.jboss.netty.handler.codec.http.HttpHeaders.validateHeaderValue(HttpHeaders.java:1054)
	at org.jboss.netty.handler.codec.http.DefaultHttpHeaders.validateHeaderValue0(DefaultHttpHeaders.java:128)
	at org.jboss.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:228)
	at net.pms.network.RequestV2.answer(RequestV2.java:344)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:392)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:266)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Nadahar** [comment]
Possible fix in #1383.
