### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1647]
I'm getting this in the current code, might be related to the new changes to connection logic @valib 

```
15:02:21 WARN  Setting SSDP network interface failed: {}
java.net.SocketException: The requested address is not valid in its context (Error setting socket option)
	at java.net.TwoStacksPlainDatagramSocketImpl.socketNativeSetOption(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.socketSetOption(Unknown Source)
	at java.net.AbstractPlainDatagramSocketImpl.setOption(Unknown Source)
	at java.net.MulticastSocket.setNetworkInterface(Unknown Source)
	at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:284)
	at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:221)
	at net.pms.network.UPNPHelper$1.run(UPNPHelper.java:415)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
I think this might have been a problem with my network
