### ISSUE TITLE
8.0.0-a2 fails on parsing WEB.conf file (working in 7.7.1)

### ISSUE THREAD

**Issue by felsen2011** [UniversalMediaServer/UniversalMediaServer#1739]
uname:
Linux odroid 4.14.87-153 #1 SMP PREEMPT Tue Dec 11 11:33:18 -02 2018 armv7l armv7l armv7l GNU/Linux

java version:
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK Client VM (build 25.191-b12, mixed mode)

log snippet:
ERROR 2018-12-29 14:22:53.098 [main] A serious error occurred during Universal Media Server initialization: null
TRACE 2018-12-29 14:22:53.102 [main]
java.lang.NullPointerException: null
        at net.pms.dlna.RootFolder.parseWebConf(RootFolder.java:514)
        at net.pms.dlna.RootFolder.loadWebConf(RootFolder.java:500)
        at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:199)
        at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:117)
        at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:507)
        at net.pms.PMS.getRootFolder(PMS.java:159)
        at net.pms.PMS.init(PMS.java:659)
        at net.pms.PMS.createInstance(PMS.java:900)
        at net.pms.PMS.main(PMS.java:1070)

[WEB.conf.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2716462/WEB.conf.txt)

**Comment by SubJunk** [comment]
@felsen2011 thanks for the details, I'm looking into this now

**Comment by felsen2011** [comment]
8.0.0-b1 fails some milliseconds later, can't give you the exact timing as i didn't save the original log (sorry, will do that for this run now).

log snippet:
DEBUG 2019-01-03 00:31:27.040 [main] Added file watch at [...]**
TRACE 2019-01-03 00:31:27.311 [main] Adding new child "Web" with class "VirtualFolder"
TRACE 2019-01-03 00:31:27.311 [main] Adding new child "Pictures" with class "VirtualFolder"
TRACE 2019-01-03 00:31:27.315 [main] Adding new child "1546475487314" with class "ImagesFeed"
ERROR 2019-01-03 00:31:27.316 [main] A serious error occurred during Universal Media Server initialization: null
TRACE 2019-01-03 00:31:27.320 [main]
java.lang.NullPointerException: null
        at net.pms.dlna.RootFolder.parseWebConf(RootFolder.java:604)
        at net.pms.dlna.RootFolder.loadWebConf(RootFolder.java:500)
        at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:199)
        at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:117)
        at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:507)
        at net.pms.PMS.getRootFolder(PMS.java:159)
        at net.pms.PMS.init(PMS.java:659)
        at net.pms.PMS.createInstance(PMS.java:900)
        at net.pms.PMS.main(PMS.java:1070)

**Comment by SubJunk** [comment]
@felsen2011 that makes sense, I'll try to fix it a less lazy way ;)

**Comment by felsen2011** [comment]
Starting up normally.
Web interface seems operational (don't use it usually)
Cache admin comes up.
DLNA Stream to my TV on first video I tried starts fine.

All these "GlobalIdRepo: id not found" Errors are gone from log \o/

I'll get back to you when sth crashes ;)

And thanks for this awesome piece of software!

**Comment by SubJunk** [comment]
@felsen2011 thanks for confirming :)
