### ISSUE TITLE
ffmpeg not executable

### ISSUE THREAD

**Issue by b0c1** [UniversalMediaServer/UniversalMediaServer#1866]
I installed ums using docker. When I start the application I got an error in docker log:
```
 [main] A serious error occurred during Universal Media Server initialization: Format specifier '%d'
```

I mapped out the `/var/log/UMS` and in the debug log I see:
```
DEBUG 2019-11-02 21:54:41.300 [TPW "ffmpeg64" 2] IOException when trying to start "ffmpeg64" process: Cannot run program "/usr/src/ums/linux/ffmpeg64": error=13, Permission denied
DEBUG 2019-11-02 21:54:41.317 [main] Starting /usr/src/ums/linux/ffmpeg64 -hwaccels
ERROR 2019-11-02 21:54:41.317 [main] Error initializing process:
DEBUG 2019-11-02 21:54:41.318 [main]
java.io.IOException: Cannot run program "/usr/src/ums/linux/ffmpeg64": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at net.pms.io.ProcessWrapperImpl.run(ProcessWrapperImpl.java:188)
        at net.pms.util.UMSUtils.checkGPUDecodingAccelerationMethodsForFFmpeg(UMSUtils.java:584)
        at net.pms.PMS.init(PMS.java:576)
        at net.pms.PMS.createInstance(PMS.java:900)
        at net.pms.PMS.main(PMS.java:1070)
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 5 common frames omitted
INFO  2019-11-02 21:54:41.322 [main] Configuration saved to "/root/.config/UMS/UMS.conf"
DEBUG 2019-11-02 21:54:41.333 [main] Checking transcoding engine FFmpeg Audio
DEBUG 2019-11-02 21:54:41.381 [main] /usr/bin/ffmpeg supported protocols: [async, cache, concat, crypto, data, ffrtmphttp, file, ftp, gopher, hls, http, httpproxy, https, mmsh, mmst, pipe, rtmp, rtmps, rtmpt, rt
mpts, rtp, srtp, subfile, tcp, tls, udp, udplite, unix, mms]
DEBUG 2019-11-02 21:54:41.382 [main] IOException when trying to start "ffmpeg64" process: Cannot run program "/usr/src/ums/linux/ffmpeg64": error=13, Permission denied
ERROR 2019-11-02 21:54:41.382 [main] A serious error occurred during Universal Media Server initialization: Format specifier '%d'
DEBUG 2019-11-02 21:54:41.382 [main]
java.util.MissingFormatArgumentException: Format specifier '%d'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at net.pms.encoders.FFMpegVideo.testExecutable(FFMpegVideo.java:1604)
        at net.pms.encoders.Player.testPlayer(Player.java:906)
        at net.pms.encoders.PlayerFactory.testPlayerExecutableType(PlayerFactory.java:206)
        at net.pms.encoders.PlayerFactory.registerPlayer(PlayerFactory.java:169)
        at net.pms.encoders.PlayerFactory.registerPlayers(PlayerFactory.java:120)
        at net.pms.encoders.PlayerFactory.initialize(PlayerFactory.java:106)
        at net.pms.PMS.init(PMS.java:612)
        at net.pms.PMS.createInstance(PMS.java:900)
        at net.pms.PMS.main(PMS.java:1070)

```

I checked in the docker container the ffmpeg files are not executable. Please add this to the UMS Dockerfile after the UMS copy
```sh
chmod ug=rwx /usr/src/ums/linux/ffmpeg64 /usr/src/ums/linux/ffmpeg /usr/src/ums/linux/tsMuxeR-new /usr/src/ums/linux/tsMuxeR
```

**Comment by SubJunk** [comment]
Thanks for reporting this, I think it is fixed now. Please feel free to reopen if you experience it again.
