### ISSUE TITLE
Bundled ffmpeg lookup fails on Linux

### ISSUE THREAD

**Issue by snicket2100** [UniversalMediaServer/UniversalMediaServer#1967]
I don't think this piece of code will ever be able to discover the bundled `ffmpeg`:

```java
		// We use the system FFmpeg if it exists, otherwise use ours
		Path ffmpeg = FileUtil.findExecutableInOSPath(Paths.get("ffmpeg"));
		ffmpegInfo = new FFmpegProgramInfo("FFmpeg", ProgramExecutableType.INSTALLED);
		if (ffmpeg != null) {
			ffmpegInfo.setPath(ProgramExecutableType.INSTALLED, ffmpeg);
		} else {
			ffmpeg = PLATFORM_BINARIES_FOLDER.resolve("ffmpeg");
			try {
				if (!new FilePermissions(ffmpeg).isExecutable()) {
					ffmpegInfo.setPath(ProgramExecutableType.BUNDLED, ffmpeg);
					LOGGER.trace("Insufficient permission to executable \"{}\"", ffmpeg);
				}
			} catch (FileNotFoundException e) {
				LOGGER.trace("Executable \"{}\" not found: {}", ffmpeg, e.getMessage());
			}
		}
```

I mean the `ffmpegInfo.setPath(ProgramExecutableType.BUNDLED, ffmpeg);` line which only gets executed if the `ffmpeg` binary isn't executable?! Anyway, the symptom is that whenever I try to run UMS on a Linux box without `ffmpeg` globally installed, it fails to start with the following error:

```
INFO  2020-04-10 14:17:52.530 [main] Checking the fontconfig cache in the background, this can take two minutes or so.
ERROR 2020-04-10 14:17:52.532 [main] A serious error occurred during Universal Media Server initialization: null
TRACE 2020-04-10 14:17:52.532 [TPW "null" 1] Executing " dummy"
DEBUG 2020-04-10 14:17:52.533 [main] 
java.lang.NullPointerException: null
	at net.pms.PMS.init(PMS.java:569)
	at net.pms.PMS.createInstance(PMS.java:916)
	at net.pms.PMS.main(PMS.java:1086)
```
which is due to a `NullPointerException` in this line `configuration.getFFmpegPaths().getDefaultPath().toString(),`.

I could've as well fixed that problem myself, just that there is some non-mavenized dependency in `pom.xml` and I couldn't easily build the project :/

**Comment by SubJunk** [comment]
@snicket2100 thanks for reporting this, I will look into it. Also if you can let us know which error you get when trying to build, that would be good. It should just work. Did you do this step? https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/BUILD.md#6-resolve-and-install-external-libraries

**Comment by snicket2100** [comment]
Aah, I missed that step indeed, having done it I can build the project without problems!

Regarding the `ffmpeg` problem itself, this patch:
```diff
diff --git a/src/main/java/net/pms/configuration/LinuxProgramPaths.java b/src/main/java/net/pms/configuration/LinuxProgramPaths.java
index 44dfe91f5..898faa6fe 100644
--- a/src/main/java/net/pms/configuration/LinuxProgramPaths.java
+++ b/src/main/java/net/pms/configuration/LinuxProgramPaths.java
@@ -55,9 +55,10 @@ public class LinuxProgramPaths extends PlatformProgramPaths {
                        ffmpegInfo.setPath(ProgramExecutableType.INSTALLED, ffmpeg);
                } else {
                        ffmpeg = PLATFORM_BINARIES_FOLDER.resolve("ffmpeg");
+                       ffmpegInfo.setPath(ProgramExecutableType.BUNDLED, ffmpeg);
+                       ffmpegInfo.setDefault(ProgramExecutableType.BUNDLED);
                        try {
                                if (!new FilePermissions(ffmpeg).isExecutable()) {
-                                       ffmpegInfo.setPath(ProgramExecutableType.BUNDLED, ffmpeg);
                                        LOGGER.trace("Insufficient permission to executable \"{}\"", ffmpeg);
                                }
                        } catch (FileNotFoundException e) {
```
seems to fix it on my machine. i.e. with it UMS can start without having `ffmpeg` globally installed. Sorry but I don't want to sent a pull request with it as I don't familiar with the best practices in the codebase that much.

**Comment by SubJunk** [comment]
Looks good, that patch should make it into our next release. Thanks
