### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2416]
https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14642

Looks like there is a missing column "MODIFIED" somewhere.

here are some of the errors i have found in his first log. 
He couldn't post the full trace log as it was too large so he cut out the first half. I have asked him to post the first half.

```
WARN  2021-03-05 15:19:55.401 [Library Scanner] Empty value passed in. Returning default number 2.

ERROR 2021-03-06 16:18:08.289 [DLNAResource resolver thread 325-3] Error in parsing stream: http://api.flickr.com/services/feeds/photos_public.gne?id=14362684@N08&format=rss2
com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 6: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:236)
	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)
	at net.pms.dlna.Feed.parse(Feed.java:68)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:52)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1408)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1394)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jdom2.input.JDOMParseException: Error on line 6: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:233)
	... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	... 12 common frames omitted
ERROR 2021-03-06 16:18:08.289 [DLNAResource resolver thread 325-1] Error in parsing stream: http://api.flickr.com/services/feeds/photos_public.gne?format=rss2
com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 6: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:236)
	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)
	at net.pms.dlna.Feed.parse(Feed.java:68)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:52)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1408)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1394)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jdom2.input.JDOMParseException: Error on line 6: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:233)
	... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	... 12 common frames omitted
ERROR 2021-03-06 16:18:08.289 [DLNAResource resolver thread 325-2] Error in parsing stream: http://api.flickr.com/services/feeds/photos_public.gne?id=39453068@N05&format=rss2
com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 6: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:236)
	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)
	at net.pms.dlna.Feed.parse(Feed.java:68)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:52)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1408)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1394)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jdom2.input.JDOMParseException: Error on line 6: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:233)
	... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: The element type "hr" must be terminated by the matching end-tag "</hr>".
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	... 12 common frames omitted
ERROR 2021-03-06 16:18:08.802 [DLNAResource resolver thread 325-1] Error in parsing stream: http://picasaweb.google.com/data/feed/base/user/FenderStratRocker?alt=rss&kind=album&hl=en_US&access=public
java.io.FileNotFoundException: http://picasaweb.google.com/data/feed/base/user/FenderStratRocker?alt=rss&kind=album&hl=en_US&access=public
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at net.pms.network.HTTPResource.downloadAndSendBinary(HTTPResource.java:239)
	at net.pms.network.HTTPResource.downloadAndSendBinary(HTTPResource.java:201)
	at net.pms.dlna.Feed.parse(Feed.java:66)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:52)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1408)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1394)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR 2021-03-06 16:18:10.195 [DLNAResource resolver thread 325-3] Error in parsing stream: http://picasaweb.google.fr/data/feed/base/user/nefuisalbum/albumid/5218433104757705489?alt=rss&kind=photo&hl=en_US
java.io.FileNotFoundException: http://get.google.com/albumarchive/pwa/data/feed/base/user/nefuisalbum/albumid/5218433104757705489?alt=rss&kind=photo&hl=en_US
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at net.pms.network.HTTPResource.downloadAndSendBinary(HTTPResource.java:239)
	at net.pms.network.HTTPResource.downloadAndSendBinary(HTTPResource.java:201)
	at net.pms.dlna.Feed.parse(Feed.java:66)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:52)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1408)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1394)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR 2021-03-06 16:18:15.495 [DLNAResource resolver thread 327-3] Error in parsing stream: https://www.unicef.org/rss/unicef_television_vodcast.xml
com.rometools.rome.io.ParsingFeedException: Invalid XML: Error on line 1: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:236)
	at com.rometools.rome.io.SyndFeedInput.build(SyndFeedInput.java:150)
	at net.pms.dlna.Feed.parse(Feed.java:68)
	at net.pms.dlna.Feed.resolveOnce(Feed.java:52)
	at net.pms.dlna.DLNAResource.resolve(DLNAResource.java:1408)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1394)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jdom2.input.JDOMParseException: Error on line 1: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
	at com.rometools.rome.io.WireFeedInput.build(WireFeedInput.java:233)
	... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	... 12 common frames omitted
ERROR 2021-03-06 17:24:21.352 [HTTPv2 Request Worker 30] null
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "MODIFIED" not found [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3214)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3287)
	at org.h2.jdbc.JdbcResultSet.getTimestamp(JdbcResultSet.java:494)
	at net.pms.dlna.DLNAMediaDatabase.getFiles(DLNAMediaDatabase.java:1584)
	at net.pms.dlna.virtual.MediaLibraryFolder.doRefreshChildren(MediaLibraryFolder.java:257)
	at net.pms.dlna.virtual.MediaLibraryFolder.discoverChildren(MediaLibraryFolder.java:107)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1290)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1153)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1075)
	at net.pms.network.RequestV2.browseSearchHandler(RequestV2.java:1147)
	at net.pms.network.RequestV2.browseHandler(RequestV2.java:1077)
	at net.pms.network.RequestV2.answer(RequestV2.java:659)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:404)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:260)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR 2021-03-06 17:24:22.365 [HTTPv2 Request Worker 30] null
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "MODIFIED" not found [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3214)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3287)
	at org.h2.jdbc.JdbcResultSet.getTimestamp(JdbcResultSet.java:494)
	at net.pms.dlna.DLNAMediaDatabase.getFiles(DLNAMediaDatabase.java:1584)
	at net.pms.dlna.virtual.MediaLibraryFolder.doRefreshChildren(MediaLibraryFolder.java:257)
	at net.pms.dlna.virtual.MediaLibraryFolder.discoverChildren(MediaLibraryFolder.java:107)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1290)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1153)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1075)
	at net.pms.network.RequestV2.browseSearchHandler(RequestV2.java:1147)
	at net.pms.network.RequestV2.browseHandler(RequestV2.java:1077)
	at net.pms.network.RequestV2.answer(RequestV2.java:659)
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:404)
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:260)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by valib** [comment]
This is not the database problem. I have the same error which is made by wrong parsing of the `http://api.flickr.com/services/feeds/photos_public.gne?id=14362684@N08&format=rss2` from the Shared WEB content.

> ERROR 2021-03-06 16:18:08.289 [DLNAResource resolver thread 325-3] Error in parsing stream: http://api.flickr.com/services/feeds/photos_public.gne?id=14362684@N08&format=rss2

**Comment by valib** [comment]
@SubJunk I think that api.flickr.com has made some changes and it causes problem. The same is for YouTube.

**Comment by Mik-S-UMS** [comment]
He has posted the full log file. It was nearly 1GB in size which is why he couldn't post it one go.

I have replied with what I have found on the forum, but it looks like an issue browsing the media library organised by date I think.

like "2020 09 27" for example, yet for "###" there is no issue even though the browse request from his TV is the same.

**Comment by SubJunk** [comment]
I have fixed the flickr bug, it turns out we just needed to use HTTPS for them instead of HTTP

**Comment by SubJunk** [comment]
I think this has been fixed
