### ISSUE TITLE
10.4.1: OpenSubtitles java.lang.NullPointerException error

### ISSUE THREAD

**Issue by esabol** [UniversalMediaServer/UniversalMediaServer#2449]
I'm seeing a lot of errors like this in my logs:
```
13:27:50 INFO  Exception in thread "OpenSubtitles background worker 93" java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
13:27:50 INFO  	at net.pms.database.TableTVSeries.set(TableTVSeries.java:124)
13:27:50 INFO  	at net.pms.util.OpenSubtitle.setTVSeriesInfo(OpenSubtitle.java:4813)
13:27:50 INFO  	at net.pms.util.OpenSubtitle.lambda$0(OpenSubtitle.java:4940)
13:27:50 INFO  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
13:27:50 INFO  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
13:27:50 INFO  	at java.base/java.lang.Thread.run(Unknown Source)
13:31:16 INFO  The file /path/to/the/file.mkv could not be parsed. It will be hidden
```
Looking in the full debug log, I see this:
```
TRACE 2021-03-31 13:27:50.370 [OpenSubtitles background worker 93] Removed entries 1 in FAILED_LOOKUPS for filename "/path/to/the/file.mkv"
INFO  2021-03-31 13:27:50.370 [OpenSubtitles background worker 92] 	at net.pms.util.OpenSubtitle.lambda$0(OpenSubtitle.java:4940)
INFO  2021-03-31 13:27:50.370 [OpenSubtitles background worker 92] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO  2021-03-31 13:27:50.370 [OpenSubtitles background worker 92] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO  2021-03-31 13:27:50.370 [OpenSubtitles background worker 92] 	at java.base/java.lang.Thread.run(Unknown Source)
DEBUG 2021-03-31 13:27:50.442 [OpenSubtitles background worker 93] OpenSubtitles hash for "file.mkv" is 2664e6370fd25186
TRACE 2021-03-31 13:27:50.442 [OpenSubtitles background worker 93] looking up episode: The File
DEBUG 2021-03-31 13:27:50.567 [OpenSubtitles background worker 93] API status was 404 for {"error":"Metadata not found."}
, https://api.universalmediaserver.com/api/media/video?title=The+File&season=1&episode=6&osdbHash=2664e6370fd25186&filebytesize=921184516
TRACE 2021-03-31 13:27:50.567 [OpenSubtitles background worker 93] Failed lookup for file.mkv
TRACE 2021-03-31 13:27:50.567 [OpenSubtitles background worker 93] Set new entry successfully in FAILED_LOOKUPS with "/path/to/the/file.mkv"
TRACE 2021-03-31 13:27:50.567 [OpenSubtitles background worker 93] Metadata for TV series The File (null) does not already exist in the database
TRACE 2021-03-31 13:27:50.567 [OpenSubtitles background worker 93] We have no failed lookups stored for thefile
TRACE 2021-03-31 13:27:50.567 [OpenSubtitles background worker 93] getting API info for TV series: The File, null, null
TRACE 2021-03-31 13:27:50.648 [OpenSubtitles background worker 93] Searching TV_SERIES with "SELECT * FROM TV_SERIES WHERE SIMPLIFIEDTITLE = 'thefile' LIMIT 1"
TRACE 2021-03-31 13:27:50.648 [OpenSubtitles background worker 93] No title match, so let's make a new entry for The File
TRACE 2021-03-31 13:27:50.648 [OpenSubtitles background worker 93] Searching in TV_SERIES with "SELECT * FROM TV_SERIES WHERE IMDBID = 'tt55555555’ LIMIT 1" before set
TRACE 2021-03-31 13:27:50.648 [OpenSubtitles background worker 93] Entry "thefile" not found in TV_SERIES, inserting
INFO  2021-03-31 13:27:50.649 [OpenSubtitles background worker 93] Exception in thread "OpenSubtitles background worker 93" java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
```

**Comment by SubJunk** [comment]
Thanks for reporting, this should be fixed in the next version
