### ISSUE TITLE
NullPointerException while using Web

### ISSUE THREAD

**Issue by gpascualg** [UniversalMediaServer/UniversalMediaServer#2652]
Steps to reproduce (it doesn't always happen):

Open the web and play any video. While it is playing, go back to the list (via browser back button) and then play another video.
The following error happens:
```
ERROR 2021-09-19 18:28:52.115 [pool-2-thread-1] Unexpected error on web interface. Please try closing any tabs or windows that contain UMS and try again
DEBUG 2021-09-19 18:28:52.116 [pool-2-thread-1]
java.lang.NullPointerException: null
        at net.pms.remote.RemoteWeb$RemotePollHandler.handle(RemoteWeb.java:657)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:72)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:700)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:672)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by SubJunk** [comment]
I think this is fixed now
