### ISSUE TITLE
Cannot run program "ping"

### ISSUE THREAD

**Issue by Maelep** [UniversalMediaServer/UniversalMediaServer#2753]
Customized docker image.

```java
ERROR 12:41:52.353 [pool-3-thread-1] Error initializing process: Cannot run program "ping": error=2, No such file or directory
WARN  12:41:52.354 [pool-3-thread-1] Error measuring network throughput : null
java.lang.NullPointerException: null
        at net.pms.network.SpeedStats$MeasureSpeed.doPing(SpeedStats.java:190)
        at net.pms.network.SpeedStats$MeasureSpeed.doCall(SpeedStats.java:146)
        at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:105)
        at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by SubJunk** [comment]
Is this on Ubuntu? `ping` isn't installed on Docker by default so you'll need the `iputils-ping` package, see https://stackoverflow.com/a/39901446/2049714

**Comment by Maelep** [comment]
> Is this on Ubuntu? `ping` isn't installed on Docker by default so you'll need the `iputils-ping` package, see https://stackoverflow.com/a/39901446/2049714

Yes, it's Ubuntu, thank you for your answer.
