### ISSUE TITLE
Endless socket hanging logs

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2855]
I have a hung process with logs:

```
INFO  2022-03-02 09:09:44.367 [UMS Shutdown] Stopping server on host 192.168.1.128 and port 5001...
ERROR 2022-03-02 09:09:44.367 [UPNPHelper] UPnP network exception: socket closed
TRACE 2022-03-02 09:09:44.369 [UPNPHelper] 
java.net.SocketException: socket closed
	at java.net.TwoStacksPlainDatagramSocketImpl.receive0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.receive(TwoStacksPlainDatagramSocketImpl.java:114)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$1(SocketSSDPServer.java:496)
	at java.lang.Thread.run(Thread.java:750)
TRACE 2022-03-02 09:09:44.369 [UPNPHelper] Final UPnP network exception: Socket is closed
TRACE 2022-03-02 09:09:44.369 [UPNPHelper] 
java.net.SocketException: Socket is closed
	at java.net.MulticastSocket.leaveGroup(MulticastSocket.java:435)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$1(SocketSSDPServer.java:565)
	at java.lang.Thread.run(Thread.java:750)
ERROR 2022-03-02 09:09:44.369 [UPNPHelper] UPnP network exception: Socket closed
TRACE 2022-03-02 09:09:44.369 [UPNPHelper] 
java.net.SocketException: Socket closed
	at java.net.TwoStacksPlainDatagramSocketImpl.receive0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.receive(TwoStacksPlainDatagramSocketImpl.java:114)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$1(SocketSSDPServer.java:496)
	at java.lang.Thread.run(Thread.java:750)
INFO  2022-03-02 09:09:44.370 [UMS Shutdown] Confirm allChannels is empty: DefaultChannelGroup(name: HTTPServer, size: 0)
TRACE 2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] Error when sending the ALIVE message: {}
java.net.SocketException: Socket is closed
	at java.net.DatagramSocket.send(DatagramSocket.java:658)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:324)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:296)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendAlive(SocketSSDPServer.java:261)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$0(SocketSSDPServer.java:477)
	at java.lang.Thread.run(Thread.java:750)
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] Exception in thread "UPNP-AliveMessageSender" java.lang.IllegalArgumentException: unsupported address type
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] 	at java.net.DatagramPacket.setSocketAddress(DatagramPacket.java:313)
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] 	at java.net.DatagramPacket.<init>(DatagramPacket.java:144)
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] 	at java.net.DatagramPacket.<init>(DatagramPacket.java:178)
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:315)
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:296)
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendAlive(SocketSSDPServer.java:261)
INFO  2022-03-02 09:09:44.423 [UPNP-AliveMessageSender] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$0(SocketSSDPServer.java:477)
INFO  2022-03-02 09:09:44.424 [UPNP-AliveMessageSender] 	at java.lang.Thread.run(Thread.java:750)
```

It repeats the `UPnP network exception: socket closed` and `Final UPnP network exception: Socket is closed` logs endlessly. It is on d40dd0427 which may no longer be relevant given the v11 branch, but I thought I would mention it while I saw it @SurfaceS 
If it's no longer relevant we can close it

**Comment by SurfaceS** [comment]
already fixed in v11
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/687586bd8f9e08ecfd05b1bcc4aa7401df82ec07/src/main/java/net/pms/network/mediaserver/socketssdpserver/SocketSSDPServer.java
