### ISSUE TITLE
"UPnP network exception: Socket closed" error on server restart

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2899]
A user on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=15034) has reported this error coming up repeatedly after restarting the server since 10.17.0 and 2 others have the same issue. I tested this on mine and it happens to me too.
As far as I can tell it is coming from UPNP-AliveMessageSender, maybe that is not reset when the server is?

My logs are posted on the forum but i think this part is significant
`TRACE 2022-03-18 19:17:24.325 [UPNP-AliveMessageSender] Error when sending the ALIVE message: {}
java.net.SocketException: Socket is closed
	at java.net.DatagramSocket.send(DatagramSocket.java:658)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:324)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:296)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendAlive(SocketSSDPServer.java:261)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$0(SocketSSDPServer.java:477)
	at java.lang.Thread.run(Thread.java:750)`

**Comment by SubJunk** [comment]
It happens to me too

**Comment by schroef** [comment]
I tried it on OSX and check the web interface button, nothing loaded. Then noticed tons of errors in the log panel. Also this same error

**Comment by dmitche3** [comment]
Same here.  Doing a restart causes with nothing connected to the socket causes the following message to repeat with the thread # changing, of course.

ERROR 2022-07-23 21:06:59.930 [UPNPHelper] UPnP network exception: Socket closed
TRACE 2022-07-23 21:06:59.930 [UPNPHelper] 
java.net.SocketException: Socket closed
	at java.net.TwoStacksPlainDatagramSocketImpl.receive0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.receive(TwoStacksPlainDatagramSocketImpl.java:114)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$1(SocketSSDPServer.java:496)
	at java.lang.Thread.run(Thread.java:750)
TRACE 2022-07-23 21:06:59.946 [background-task-0-restart(0)] Error when sending the ALIVE message: {}
java.net.SocketException: Socket is closed
	at java.net.DatagramSocket.send(DatagramSocket.java:658)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:324)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:296)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendAlive(SocketSSDPServer.java:261)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.start(SocketSSDPServer.java:103)
	at net.pms.network.mediaserver.MediaServer.start(MediaServer.java:83)
	at net.pms.PMS.lambda$reset$0(PMS.java:832)
	at net.pms.util.TaskRunner.lambda$submitNamed$0(TaskRunner.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
TRACE 2022-07-23 21:06:59.999 [background-task
