### ISSUE TITLE
Detected Media Renderers not showing custom renderers

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#2917]
A user on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=15072) has found that if using a custom conf for their renderer then it will not appear in under the Detected Media Renderers on the Status tab since 10.16.0 when it was working previously.

I see an exception error in his logs referring to nettyserver right after the renderer is detected.

```
DEBUG 2022-04-07 19:50:13.959 [HTTPv2 Request Worker 2] net.pms.network.mediaserver.nettyserver.RequestHandlerV2 Caught exception: null

TRACE 2022-04-07 19:50:13.960 [HTTPv2 Request Worker 2] net.pms.network.mediaserver.nettyserver.RequestHandlerV2 
java.lang.NullPointerException: null
	at net.pms.network.mediaserver.UPNPControl.getURL(UPNPControl.java:339)
	at net.pms.network.mediaserver.UPNPControl.getAddress(UPNPControl.java:820)
	at net.pms.configuration.RendererConfiguration.getAddress(RendererConfiguration.java:1565)
	at net.pms.newgui.StatusTab$RendererItem.<init>(StatusTab.java:91)
	at net.pms.newgui.StatusTab.addRenderer(StatusTab.java:388)
	at net.pms.newgui.LooksFrame.addRenderer(LooksFrame.java:791)
	at net.pms.PMS.setRendererFound(PMS.java:202)
	at net.pms.configuration.RendererConfiguration.resolve(RendererConfiguration.java:687)
	at net.pms.configuration.RendererConfiguration.getRendererConfigurationByHeaders(RendererConfiguration.java:594)
	at net.pms.configuration.RendererConfiguration.getRendererConfigurationByHeaders(RendererConfiguration.java:586)
	at net.pms.network.mediaserver.nettyserver.RequestHandlerV2.messageReceived(RequestHandlerV2.java:138)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by SubJunk** [comment]
Probably one for @SurfaceS

**Comment by Mik-S-UMS** [comment]
I managed to replicate this. 
It is the `Device = IP number` setting that is automatically added when creating a custom conf from an existing renderer inside UMS. 
```

#----------------------------------------------------------------------------
# Custom Device profile
# See DefaultRenderer.conf for descriptions of all possible renderer options
# and UMS.conf for program options.

# Options in this file override the default settings for the specific PlayStation 4 mod device(s) listed below.
# Specify devices by uuid (or address if no uuid), separated by commas if more than one.

Device = 192.168.1.67
#----------------------------------------------------------------------------
# Profile for Sony PlayStation 4.
# See DefaultRenderer.conf for descriptions of all the available options.
#
RendererName = PlayStation 4 mod2 test
RendererIcon = ps4.png
```

```
INFO  2022-04-11 02:20:58.823 [pool-7-thread-1] Checking IP: 192.168.1.67 for PlayStation 4 mod2 test
DEBUG 2022-04-11 02:20:58.839 [HTTPv2 Request Worker 7] Caught exception: null
TRACE 2022-04-11 02:20:58.841 [HTTPv2 Request Worker 7] 
java.lang.NullPointerException: null
	at net.pms.network.mediaserver.UPNPControl.getURL(UPNPControl.java:339)
	at net.pms.network.mediaserver.UPNPControl.getAddress(UPNPControl.java:820)
	at net.pms.configuration.RendererConfiguration.getAddress(RendererConfiguration.java:1565)
	at net.pms.newgui.StatusTab$RendererItem.<init>(StatusTab.java:91)
	at net.pms.newgui.StatusTab.addRenderer(StatusTab.java:388)
	at net.pms.newgui.LooksFrame.addRenderer(LooksFrame.java:791)
	at net.pms.PMS.setRendererFound(PMS.java:202)
	at net.pms.configuration.RendererConfiguration.resolve(RendererConfiguration.java:687)
	at net.pms.configuration.RendererConfiguration.getRendererConfigurationByHeaders(RendererConfiguration.java:594)
	at net.pms.configuration.RendererConfiguration.getRendererConfigurationByHeaders(RendererConfiguration.java:586)
	at net.pms.network.mediaserver.nettyserver.RequestHandlerV2.messageReceived(RequestHandlerV2.java:138)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
