### ISSUE TITLE
Error in RealFile.resolve: Text 'Encoded_Date' could not be parsed at index 0

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#2946]
From our logs in v11:
```
java.time.format.DateTimeParseException: Text 'Encoded_Date' could not be parsed at index 0
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
	at java.base/java.time.format.DateTimeFormatter.parse(Unknown Source)
	at java.base/java.time.LocalTime.parse(Unknown Source)
	at net.pms.dlna.LibMediaInfoParser.parse(LibMediaInfoParser.java:147)
	at net.pms.configuration.FormatConfiguration.parse(FormatConfiguration.java:598)
	at net.pms.formats.Format.parse(Format.java:292)
	at net.pms.dlna.RealFile.resolve(RealFile.java:268)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1528)
	at net.pms.dlna.RealFile.syncResolve(RealFile.java:441)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1327)
	at net.pms.dlna.RealFile.isValid(RealFile.java:106)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:553)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:290)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:371)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:319)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:329)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:276)
	at net.pms.dlna.LibraryScanner.lambda$scanLibrary$0(LibraryScanner.java:41)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
@SurfaceS it looks like this bug may have been introduced around https://github.com/UniversalMediaServer/UniversalMediaServer/commit/a15e47279d986a3b475859370a5de5606770c336

**Comment by SurfaceS** [comment]
was fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2843/commits/96a7caae2d68da50cdf5657aa13f962160d541b7
