### ISSUE TITLE
Samsung BD-C5500

### ISSUE THREAD

**Issue by peoii** [UniversalMediaServer/UniversalMediaServer#302]
After upgrading to 3.6.0, on a Windows 7 Machine running JRE 1.7.0_55-b13  I am getting the following log error when browsing to this folder on my media server.  Now that said, every other series seems to work fine, it's just this one, and specifically 3 episodes in the middle of the season.  The 6x09 shows fine, 6x13 shows, but 10-12 all produce this exact same error when I navigate to the containing folder.

```
05-01 20:19:28  Error adding child: "Castle (2009) - 6x12 - Deep Cover.mp4"
java.lang.NullPointerException: null
    at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:726) [ums.jar:3.6.0]
    at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:479) [ums.jar:3.6.0]
    at net.pms.dlna.MapFile.manageFile(MapFile.java:116) [ums.jar:3.6.0]
    at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:169) [ums.jar:3.6.0]
    at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:973) [ums.jar:3.6.0]
    at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:889) [ums.jar:3.6.0]
    at net.pms.network.RequestV2.answer(RequestV2.java:654) [ums.jar:3.6.0]
    at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:288) [ums.jar:3.6.0]
    at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:246) [ums.jar:3.6.0]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:3.6.0]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:3.6.0]
    at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [ums.jar:3.6.0]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:3.6.0]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [ums.jar:3.6.0]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [ums.jar:3.6.0]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [ums.jar:3.6.0]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [ums.jar:3.6.0]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:3.6.0]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [ums.jar:3.6.0]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [ums.jar:3.6.0]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [ums.jar:3.6.0]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [ums.jar:3.6.0]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [ums.jar:3.6.0]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [ums.jar:3.6.0]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [ums.jar:3.6.0]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [ums.jar:3.6.0]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [ums.jar:3.6.0]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [ums.jar:3.6.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_55]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_55]
    at java.lang.Thread.run(Unknown Source) [na:1.7.0_55]
```

**Comment by Sami32** [comment]
@peoii Did the latest UMS version solved this issue ?
If not, please, post your log following these instructions:
http://www.universalmediaserver.com/forum/viewtopic.php?f=3&t=556

Perhaps it have nothing to do with your issue, but do you MP4 video giving this problem have CoverArt ID3Tag ?
