### ISSUE TITLE
Database "medias" error while writing in "VIDEO_METADATA_POSTERS" for ""

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3132]
I see this error in my logs from time to time, doesn't seem to do noticeable damage but would be good to figure out why

```
ERROR 2022-07-03 15:11:02.492 [OpenSubtitles background worker 1] Database "medias" error while writing in "VIDEO_METADATA_POSTERS" for "": Unique index or primary key violation: "PUBLIC.FILENAME_POSTER_TVSERIESID_IDX ON PUBLIC.VIDEO_METADATA_POSTERS(FILENAME NULLS FIRST, TVSERIESID NULLS FIRST) VALUES ( /* key:1082 */ '', 168)"; SQL statement:
INSERT INTO VIDEO_METADATA_POSTERS (TVSERIESID, FILENAME, POSTER) VALUES (?, ?, ?) [23505-214]
TRACE 2022-07-03 15:11:02.494 [OpenSubtitles background worker 1] 
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.FILENAME_POSTER_TVSERIESID_IDX ON PUBLIC.VIDEO_METADATA_POSTERS(FILENAME NULLS FIRST, TVSERIESID NULLS FIRST) VALUES ( /* key:1082 */ '', 168)"; SQL statement:
INSERT INTO VIDEO_METADATA_POSTERS (TVSERIESID, FILENAME, POSTER) VALUES (?, ?, ?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.CommandContainer.executeUpdateWithGeneratedKeys(CommandContainer.java:242)
	at org.h2.command.CommandContainer.update(CommandContainer.java:163)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at net.pms.database.MediaTableVideoMetadataPosters.set(MediaTableVideoMetadataPosters.java:224)
	at net.pms.util.APIUtils.setTVSeriesInfo(APIUtils.java:690)
	at net.pms.util.APIUtils.lambda$backgroundLookupAndAddMetadata$0(APIUtils.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
I haven't seen this for a long time so I think it was fixed
