### ISSUE TITLE
playing Youtube streams causes java exceptions

### ISSUE THREAD

**Issue by Demonsthere** [UniversalMediaServer/UniversalMediaServer#3134]
Hello there, and thanks for the active development of this project! 

Small issue I found when using the web content. Adding a new web based source using the feed xml method (`https://www.youtube.com/feeds/videos.xml?channel_id=UChmm356a5qe1luUsoatAgjA`) is generating a valid object in the UI, with proper video data. However when playing one of those streams in the logs I can see a ffmpeg based error:

```shell
15:22:52 INFO  Process /Applications/Universal Media Server.app/Contents/Resources/osx/ffmpeg has a return code of 1! Maybe an error occurred... check the log file
15:22:53 INFO  Started playing Tales Under The Oak - The Toad King (2021) (Dungeon Synth) on your Chrome
15:27:11 INFO  Exception in thread "ServerSentEvents ping" java.lang.NullPointerException
15:27:11 INFO  	at net.pms.network.webinterfaceserver.ServerSentEvents.close(ServerSentEvents.java:47)
15:27:11 INFO  	at net.pms.network.webinterfaceserver.ServerSentEvents.lambda$startPing$0(ServerSentEvents.java:85)
15:27:11 INFO  	at java.lang.Thread.run(Thread.java:750)
15:27:22 ERROR External input stream instance is null... stopping process
```

However, even setting the log level to debug or trace does not provide more data. I am providing the debug zip package: [ums_dbg_2022-07-03-15-31.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/9034860/ums_dbg_2022-07-03-15-31.zip)

**Comment by SubJunk** [comment]
@Demonsthere thanks for reporting this, I have reproduced it too on macOS. I'll do some digging

**Comment by SubJunk** [comment]
This is being worked on in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4785

**Comment by SubJunk** [comment]
There's a new issue for this work https://github.com/UniversalMediaServer/UniversalMediaServer/issues/4807

**Comment by SubJunk** [comment]
This fix is being released now
