### ISSUE TITLE
Web feeds and streams don't ply video

### ISSUE THREAD

**Issue by MGAnton** [UniversalMediaServer/UniversalMediaServer#3204]
I have installed UMS-11.3.0, Debian 11-Xfce and openjdk-11. Web feeds and streams work fine with pictures, podcasts and radio, but when I play video, if I run UMS from terminal, system returns:
INFO  01:07:43.873 [ServerSentEvents ping] Exception in thread "ServerSentEvents ping" java.lang.NullPointerException: Cannot invoke "java.io.OutputStream.close()" because "this.os" is null
INFO  01:07:43.873 [ServerSentEvents ping] 	at net.pms.network.webinterfaceserver.ServerSentEvents.close(ServerSentEvents.java:47)
INFO  01:07:43.873 [ServerSentEvents ping] 	at net.pms.network.webinterfaceserver.ServerSentEvents.lambda$startPing$0(ServerSentEvents.java:85)
INFO  01:07:43.874 [ServerSentEvents ping] 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by SubJunk** [comment]
@MGAnton is this fixed now?
