### ISSUE TITLE
Startup freeze

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3622]
I got a startup crash while building the 12.0.0 release. I'm fixing it now and will abort the release and do 12.0.1 instead
```
java.lang.NullPointerException: Cannot invoke "java.io.File.getPath()" because the return value of "net.pms.configuration.sharedcontent.FolderContent.getFile()" is null
	at net.pms.newgui.SharedContentTab.refreshSharedContent(SharedContentTab.java:466)
	at net.pms.newgui.SharedContentTab.updateSharedContent(SharedContentTab.java:165)
	at net.pms.configuration.sharedcontent.SharedContentConfiguration.addListener(SharedContentConfiguration.java:120)
	at net.pms.newgui.SharedContentTab.build(SharedContentTab.java:140)
	at net.pms.newgui.LooksFrame.buildMain(LooksFrame.java:550)
	at net.pms.newgui.LooksFrame.buildContent(LooksFrame.java:520)
	at net.pms.newgui.LooksFrame.<init>(LooksFrame.java:376)
	at net.pms.PMS.init(PMS.java:485)
	at net.pms.PMS.createInstance(PMS.java:867)
	at net.pms.PMS.main(PMS.java:1021)
```

**Comment by SubJunk** [comment]
On startup on macOS after fixing this bug, I get another one where I have to click this popup about 20 times in a row. In v11 you just click it one time on startup.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/584228/202786411-6adb6dac-f79c-401f-979c-33fe4faa5630.png">

**Comment by SubJunk** [comment]
Looking at the logs after each time I click `OK`, it is re-prompting for the permission when it adds a new `file watch` in that folder
