### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#3693]
In https://github.com/UniversalMediaServer/UniversalMediaServer/pull/3680/files I seem to have caused a database error:

```
TRACE 2022-12-15 20:58:51.885 [jupnp-netty-worker-2] 
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "HDRFORMAT" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3492)
	at org.h2.jdbc.JdbcResultSet.updateString(JdbcResultSet.java:1864)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.updateString(HikariProxyResultSet.java)
	at net.pms.database.MediaTableFiles.insertOrUpdateData(MediaTableFiles.java:702)
	at net.pms.dlna.DLNAResource.registerExternalSubtitles(DLNAResource.java:3984)
```

but the column does exist when I view with h2database:

![image](https://user-images.githubusercontent.com/584228/207941707-007aa66b-aa91-4c57-b717-cc456c776e9a.png)

I must be missing something hopefully obvious, can someone help? @UniversalMediaServer/developers

**Comment by SubJunk** [comment]
Ok it was obvious, good thing I am on holiday soon I clearly need it..
