### ISSUE TITLE
java.lang.ExceptionInInitializerError on FreeBSD 13.1-STABLE

### ISSUE THREAD

**Issue by ppoloskov** [UniversalMediaServer/UniversalMediaServer#3784]
I'm trying to run UMS under FreeBSD jail, however I stumble upon error (see below). As far as I understand it caused by FreeBSD not following semantic versioning (the version I use is 13.1-STABLE):

``` shell
# uname -a
FreeBSD dlna 13.1-STABLE FreeBSD 13.1-STABLE #1 stable/13-n253485-de1ce17d2305: Tue Jan 17 23:37:32 AEST 2023     root@roots:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

```

``` shell
# ./UMS.sh
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.pms.PMS.main(PMS.java:959)
Caused by: com.vdurmont.semver4j.SemverException: Invalid version (no patch version): 13.1-STABLE.0
	at com.vdurmont.semver4j.Semver.<init>(Semver.java:81)
	at com.vdurmont.semver4j.Semver.<init>(Semver.java:20)
	at net.pms.platform.PlatformUtils.createOsVersion(PlatformUtils.java:369)
	at net.pms.platform.PlatformUtils.<clinit>(PlatformUtils.java:68)
	... 1 more
```

**Comment by SubJunk** [comment]
@ppoloskov thanks for posting this, I'll post a fix to test soon

**Comment by SubJunk** [comment]
@ppoloskov I realised I don't know which release to upload for you, what file do you usually download?

**Comment by SubJunk** [comment]
I'm going to close this issue since it is fixed, but I'm still happy to upload a fixed version for you if you let me know

**Comment by ppoloskov** [comment]
HI @SubJunk I use generic x89_64 build.

**Comment by SubJunk** [comment]
@ppoloskov please let me know when you've downloaded it https://www.universalmediaserver.com/uploads/UMS-3784.tgz

**Comment by ppoloskov** [comment]
HI @SubJunk downloaded, thank you
