### ISSUE TITLE
Can't run and start UMS because occurs "Semver Exception" in PlatformUtils since UMS 12.0.1

### ISSUE THREAD

**Issue by mitsurina** [UniversalMediaServer/UniversalMediaServer#3838]
I'm using UMS with "non-GUI" on raspberry pi 3.
The UMS package I always download is "Linux (armhf package)".
Up to 11.6.0, it was working fine.

But after 12.0.1 I got the below exception and UMS no longer starts. 
13.2.0 gives the exact same exception and UMS won't start.

"debug.log" was not output either, probably because UMS failed to start. First the "debug.log" file was not created.
Setting the logging level in "UMS.conf" to "TRACE" did not create "debug.log".
Below is the exception printed to the console.

---------------------------------------------------------------------------------------------------

Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.pms.util.FilePermissions.checkPermissions(FilePermissions.java:208)
        at net.pms.util.FilePermissions.getFlags(FilePermissions.java:384)
        at net.pms.util.FileUtil.findInOSPath(FileUtil.java:2358)
        at net.pms.util.FileUtil.findExecutableInOSPath(FileUtil.java:2281)
        at net.pms.platform.linux.LinuxProgramPaths.<init>(LinuxProgramPaths.java:53)
        at net.pms.platform.PlatformProgramPaths.<clinit>(PlatformProgramPaths.java:202)
        at net.pms.configuration.UmsConfiguration.<init>(UmsConfiguration.java:745)
        at net.pms.configuration.UmsConfiguration.<init>(UmsConfiguration.java:696)
        at net.pms.PMS.main(PMS.java:955)
Caused by: com.vdurmont.semver4j.SemverException: The build cannot be empty.
        at com.vdurmont.semver4j.Semver.<init>(Semver.java:100)
        at com.vdurmont.semver4j.Semver.<init>(Semver.java:20)
        at net.pms.platform.PlatformUtils.createOsVersion(PlatformUtils.java:369)
        at net.pms.platform.PlatformUtils.<clinit>(PlatformUtils.java:68)
        ... 9 more

---------------------------------------------------------------------------------------------------

Below is my execution environment.
---------------------------------------------------------------------------------------------------
[System]
	Raspberry Pi 3 Model B Rev 1.2 (Linux raspberrypi 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux)

[OS]
	Raspbian GNU/Linux 11 (bullseye)

[Java]
	openjdk version "17.0.6" 2023-01-17

	OpenJDK Runtime Environment (build 17.0.6+10-Raspbian-1deb11u1rpt1)
	OpenJDK Client VM (build 17.0.6+10-Raspbian-1deb11u1rpt1, mixed mode, emulated-client)
---------------------------------------------------------------------------------------------------
In my execution environment, it was working fine until 11.6.0.
Please let me know if there is anything I can do to make 12.0.1 or later work as well.

If it is a bug, please fix it as soon as possible.
best regards.

**Comment by SubJunk** [comment]
This has been fixed in 13.2.1, thanks for reporting it
