### ISSUE TITLE
13.3.0: HikariPool-1 (or 2) - Thread starvation or clock leap detected (housekeeper delta=50s2ms).

### ISSUE THREAD

**Issue by esabol** [UniversalMediaServer/UniversalMediaServer#3903]
I saw this with 13.2.0 as well, fwiw. After UMS has been running for a couple days, I frequently get log messages that say:
```
WARN  2023-04-20 19:59:07.503 [HikariPool-2 housekeeper] HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=50s2ms).
WARN  2023-04-20 19:59:34.625 [HikariPool-1 housekeeper] HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=50s2ms).
```
A good chunk of my log files are messages like this repeated over and over.

System info, FYI:
```
WARN  2023-04-21 22:41:20.434 [System Information Logger] Failed sysctl call: hw.nperflevels, Error code: 2
INFO  2023-04-21 22:41:20.541 [System Information Logger] System information:
  OS: Apple macOS 10.13.6 (High Sierra) build 17G14042 64-bit
  JVM: OpenJDK 64-Bit Server VM 17.0.4.1 (64-bit) by BellSoft
  Language: English (United States)
  Encoding: UTF-8
  CPU: Intel(R) Xeon(R) CPU           W3680  @ 3.33GHz with 6 cores (12 virtual cores) (Westmere (Server))
  Physical Memory: 48 GiB
  Free Memory: 22.8 GiB
  Maximum JVM Memory: 2 GiB
  Used network interfaces:
  Ethernet 1, speed 1000 Mb/s
```

**Comment by SubJunk** [comment]
I think this just means the computer has woken from sleep, and Hikari has detected that the clock has "leapt" forward. It's not a problem

**Comment by esabol** [comment]
@SubJunk, except my computer never sleeps. I have all sleep functionality completely turned off.

**Comment by esabol** [comment]
https://stackoverflow.com/a/67436783 says:
> Another reason why this is happening is due to excessive garbage collection, when garbage collection was running for a longer time within two executions of housekeeping thread, trying to free up some memory(e.g exactly when an application thread was running a 'select' query). Since the GC was blocking all application threads including the housekeeping thread, as such my suspicion is that the clock "leapt" due to that.

https://stackoverflow.com/a/67148145 says:
> I was facing this issue because of an infinite loop in my hashCode method of the Entity.
> 
> Two entities had OneToMany relationship and I was using lombok @Data annotation which generates equals and hashcode implementation itself by calling hashCode() method for each attribute which was causing the infinite loop.

**Comment by SubJunk** [comment]
Ah I see. On my computer it happens after sleeping so I thought it would be the same for yours. I'll reopen this

**Comment by elektronen** [comment]
Just want to note this remains an issue in 14.3.0, and I am also on macOS High Sierra (10.13.6). When enough of these occur, the application becomes unresponsive, and I have to Force Quit, then relaunch.

**Comment by SubJunk** [comment]
@elektronen do you mean 14.13.0?

**Comment by elektronen** [comment]
Hi. Yes, the newest release for Patreon subscribers. 🙂

**Comment by esabol** [comment]
I've learned to deal with it by setting a up a cron job which restarts UMS twice per day.

**Comment by ik666** [comment]
> https://stackoverflow.com/a/67436783 says:
> 
> > Another reason why this is happening is due to excessive garbage collection, when garbage collection was running for a longer time within two executions of housekeeping thread, trying to free up some memory(e.g exactly when an application thread was running a 'select' query). Since the GC was blocking all application threads including the housekeeping thread, as such my suspicion is that the clock "leapt" due to that.

Hi. If this is true, you can try another Gargabe collector. Add : "-XX:+UseShenandoahGC" to your VM start args.

**Comment by ik666** [comment]
> Just want to note this remains an issue in 14.3.0, and I am also on macOS High Sierra (10.13.6). When enough of these occur, the application becomes unresponsive, and I have to Force Quit, then relaunch.

Actually, this sounds more like a memory leak, or short of memory. Could you add "-Xmx4096m" to your VM start line.

**Comment by SubJunk** [comment]
Yeah can you let us know how much memory UMS is using when it is unresponsive?

**Comment by esabol** [comment]
> Yeah can you let us know how much memory UMS is using when it is unresponsive?

I'm seeing lots of "Thread starvation or clock leap detected (housekeeper delta=50s2ms)" in my logs right now, and it's only using 140-200 MB of RAM, according to the Memory Usage meter in the UMS window. If I quit and re-open UMS, the Memory Usage meter shows 50-80 MB. I'm currently on 14.12.1.

When it gets unresponsive, it's usually over 1 GB. But since I added a cron job to restart UMS twice per day, that hasn't happened in a long time.

My Java options are -Xmx2048M -Xss16M.

**Comment by SubJunk** [comment]
Is this still happening in v15? We changed some memory things

**Comment by esabol** [comment]
> Is this still happening in v15? We changed some memory things

Sorry, I haven't upgraded to V15 yet. I'll try to remember to come back to this and report my findings after I do.

**Comment by esabol** [comment]
I finally upgraded to UMS 15.2.0, and I'm still seeing `HikariPool-* - Thread starvation or clock leap detected (housekeeper delta=50s*ms)` messages in my log.

The log messages right before these `Thread starvation` messages start are **new with 15.2.0**:
```
08:30:40 ERROR Error initializing process: Cannot run program "ping": error=2, No such file or directory
08:30:40 WARN  Error measuring network throughput : Cannot invoke "java.util.List.iterator()" because "ls" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "ls" is null
	at net.pms.network.SpeedStats$MeasureSpeed.doPing(SpeedStats.java:213)
	at net.pms.network.SpeedStats$MeasureSpeed.doCall(SpeedStats.java:172)
	at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:131)
	at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:118)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Ping is available on my system, of course. Some kind of path issue?
```
> which ping
/sbin/ping
```
