### ISSUE TITLE
Realtime lock not releasing

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4009]
For some reason, it seems possible for `PMS.REALTIME_LOCK` to get stuck, and then it does the opposite of what it is designed to do - it prevents browsing instead of making browsing take priority. I currently have an instance of UMS running that won't browse via DLNA or web. There are no errors I can see, so I don't know how it got into this state. I have been looking at options in the docs https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/locks/ReentrantLock.html and maybe there are flags or different kinds of strategies that would prevent this.

One idea is to use `lockInterruptibly()` instead of `lock()` because we have already specified that the `getBrowsePage` method throws an `InterruptedException`. Does that change make sense? Does anyone have other ideas? @UniversalMediaServer/developers

**Comment by SubJunk** [comment]
That idea is in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4010

**Comment by SubJunk** [comment]
I eventually got this error on that instance too the next day, but it wasn't happening at the time. Just posting here for completeness

```
WARN  2023-07-27 16:14:49.806 [pool-7-thread-23] Unhandled exception while resolving VideoName: Task net.pms.util.APIUtils$$Lambda$689/0x00000008016a3000@1bd03050 rejected from java.util.concurrent.ThreadPoolExecutor@5207a8a9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 206]
DEBUG 2023-07-27 16:14:49.806 [pool-7-thread-23] 
java.util.concurrent.RejectedExecutionException: Task net.pms.util.APIUtils$$Lambda$689/0x00000008016a3000@1bd03050 rejected from java.util.concurrent.ThreadPoolExecutor@5207a8a9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 206]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at net.pms.util.APIUtils.backgroundLookupAndAddMetadata(APIUtils.java:550)
	at net.pms.dlna.DLNAResource.setMetadataFromFileName(DLNAResource.java:5144)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1528)
	at net.pms.dlna.RealFile.syncResolve(RealFile.java:444)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1323)
	at net.pms.dlna.RealFile.isValid(RealFile.java:106)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:553)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:514)
	at net.pms.dlna.virtual.MediaLibraryFolder.doRefreshChildren(MediaLibraryFolder.java:686)
	at net.pms.dlna.DLNAResource.doRefreshChildren(DLNAResource.java:1440)
	at net.pms.dlna.DLNAResource.refreshChildren(DLNAResource.java:1470)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1301)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1115)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1065)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.getMediaLibraryFolderChilds(PlayerApiServlet.java:582)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.getBrowsePage(PlayerApiServlet.java:451)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.doPost(PlayerApiServlet.java:219)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
	at net.pms.network.webguiserver.GuiHttpServlet.service(GuiHttpServlet.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
	at net.pms.network.httpserverservletcontainer.HttpHandlerServlet.handle(HttpHandlerServlet.java:37)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
I merged that fix candidate after testing that it still works, and I can't see any downsides to using that. However I'm not sure whether it fixes the problem because I don't have reproduction steps. I guess I will see if it happens again with this change

**Comment by ik666** [comment]
Hi Subjunk. I actually don't see the use of a lock here ... where is the concurrent access ?

**Comment by SubJunk** [comment]
The `REALTIME_LOCK` is used here to prioritize operations. So low-priority things wait for high-priority things
