### ISSUE TITLE
Column "MODIFIED" not found

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#4020]
Hi there,

the current main branch seems to have some database issues:

````
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "MODIFIED" not found [42122-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3518)
	at org.h2.jdbc.JdbcResultSet.getTimestamp(JdbcResultSet.java:524)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java)
	at net.pms.database.MediaTableFiles.getFiles(MediaTableFiles.java:1137)
	at net.pms.dlna.virtual.MediaLibraryFolder.doRefreshChildren(MediaLibraryFolder.java:273)
	at net.pms.dlna.virtual.MediaLibraryFolder.discoverChildren(MediaLibraryFolder.java:123)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1414)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1273)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1114)
	at net.pms.network.mediaserver.nettyserver.RequestV2.browseSearchHandler(RequestV2.java:1114)
	at net.pms.network.mediaserver.nettyserver.RequestV2.browseHandler(RequestV2.java:1038)
	at net.pms.network.mediaserver.nettyserver.RequestV2.answer(RequestV2.java:734)
	at net.pms.network.mediaserver.nettyserver.RequestHandlerV2.writeResponse(RequestHandlerV2.java:431)
	at net.pms.network.mediaserver.nettyserver.RequestHandlerV2.messageReceived(RequestHandlerV2.java:276)
	at net.pms.network.mediaserver.jupnp.transport.impl.NettyStreamServer$RequestUpstreamHandler.messageReceived(NettyStreamServer.java:200)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by SurfaceS** [comment]
can't reproduce this, so added a trace with the end sql query

**Comment by ik666** [comment]
After updating to latest commit (a8943c2af) I can't reproduce this either. Maybe this occurs only once after DB transition? Just for information: I updated my personal branch (displaying the above exception) from ff6534341c13281b1f972a14b6e1df7002534777 to a4396af26a652e822a28bb7eae2d3820adc05652 ...

**Comment by SubJunk** [comment]
I'll try to reproduce it on a pre-migration database

**Comment by SubJunk** [comment]
It didn't happen for me the first time but I kept my old db so I'll try it some more times
