### ISSUE TITLE
NullPointerException thrown on 13.7.0 when trying to play an avi video

### ISSUE THREAD

**Issue by freggeldoe** [UniversalMediaServer/UniversalMediaServer#4172]
when trying to play an AVi-File a headless UMS 13.7.0 on a debian 12 linux server just threws this `NullPointerException`:
```
Oct 26 17:13:15 machine java[583]: ERROR 17:13:15.415 [jupnp-netty-worker 2] error while generating answer
Oct 26 17:13:15 machine java[583]: java.lang.NullPointerException: Cannot invoke "net.pms.configuration.FormatConfiguration.getMatchedMIMEtype(String, String, String)" because the return value of "net.pms.configuration.RendererConfiguration.getFormatConfiguration()" is null
Oct 26 17:13:15 machine java[583]:         at net.pms.configuration.RendererConfiguration.isVideoStreamTypeSupportedInTranscodingContainer(RendererConfiguration.java:601)
Oct 26 17:13:15 machine java[583]:         at net.pms.encoders.FFMpegVideo.launchTranscode(FFMpegVideo.java:929)
Oct 26 17:13:15 machine java[583]:         at net.pms.dlna.DLNAResource.getInputStream(DLNAResource.java:3320)
Oct 26 17:13:15 machine java[583]:         at net.pms.dlna.DLNAResource.getInputStream(DLNAResource.java:3181)
Oct 26 17:13:15 machine java[583]:         at net.pms.network.mediaserver.nettyserver.RequestV2.answer(RequestV2.java:578)
Oct 26 17:13:15 machine java[583]:         at net.pms.network.mediaserver.nettyserver.RequestHandlerV2.writeResponse(RequestHandlerV2.java:424)
Oct 26 17:13:15 machine java[583]:         at net.pms.network.mediaserver.nettyserver.RequestHandlerV2.messageReceived(RequestHandlerV2.java:281)
Oct 26 17:13:15 machine java[583]:         at net.pms.network.mediaserver.jupnp.transport.impl.NettyStreamServer$RequestUpstreamHandler.messageReceived(NettyStreamServer.java:196)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
Oct 26 17:13:15 machine java[583]:         at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
Oct 26 17:13:15 machine java[583]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Oct 26 17:13:15 machine java[583]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Oct 26 17:13:15 machine java[583]:         at java.base/java.lang.Thread.run(Thread.java:833)
```

After switching back to 13.6.0 the same file plays without any problems.

**Comment by SubJunk** [comment]
@freggeldoe thanks for reporting this, working on it now

**Comment by SubJunk** [comment]
This will be fixed in the next version, would you like me to build the fixed version for you to download now?

**Comment by freggeldoe** [comment]
Sure, I could test that one.
Else I'm staying on 13.6.0 which also works for me.
