### ISSUE TITLE
Fix transcoded videos playback for Samsung 2016 UHD TVs

### ISSUE THREAD

**Issue by sad-spirit** [UniversalMediaServer/UniversalMediaServer#4272]
I own a UE55**KS7000** model and hit the same problem that is described in these forum posts
https://www.universalmediaserver.com/forum/viewtopic.php?t=12700
https://www.universalmediaserver.com/forum/viewtopic.php?t=13367

The TV did not play any transcoded videos showing an extremely unhelpful "Unknown error" message.

The logs showed a "Connection reset" exception:
```
DEBUG 2023-12-02 13:07:22.815 [jupnp-netty-worker 23] Caught exception: Connection reset
TRACE 2023-12-02 13:07:22.815 [jupnp-netty-worker 23] 
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

which immediately followed that server response

```
HTTP/1.1 206 Partial Content (non-chunked)

HEADER:
  Content-Type: video/vnd.dlna.mpeg-tts
  Content-Range: bytes 0-9223372034707292158/9223372034707292159
  ContentFeatures.DLNA.ORG: DLNA.ORG_PN=AVC_TS_NA_ISO;DLNA.ORG_OP=11;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000
  Accept-Ranges: bytes
  Connection: keep-alive
  Server: Linux-amd64-6.1.0-0.deb11.13-amd64, UPnP/1.0 DLNADOC/1.50, UMS/13.8.0
```

As I suspected that the TV was not amused by the above `Content-Range` header, I added

```
TranscodedVideoFileSize = 1000000
```
to a custom `.conf` file based on `Samsung-UHD.conf` and transcoded videos immediately started playing.

Also changing
```
SeekByTime = true
```
to 
```
SeekByTime = exclusive
```
actually allowed seeking.

I can create a PR for these changes, what should be the correct approach:
 * Just fix `Samsung-UHD.conf`
or
 * Create a new higher-priority `.conf` with these changes that applies only to models of 2016 and before?

Another question is whether it is reasonable to use an Exabyte-sized `Content-Range` header in the first place?

**Comment by sad-spirit** [comment]
A followup:
```
ChunkedTransfer = true
```
also helps.

I think using chunked transfer encoding is a better way according to HTTP spec: it is specifically designed for content of unknown length.

**Comment by SubJunk** [comment]
@sad-spirit a PR would be great, thank you.
I can see that the `TranscodedVideoFileSize` hack is already in a lot of the Samsung configs. Do you need both `ChunkedTransfer` and `TranscodedVideoFileSize`, or just one of them?

**Comment by SubJunk** [comment]
@sad-spirit I agree with you, you can just change it in that UHD file

**Comment by SubJunk** [comment]
@sad-spirit thank you for the PR
