### ISSUE TITLE
VlcVersion is not set in Linux

### ISSUE THREAD

**Issue by mfulgo** [UniversalMediaServer/UniversalMediaServer#433]
Running in Ubuntu. It seems the SystemUtils doesn't set the vlcVersion field, so trying to transcode with VLC results in...
```
java.lang.NullPointerException: Version string can not be null
	at net.pms.util.Version.<init>(Version.java:11) ~[ums.jar:5.0.0-b1]
	at net.pms.encoders.VLCVideo.launchTranscode(VLCVideo.java:465) ~[ums.jar:5.0.0-b1]
	at net.pms.dlna.DLNAResource.getInputStream(DLNAResource.java:2532) ~[ums.jar:5.0.0-b1]
	at net.pms.network.RequestV2.answer(RequestV2.java:367) ~[ums.jar:5.0.0-b1]
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:296) ~[ums.jar:5.0.0-b1]
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:254) ~[ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.0.0-b1]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.0.0-b1]
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [ums.jar:5.0.0-b1]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [ums.jar:5.0.0-b1]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [ums.jar:5.0.0-b1]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [ums.jar:5.0.0-b1]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [ums.jar:5.0.0-b1]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [ums.jar:5.0.0-b1]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [ums.jar:5.0.0-b1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
```

It would be better if UMS didn't allow you to enable the VLC transcoder if it's unable to find the version... Though, it appears that there's no logic to ever set it in Linux.

**Comment by Sami32** [comment]
@mfulgo @SubJunk Did the latest UMS version fixed this issue ? Need Linux to test it though...

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/Linux-install-instructions
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/436

@mfulgo Feel free to re-open it if need.
