### ISSUE TITLE
ArrayIndexOutOfBoundsException while Transcoding/Streaming

### ISSUE THREAD

**Issue by mfulgo** [UniversalMediaServer/UniversalMediaServer#434]
I haven't had a chance to debug it...

```
DEBUG 17:58:10.151 [New I/O worker #1] Caught exception
java.lang.ArrayIndexOutOfBoundsException: null
    at java.lang.System.arraycopy(Native Method) ~[na:1.7.0_65]
    at net.pms.io.BufferedOutputFileImpl.read(BufferedOutputFileImpl.java:721) ~[ums.jar:5.0.0-b1]
    at net.pms.io.WaitBufferedInputStream.read(WaitBufferedInputStream.java:54) ~[ums.jar:5.0.0-b1]
    at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[na:1.7.0_65]
    at java.io.PushbackInputStream.read(PushbackInputStream.java:186) ~[na:1.7.0_65]
    at org.jboss.netty.handler.stream.ChunkedStream.nextChunk(ChunkedStream.java:112) ~[ums.jar:5.0.0-b1]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:217) [ums.jar:5.0.0-b1]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:121) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.Channels.write(Channels.java:704) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.Channels.write(Channels.java:671) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248) [ums.jar:5.0.0-b1]
    at net.pms.network.RequestV2.answer(RequestV2.java:914) [ums.jar:5.0.0-b1]
    at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:296) [ums.jar:5.0.0-b1]
    at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:254) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.0.0-b1]
    at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.0.0-b1]
    at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [ums.jar:5.0.0-b1]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [ums.jar:5.0.0-b1]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [ums.jar:5.0.0-b1]
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [ums.jar:5.0.0-b1]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [ums.jar:5.0.0-b1]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [ums.jar:5.0.0-b1]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [ums.jar:5.0.0-b1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
```

**Comment by Sami32** [comment]
@mfulgo @SubJunk Did the latest UMS version fixed this issue ?
I don't get this error while streaming on WinXP 32 bit with UMS 6.4.0.

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/253 ?

**Comment by polygirl** [comment]
@mfulgo It's been some time since you reported this and we presume this hasn't caused an issue for you so we're closing.  Please feel free to reopen with full TRACE logs if needed.
