### ISSUE TITLE
Can't start web settings

### ISSUE THREAD

**Issue by GFoley83** [UniversalMediaServer/UniversalMediaServer#4542]
Version 13.8.1 on Windows.
Tried changing the port but makes no different. Old settings and web player work fine. Reinstall make no difference.

Error from the logs when I click "Settings" from the notification icon:

```
15:37:15 INFO  Web player is available at: http://192.168.1.7:9002
15:37:16 INFO  Launching the graphical interface on a browser
15:37:16 INFO  Universal Media Server is now available for renderers to find
15:37:16 INFO  Exception in thread "Web GUI browser" java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
15:37:16 INFO  	at java.base/java.net.URI$Parser.parse(Unknown Source)
15:37:16 INFO  	at java.base/java.net.URI.<init>(Unknown Source)
15:37:16 INFO  	at net.pms.platform.PlatformUtils.browseURI(PlatformUtils.java:154)
15:37:16 INFO  	at net.pms.PMS$2.run(PMS.java:650)
15:37:16 INFO  IP Filter: Access allowed to READYSHARE
15:37:22 INFO  IP Filter: Access allowed to 192.168.1.90
15:37:22 INFO  Checking IP: 192.168.1.90 for LG WebOS TV
15:37:22 INFO  Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
15:37:22 INFO  	at java.base/java.net.URI$Parser.parse(Unknown Source)
15:37:22 INFO  	at java.base/java.net.URI.<init>(Unknown Source)
15:37:22 INFO  	at net.pms.platform.PlatformUtils.browseURI(PlatformUtils.java:154)
15:37:22 INFO  	at net.pms.platform.PlatformUtils.lambda$addSystemTray$3(PlatformUtils.java:203)
15:37:22 INFO  	at java.desktop/java.awt.MenuItem.processActionEvent(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.MenuItem.processEvent(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.MenuComponent.dispatchEvent(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
15:37:22 INFO  	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
15:37:22 INFO  	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
15:37:22 INFO  	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
15:37:22 INFO  	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
15:37:22 INFO  	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
15:37:22 INFO  	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by SubJunk** [comment]
@GFoley83 thanks for reporting this problem. We need the full logs, steps described at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new
