### ISSUE TITLE
v14.1 : reading cover art throws exception

### ISSUE THREAD

**Issue by ik666** [UniversalMediaServer/UniversalMediaServer#4659]
There seems to be an issue introduced with v14.1 reading coverart data from audio files. Nighter MP3 nor FLAC or other formats work. 

MediaInfo reads (at least some) garbage. For reference I added a file with cover art, that seems to work with v14 but not with v14.1

````
INFO  16:37:27.642 [MediaScanner File Parser] Exception in thread "MediaScanner File Parser" java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 35108
INFO  16:37:27.643 [MediaScanner File Parser] 	at java.base/java.util.Base64$Decoder.decode0(Base64.java:875)
INFO  16:37:27.644 [MediaScanner File Parser] 	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.parsers.MediaInfoParser.parse(MediaInfoParser.java:192)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.parsers.Parser.parse(Parser.java:79)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.store.MediaInfoStore.getMediaInfo(MediaInfoStore.java:150)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.store.item.RealFile.resolve(RealFile.java:224)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.store.StoreItem.syncResolve(StoreItem.java:1473)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.store.item.RealFile.syncResolve(RealFile.java:303)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.store.MediaScanner.parseFileEntry(MediaScanner.java:431)
INFO  16:37:27.644 [MediaScanner File Parser] 	at net.pms.store.MediaScanner.lambda$3(MediaScanner.java:384)
INFO  16:37:27.644 [MediaScanner File Parser] 	at java.base/java.lang.Thread.run(Thread.java:833)
```
[cover.mp3.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/15323199/cover.mp3.zip)

**Comment by SurfaceS** [comment]
@ik666 should be fixed in v14.1 now

**Comment by ik666** [comment]
@SurfaceS  Not quite. I still got the error. There were 2 cover arts in the file. Both are base64 encoded, split by a " / ". I've opened a new PR #4661 that did the fix by decoding only the first cover art.

Strange thing: I have no clue why this happens only in 14.1 ?!

**Comment by SurfaceS** [comment]
v14.1 switched from external dep `org.apache.commons.codec.binary.Base64` to `java.util.Base64`

**Comment by ik666** [comment]
ok, that makes sense
