### ISSUE TITLE
SMB network share unable to be added in WebUI

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#4754]
There is a  user on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?t=15995) that is unable to add their SMB network shares in the WebUI and when manually editing the SHARED.conf only one shows up.

I see a few errors about `A plugin has attempted to add a null child to "root"` which may be a symptom but also saw 

```
Recursion error: java.nio.file.FileSystemException: \\Server2016\media\$RECYCLE.BIN: The specified network name is no longer available
java.nio.file.FileSystemException: \\Server2016\media\$RECYCLE.BIN: The specified network name is no longer available
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(Unknown Source)
	at java.base/java.nio.file.Files.newDirectoryStream(Unknown Source)
	at java.base/java.nio.file.FileTreeWalker.visit(Unknown Source)
	at java.base/java.nio.file.FileTreeWalker.next(Unknown Source)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at net.pms.util.FileWatcher.addRecursive(FileWatcher.java:136)
	at net.pms.util.FileWatcher.add(FileWatcher.java:89)
	at net.pms.store.MediaScanner.setMediaFileWatchers(MediaScanner.java:558)
	at net.pms.store.MediaScanner.updateSharedContent(MediaScanner.java:75)
	at net.pms.configuration.sharedcontent.SharedContentConfiguration.addListener(SharedContentConfiguration.java:147)
	at net.pms.store.MediaScanner.init(MediaScanner.java:80)
	at net.pms.PMS.init(PMS.java:280)
	at net.pms.PMS.createInstance(PMS.java:1033)
	at net.pms.PMS.main(PMS.java:984)
```

which may be the cause.

Is it normally possible to add network shares in the WebUI? or is it breaking because of this error?

**Comment by SubJunk** [comment]
@Mik-S-UMS That particular recycle bin bug was fixed in 14.0.1 so the user might find that updating to the latest release fixes their problem

**Comment by SurfaceS** [comment]
this may has been fixed.

**Comment by SubJunk** [comment]
Closing as fixed and stale
