### ISSUE TITLE
Web video support broken

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4807]
It looks like support for all web videos has been broken for a long time, since v11. I thought it was just YouTube but it is also broken for e.g. https://feeds.feedburner.com/tedtalks_video
If I run UMS v10 it works, but all releases since v11 are broken.

I think it never worked since the HLS refactoring https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2880

It seems the video is not parsed before the HLS helper receives it, so this error happens:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because "duration" is null
	at net.pms.encoders.HlsHelper.getHLSm3u8ForRendition(HlsHelper.java:290)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.sendMedia(PlayerApiServlet.java:1144)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.doGet(PlayerApiServlet.java:117)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at net.pms.network.webguiserver.GuiHttpServlet.service(GuiHttpServlet.java:61)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:858)
	at org.eclipse.jetty.server.Server.handle(Server.java:181)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
@SurfaceS I can look into it, but you will probably be faster because you wrote the HLS code, can you try to fix it?
