### ISSUE TITLE
Resolve YouTube URLs with Handles into channel feeds

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4827]
For YouTube support, we currently transform channel URLs into RSS feeds for convenience.

So if a user inputs e.g. https://www.youtube.com/channel/UCsXVk37bltHxD1rDPwtNM8Q we automatically replace it with https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q

But since we introduced that feature, YouTube have a "Handle" URL syntax which makes the URL the user sees for a channel e.g. https://www.youtube.com/@kurzgesagt

Our code should accept and transform that syntax too.

Edit: Actually the above is not correct, we only transform it temporarily to fetch the title of the feed. So we should fully transform it

**Comment by Mik-S-UMS** [comment]
I think this is broken now as someone [reported](https://www.universalmediaserver.com/forum/viewtopic.php?t=16369) they are unable to add a feed

Its either a bug or YT changed something as adding with the handle brings up "feed name not found" and in the logs I see
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.attr(String)" because the return value of "org.jsoup.select.Elements.first()" is null
	at net.pms.store.container.Feed.getFeedUrlFromWebpage(Feed.java:290)
	at net.pms.store.container.Feed.getYouTubeChannelFeedUrl(Feed.java:310)
	at net.pms.store.container.Feed.getFeedUrl(Feed.java:329)
	at net.pms.store.container.Feed.<init>(Feed.java:62)
	at net.pms.store.container.VideosFeed.<init>(VideosFeed.java:26)
	at net.pms.store.MediaStore.setExternalContent(MediaStore.java:379)
	at net.pms.store.MediaStore.setSharedContents(MediaStore.java:280)
	at net.pms.store.MediaStore.discoverChildren(MediaStore.java:220)
	at net.pms.store.MediaStore.reset(MediaStore.java:407)
	at net.pms.renderers.Renderer.resetMediaStore(Renderer.java:275)
	at net.pms.renderers.ConnectedRenderers.resetAllRenderers(ConnectedRenderers.java:354)
	at net.pms.PMS.resetRenderersMediaStore(PMS.java:682)
	at net.pms.configuration.sharedcontent.SharedContentConfiguration.updateSharedContent(SharedContentConfiguration.java:179)
	at net.pms.configuration.sharedcontent.SharedContentConfiguration.setFromJsonArray(SharedContentConfiguration.java:208)
	at net.pms.network.webguiserver.servlets.SharedContentApiServlet.doPost(SharedContentApiServlet.java:112)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at net.pms.network.webguiserver.GuiHttpServlet.service(GuiHttpServlet.java:61)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1619)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1552)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:819)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:469)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server.Server.handle(Server.java:182)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:418)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:443)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
```
Using the xml link does still work.

I also found that even though UMS detects an error and says the configuration will not be saved it does so anyway.

This is a problem when UMS is restarted as it prevents anything showing on the device or web player.
This may be the cause when people have reported that UMS is empty.

**Comment by SubJunk** [comment]
Did you say on the forum that you are able to reproduce this problem?

**Comment by SubJunk** [comment]
Can you try it on the `4827-youtube` branch? It won't fix it, but will give more logging to help

**Comment by Mik-S-UMS** [comment]
I added the feeds for `https://www.youtube.com/@kurzgesagt` and `https://www.youtube.com/@LinusTechTips` so you can check to see if there is any difference from another channel.

[ums_dbg_2025-03-15-12-55.zip](https://github.com/user-attachments/files/19261813/ums_dbg_2025-03-15-12-55.zip)

**Comment by SubJunk** [comment]
Ahh interesting, it's showing a cookie consent page instead of the real YouTube channel page. It has redirected to consent.youtube.com

I guess we need to handle it in our UI somehow, like display an article about how to provide consent to YouTube.

**Comment by SubJunk** [comment]
This seems to happen to a lot of integrations, this thread might be useful https://github.com/yt-dlp/yt-dlp/issues/1303

**Comment by Mik-S-UMS** [comment]
That makes sense. I think the cookie consent is a requirement for the EU so this is why it will work fine in other regions.

I remember having similar problems trying to use Youtube-dl to rip MP3s of the chapters of a video. 
It was failing to start the download giving authorisation errors.
I can't remember how I got it to work eventually but remember seeing many threads on Reddit how to import cookies from the web browser for it to use.

I don't know if that consent page has a reject all option as that would be best to use if UMS could automatically select it, or maybe this is a requirement for it to work.
It possibly could be automatically imported from the browser but as this could also include things like login and session information this will have to be the bare minimum needed and well protected.

Maybe UMS could open isolated browser window for the user to confirm cookies. 
I have container tabs in Firefox that keeps the sessions isolated if I want to open a site and not login or use another account while still in my main one.
A private window could work too if you are able to get the cookies from there before it is closed otherwise they won't be saved.

**Comment by SubJunk** [comment]
Yeah these are all good thoughts. I wonder if it would work to simply launch the default browser with that address, or if it needs to be a browser in UMS which would be harder
