### ISSUE TITLE
AsyncContext completed and/or Request lifecycle recycled

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4848]
@SurfaceS Since switching the default to Jetty there are new errors appearing in the logs:

```
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] Adding "video.mkv" to transcode folder for engine: "null"
TRACE 2024-07-24 16:38:57.598 [jupnp-contentdirectory-service] Send event "SystemUpdateID" update from 1829860 to 1829861
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] resource with id '1181194' recreacted succefully
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] Initial discovering children for container: Knives Out (2019)
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] Creating DIDL result
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224331-1] discover 1181194 refresh forced: true
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] DIDL result created
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] Returning browse result
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224331-1] Creating DIDL result
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224331-1] DIDL result created
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224331-1] Returning browse result
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] Preparing HTTP response message: (OutgoingActionResponseMessage) 200 OK
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] Sending HTTP response status: 200
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224331-1] Preparing HTTP response message: (OutgoingActionResponseMessage) 200 OK
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224331-1] Sending HTTP response status: 200
TRACE 2024-07-24 16:38:57.598 [jupnp-sync-protocol 224247-1] Error calling servlet container's AsyncContext#complete() method
java.lang.IllegalStateException: AsyncContext completed and/or Request lifecycle recycled
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.state(AsyncContextState.java:41)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.complete(AsyncContextState.java:61)
	at net.pms.network.mediaserver.jupnp.transport.async.JakartaAsyncServletUpnpStream.complete(JakartaAsyncServletUpnpStream.java:79)
	at net.pms.network.mediaserver.jupnp.transport.impl.JakartaServletUpnpStream.run(JakartaServletUpnpStream.java:97)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SurfaceS** [comment]
@SubJunk mail me the full log pls.

**Comment by SubJunk** [comment]
Same as the other one, the logs are so big. The TV is really spamming UMS crawling all the folders

**Comment by SubJunk** [comment]
I could upload the huge logs, or provide the context here, let me know

**Comment by SubJunk** [comment]
@SurfaceS emailed a link to the 11GB logs 😆

**Comment by SurfaceS** [comment]
```
TRACE 2024-08-11 17:54:53.928 [jupnp-stream-server-162396] HttpServlet HttpServlet.service(): id: 10380, request URI: /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action
TRACE 2024-08-11 17:54:53.928 [jupnp-stream-server-162396] Handling Servlet request asynchronously: ServletApiRequest@73fd2235{ServletContextRequest@38c22057{POST@4cb6d78e http://192.168.1.9:5001/dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action HTTP/1.1}}
TRACE 2024-08-11 17:54:53.928 [jupnp-sync-protocol 146566-1] Processing HTTP request: POST /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action 
TRACE 2024-08-11 17:54:53.928 [jupnp-sync-protocol 146566-1] Reading request body bytes: 681
TRACE 2024-08-11 17:54:53.928 [jupnp-sync-protocol 146566-1] Request contains textual entity body, converting then setting string on message
TRACE 2024-08-11 17:54:53.928 [jupnp-sync-protocol 146566-1] Processing new request message: (StreamRequestMessage) POST /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action
TRACE 2024-08-11 17:54:53.928 [jupnp-sync-protocol 146566-1] Received a request from 192.168.1.7:
============================= UPNP HTTP SERVER REQUEST BEGIN ================================
POST /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action HTTP/1.1

HEADER:
  SOAPAction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
  DLNADeviceName.lge.com: %5bLG%5d%20webOS%20TV%20OLED65C24LA
  User-Agent: Linux/5.4.96-307 UPnP/1.0 LGE WebOS TV LGE_DLNA_SDK/1.6.0/13.30.80 DLNADOC/1.50
  Host: 192.168.1.9:5001
  Content-Length: 681
  Content-Type: text/xml; charset="utf-8"

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
            <ObjectID>1179006</ObjectID>
            <BrowseFlag>BrowseDirectChildren</BrowseFlag>
            <Filter>res@resolution,res@nrAudioChannels,res@sampleFrequency,res@bitrate,dc:creator,res@dlna:cleartextSize,dc:date,upnp:genre,res,res@duration,res@size,upnp:albumArtURI,upnp:originalTrackNumber,upnp:album,upnp:artist,upnp:author</Filter>
            <StartingIndex>0</StartingIndex>
            <RequestedCount>30</RequestedCount>
            <SortCriteria/>
        </u:Browse>
    </s:Body>
</s:Envelope>

============================= UPNP HTTP SERVER REQUEST END ==================================
TRACE 2024-08-11 17:54:53.928 [jupnp-sync-protocol 146566-1] Matched media renderer "[LG] webOS TV OLED65C24LA" based on address 192.168.1.7
DEBUG 2024-08-11 17:54:53.929 [jupnp-sync-protocol 146566-1] Recognized media renderer "[LG] webOS TV OLED65C24LA"
TRACE 2024-08-11 17:54:53.929 [jupnp-sync-protocol 146566-1] try recreating resource with id '1179006'
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Unwatched" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Watched" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Filter by Progress" with class "LocalizedStoreContainer"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Actors" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Country" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Director" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Genres" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Rated" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Rating" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Released" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] filteredExpectedOutputsWithPrependedTexts: [1, 0]
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] genresSqls: [SELECT DISTINCT VIDEO_METADATA_GENRES.GENRE FROM FILES LEFT JOIN VIDEO_METADATA_GENRES ON FILES.ID = VIDEO_METADATA_GENRES.FILEID LEFT JOIN FILES_STATUS ON FILES.FILENAME = FILES_STATUS.FILENAME LEFT JOIN VIDEO_METADATA ON FILES.ID = VIDEO_METADATA.FILEID WHERE FILES.FORMAT_TYPE = 4 ORDER BY VIDEO_METADATA_GENRES.GENRE ASC, SELECT * FROM FILES LEFT JOIN VIDEO_METADATA_GENRES ON FILES.ID = VIDEO_METADATA_GENRES.FILEID LEFT JOIN FILES_STATUS ON FILES.FILENAME = FILES_STATUS.FILENAME LEFT JOIN VIDEO_METADATA ON FILES.ID = VIDEO_METADATA.FILEID WHERE VIDEO_METADATA_GENRES.GENRE = '${0}' AND FILES.FORMAT_TYPE = 4 ORDER BY FILES.FILENAME ASC]
TRACE 2024-08-11 17:54:54.031 [jupnp-sync-protocol 146566-1] Adding new child "Filter by Information" with class "LocalizedStoreContainer"
TRACE 2024-08-11 17:54:54.032 [jupnp-sync-protocol 146566-1] Adding new child "Recommendations" with class "MediaLibraryFolder"
TRACE 2024-08-11 17:54:54.125 [jupnp-sync-protocol 146566-1] Matched format MPG to "F:\Klaus\Unsorted\Torrents\Movies\Vixen.The.Movie.2017.COMPLETE.BLURAY-WaLMaRT\BDMV\STREAM\00257.m2ts"
TRACE 2024-08-11 17:54:54.245 [NetworkConfiguration Watcher] Checking network configuration changes
TRACE 2024-08-11 17:55:53.985 [jupnp-stream-server-68816] HttpServlet HttpServlet.service(): id: 10381, request URI: /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action
TRACE 2024-08-11 17:55:53.936 [jupnp-stream-server-169881] Stream Async Timed out, id: 10380, uri: /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action, duration: 60009 ms

```

Stream Async Timed out, so it is a normal error from AsyncContext#complete().

Problem is here :

```
TRACE 2024-08-11 17:54:54.245 [NetworkConfiguration Watcher] Checking network configuration changes
TRACE 2024-08-11 17:55:53.985 [jupnp-stream-server-68816] HttpServlet HttpServlet.service(): id: 10381, request URI: /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action
```

"Checking network configuration changes" take more than 60 seconds !?

**Comment by SurfaceS** [comment]
Strange thing is that `NetworkConfiguration Watcher` run in its own thread.
So it should not impact other threads.

It is like if Java core is stuck for 60 sec here.

**Comment by SurfaceS** [comment]
#4939

**Comment by SurfaceS** [comment]
`jupnp-sync-protocol 146566-1` is running a `recreating resource with id '1179006'` when this happens.

**Comment by SurfaceS** [comment]
Stream Async Timed out was solved (zipping log was taking long time).
