### ISSUE TITLE
Exception in result creation "null"

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#4849]
Another error since using Jetty:

```
TRACE 2024-07-24 16:38:57.186 [jupnp-sync-protocol 224247-1] Adding "video.avi" to transcode folder for engine: "null"
ERROR 2024-07-24 16:38:57.187 [jupnp-sync-protocol 224332-1] Exception in result creation "null"
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at net.pms.store.container.MediaLibraryFolder.doRefreshChildren(MediaLibraryFolder.java:381)
	at net.pms.store.container.MediaLibraryFolder.discoverChildren(MediaLibraryFolder.java:83)
	at net.pms.store.MediaStore.recreateResource(MediaStore.java:523)
	at net.pms.store.MediaStore.getWeakResource(MediaStore.java:504)
	at net.pms.store.MediaStore.getResource(MediaStore.java:475)
	at net.pms.store.MediaStore.getResources(MediaStore.java:637)
	at net.pms.network.mediaserver.jupnp.support.contentdirectory.UmsContentDirectoryService.browse(UmsContentDirectoryService.java:642)
	at net.pms.network.mediaserver.jupnp.support.contentdirectory.UmsContentDirectoryService.browse(UmsContentDirectoryService.java:287)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jupnp.util.Reflections.invoke(Reflections.java:42)
	at org.jupnp.model.action.MethodActionExecutor.execute(MethodActionExecutor.java:94)
	at org.jupnp.model.action.AbstractActionExecutor$1.execute(AbstractActionExecutor.java:74)
	at org.jupnp.model.DefaultServiceManager.execute(DefaultServiceManager.java:130)
	at org.jupnp.model.action.AbstractActionExecutor.execute(AbstractActionExecutor.java:71)
	at org.jupnp.protocol.sync.ReceivingAction.executeSync(ReceivingAction.java:104)
	at org.jupnp.protocol.ReceivingSync.execute(ReceivingSync.java:65)
	at org.jupnp.protocol.ReceivingAsync.run(ReceivingAsync.java:71)
	at org.jupnp.transport.spi.UpnpStream.process(UpnpStream.java:83)
	at net.pms.network.mediaserver.jupnp.transport.impl.JakartaServletUpnpStream.run(JakartaServletUpnpStream.java:70)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SurfaceS** [comment]
@SubJunk same for this one.

**Comment by SubJunk** [comment]
For some reason my logs are huge, the folder of the latest logs is 19.4GB 😆 and each log file is around 300MB or more

The logs with the surrounding info are:

```
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Getting engine for resource "video.mp4"
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Returning compatible engine "FFmpeg Video"
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Format "mp4" failed to match supported line f:3gp|3g2   v:h264|mp4                          a:aac-lc                                                                                         m:video/3gpp
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Format "mp4" failed to match supported line f:avi       v:divx|h264|mjpeg|mp4               a:aac-lc|ac3|he-aac|mp3|mpa                  gmc:0                                               m:video/avi
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Format "mp4" failed to match supported line f:mkv       v:av1|h264|h265|mp4|mpeg2|vp8|vp9   a:aac-lc|he-aac|ac3|eac3|lpcm|mp3|mpa|opus           si:ASS|SUBRIP   hdr:hdr10|hlg               m:video/x-matroska
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Format "mp4" failed to match supported line f:mov       v:av1|h264|h265|mp4                 a:aac-lc|ac3|ac4|eac3|he-aac|mp3                                                                 m:video/quicktime
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Matched support line f:mp4|m4v   v:av1|h264|h265|mp4                 a:aac-lc|ac3|ac4|eac3|he-aac|mp3                     si:TX3G         hdr:dolbyvision|hdr10|hlg   m:video/mp4
DEBUG 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Final verdict: "video.mp4" will be streamed
TRACE 2024-07-24 16:35:45.038 [jupnp-sync-protocol 224091-1] Adding "video.mp4" to transcode folder for engine: "null"
ERROR 2024-07-24 16:35:45.065 [jupnp-sync-protocol 224091-1] Exception in result creation "null"
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at net.pms.store.container.MediaLibraryFolder.doRefreshChildren(MediaLibraryFolder.java:389)
	at net.pms.store.container.MediaLibraryFolder.discoverChildren(MediaLibraryFolder.java:83)
	at net.pms.store.MediaStore.recreateResource(MediaStore.java:523)
	at net.pms.store.MediaStore.getWeakResource(MediaStore.java:504)
	at net.pms.store.MediaStore.getResource(MediaStore.java:475)
	at net.pms.store.MediaStore.getResources(MediaStore.java:637)
	at net.pms.network.mediaserver.jupnp.support.contentdirectory.UmsContentDirectoryService.browse(UmsContentDirectoryService.java:642)
	at net.pms.network.mediaserver.jupnp.support.contentdirectory.UmsContentDirectoryService.browse(UmsContentDirectoryService.java:287)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jupnp.util.Reflections.invoke(Reflections.java:42)
	at org.jupnp.model.action.MethodActionExecutor.execute(MethodActionExecutor.java:94)
	at org.jupnp.model.action.AbstractActionExecutor$1.execute(AbstractActionExecutor.java:74)
	at org.jupnp.model.DefaultServiceManager.execute(DefaultServiceManager.java:130)
	at org.jupnp.model.action.AbstractActionExecutor.execute(AbstractActionExecutor.java:71)
	at org.jupnp.protocol.sync.ReceivingAction.executeSync(ReceivingAction.java:104)
	at org.jupnp.protocol.ReceivingSync.execute(ReceivingSync.java:65)
	at org.jupnp.protocol.ReceivingAsync.run(ReceivingAsync.java:71)
	at org.jupnp.transport.spi.UpnpStream.process(UpnpStream.java:83)
	at net.pms.network.mediaserver.jupnp.transport.impl.JakartaServletUpnpStream.run(JakartaServletUpnpStream.java:70)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
TRACE 2024-07-24 16:35:45.065 [jupnp-sync-protocol 224091-1] Preparing HTTP response message: (OutgoingActionResponseMessage) 500 Internal Server Error
TRACE 2024-07-24 16:35:45.065 [jupnp-sync-protocol 224091-1] Sending HTTP response status: 500
TRACE 2024-07-24 16:35:45.066 [jupnp-sync-protocol 224091-1] Response sent to 192.168.1.7:
============================= UPNP HTTP SERVER RESPONSE BEGIN ===============================
HTTP/1.1 500

HEADER:
  Server: Windows_11-amd64-10.0, UPnP/1.0 DLNADOC/1.50, UMS/14.2.1-SNAPSHOT
  Date: Wed, 24 Jul 2024 04:35:45 GMT
  Ext: 
  Content-type: text/xml;charset="utf-8"
  Content-Length: 537

CONTENT:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <s:Fault>
            <faultcode>s:Client</faultcode>
            <faultstring>UPnPError</faultstring>
            <detail>
                <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
                    <errorCode>501</errorCode>
                    <errorDescription>Current state of service prevents invoking that action. java.util.ConcurrentModificationException.</errorDescription>
                </UPnPError>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>

============================= UPNP HTTP SERVER RESPONSE END =================================
TRACE 2024-07-24 16:35:45.066 [jupnp-sync-protocol 224091-1] Stream Async Complete, id: 12593, uri: /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/svc/upnp-org/ContentDirectory/action, duration: 131902 ms
TRACE 2024-07-24 16:35:45.066 [jupnp-sync-protocol 224091-1] Completed asynchronous processing of HTTP request: org.eclipse.jetty.ee10.servlet.ServletApiRequest@1a6818a8
```

Is that enough? I could find a way to upload the logs if you need the full ones

**Comment by SubJunk** [comment]
I still have the logs I can upload

**Comment by SurfaceS** [comment]
@SubJunk yes, it can point me on the good direction.

**Comment by SurfaceS** [comment]
I don't have this error in the logs.

**Comment by SubJunk** [comment]
Emailed a different set

**Comment by SurfaceS** [comment]
@SubJunk 
Is this still bugged ?

**Comment by SubJunk** [comment]
@SurfaceS I haven't seen this happen again, it might be rare or fixed. Will close for now
