### ISSUE TITLE
Unknown source error

### ISSUE THREAD

**Issue by mykeehu** [UniversalMediaServer/UniversalMediaServer#4919]
I wanted to start an AVI movie, but I found the following error in the log:

`19:45:54 WARN  Job failed
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -2034644243 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at net.pms.io.BufferedOutputFileImpl.read(BufferedOutputFileImpl.java:722)
	at net.pms.io.WaitBufferedInputStream.read(WaitBufferedInputStream.java:52)
	at net.pms.io.WaitBufferedInputStream.read(WaitBufferedInputStream.java:62)
	at net.pms.network.HttpServletHelper.copyStream(HttpServletHelper.java:252)
	at net.pms.network.HttpServletHelper.lambda$copyStreamAsync$0(HttpServletHelper.java:283)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1299)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1292)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.lambda$start$0(AsyncContextState.java:138)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1305)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1322)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
`

Here is AVI's MediaInfo:
```
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Format settings                          : BitmapInfoHeader / WaveFormatEx
File size                                : 54.3 MiB
Duration                                 : 6 min 27 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 177 kb/s
Frame rate                               : 25.000 FPS
Writing application                      : Nandub v1.0rc2
Writing library                          : Nandub build 1853/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Advanced Simple@L5
Format settings                          : BVOP2 / QPel
Format settings, BVOP                    : 2
Format settings, QPel                    : Yes
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : XVID
Codec ID/Hint                            : XviD
Duration                                 : 6 min 27 s
Bit rate                                 : 1 027 kb/s
Width                                    : 512 pixels
Height                                   : 384 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.209
Stream size                              : 47.4 MiB (87%)
Writing library                          : XviD 1.1.0 (2005-11-22)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 6 min 27 s
Bit rate mode                            : Variable
Bit rate                                 : 136 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 6.29 MiB (12%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 24  ms (0.60 video frame)
Interleave, preload duration             : 451  ms
```

I use UMS 14.3.0 version. Java error? Log attached. 
[ums_dbg_2024-08-23-20-29.zip](https://github.com/user-attachments/files/16732494/ums_dbg_2024-08-23-20-29.zip)

There is no such bug under version 13.10.1, so I reinstalled this older version.

**Comment by SpitFire-666** [comment]
Getting a related error on v14.5.1

```
DEBUG 2024-10-21 13:12:32.965 [ffmpeg.exe-192] Process ID (C:\Program Files (x86)\Universal Media Server\bin\ffmpeg.exe): 20332
DEBUG 2024-10-21 13:12:33.014 [Thread-1321] Result of \\.\pipe\ffmpegvideo_132779_1729476752646: true
DEBUG 2024-10-21 13:12:33.156 [jupnp-stream-server-129347] Requesting time seek: 1609.0 seconds
DEBUG 2024-10-21 13:12:33.156 [jupnp-stream-server-129347] Duplicate time seek request: 1609.0 seconds, ignoring
DEBUG 2024-10-21 13:12:33.164 [jupnp-stream-server-283687] Requesting time seek: 1609.0 seconds
DEBUG 2024-10-21 13:12:33.164 [jupnp-stream-server-283687] Duplicate time seek request: 1609.0 seconds, ignoring
DEBUG 2024-10-21 13:12:33.210 [jupnp-stream-server-283692] Sending stream with premature end: 65536 bytes. Reason: Connection reset by peer
DEBUG 2024-10-21 13:12:33.214 [jupnp-stream-server-132977] Requesting time seek: 1609.0 seconds
DEBUG 2024-10-21 13:12:33.214 [jupnp-stream-server-132977] Duplicate time seek request: 1609.0 seconds, ignoring
DEBUG 2024-10-21 13:12:33.223 [jupnp-stream-server-283963] Sending stream with premature end: 65536 bytes. Reason: Connection reset by peer
DEBUG 2024-10-21 13:12:33.235 [jupnp-stream-server-143922] Requesting time seek: 1609.0 seconds
DEBUG 2024-10-21 13:12:33.235 [jupnp-stream-server-143922] Duplicate time seek request: 1609.0 seconds, ignoring
DEBUG 2024-10-21 13:12:33.235 [jupnp-stream-server-143922] Setting InputStream new position to: 9,223,372,034,707,292,031
WARN  2024-10-21 13:12:34.238 [jupnp-stream-server-283692] Job failed
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1631489883 is negative
        at java.base/java.lang.System.arraycopy(Native Method)
        at net.pms.io.BufferedOutputFileImpl.read(BufferedOutputFileImpl.java:722)
        at net.pms.io.WaitBufferedInputStream.read(WaitBufferedInputStream.java:52)
        at net.pms.io.WaitBufferedInputStream.read(WaitBufferedInputStream.java:62)
        at net.pms.network.HttpServletHelper.copyStream(HttpServletHelper.java:256)
        at net.pms.network.HttpServletHelper.lambda$copyStreamAsync$0(HttpServletHelper.java:300)
        at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1507)
        at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1500)
        at org.eclipse.jetty.ee10.servlet.AsyncContextState.lambda$start$0(AsyncContextState.java:138)
        at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1513)
        at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1530)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Unknown Source)
DEBUG 2024-10-21 13:12:35.265 [jupnp-sync-protocol 278370-1] Recognized media renderer "Samsung BU8000 65 TV"
```

**Comment by Mik-S-UMS** [comment]
This is abnormal and I have seen it a few times now in several peoples logs, I made a comment  about it the other day on a possibly related issue. (#5015)
```
Setting InputStream new position to: 9,223,372,034,707,292,031
```
I'm guessing this number is a result of an overflow, probably related to the negative number in the length.

**Comment by SubJunk** [comment]
@SurfaceS would this be fixed by https://github.com/UniversalMediaServer/UniversalMediaServer/pull/5046 ?

**Comment by Mik-S-UMS** [comment]
I got [someone else](https://www.universalmediaserver.com/forum/viewtopic.php?t=16212) with this same number showing up in the logs, and #5024 is showing a negative length too. 

I think every time I have seen it is was from a Samsung TV, although my PS4 was causing exception messages it still played.

Maybe UMS is not reading the range sent from the renderer correctly and is getting corrupted?

**Comment by SubJunk** [comment]
@mykeehu this fix will be in the next version of UMS, do you want me to upload a fixed build for you in the meantime?
