### ISSUE TITLE
java.lang.NumberFormatException when transcoding

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#5015]
I have been seeing this recently whenever anything transcodes

```
TRACE 2024-10-06 05:29:31.014 [jupnp-stream-server-96] Received a request from PlayStation 4 (192.168.1.194:62298):
============================= MEDIA HTTP SERVER REQUEST BEGIN ================================
GET /ums/media/0c9aa9fd-d117-363c-bffe-c20c14178780/34404/sample-30s.webm_transcoded_to.ts HTTP/1.1

HEADER:
  Range: bytes=-1048736-
  Host: 192.168.1.74:5001
  User-Agent: MediaPlayer/4.01 libhttp/10.71 (PlayStation 4)
  Connection: keep-alive
============================= MEDIA HTTP SERVER REQUEST END ==================================
WARN  2024-10-06 05:29:31.014 [jupnp-stream-server-96] /ums/media/0c9aa9fd-d117-363c-bffe-c20c14178780/34404/sample-30s.webm_transcoded_to.ts
java.lang.NumberFormatException: For input string: "1048736-"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at java.base/java.lang.Long.valueOf(Unknown Source)
	at net.pms.network.mediaserver.servlets.MediaServerServlet.getRange(MediaServerServlet.java:614)
	at net.pms.network.mediaserver.servlets.MediaServerServlet.sendMediaResponse(MediaServerServlet.java:287)
	at net.pms.network.mediaserver.servlets.MediaServerServlet.doGetHead(MediaServerServlet.java:161)
	at net.pms.network.mediaserver.servlets.MediaServerServlet.doGet(MediaServerServlet.java:85)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at net.pms.network.mediaserver.servlets.MediaServerHttpServlet.service(MediaServerHttpServlet.java:35)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)
	at org.eclipse.jetty.server.Server.handle(Server.java:181)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:661)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:406)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Maybe this has been related to the transcoding issues lately.

It also appears to be starting the transcode twice sometimes, in the logs I only started each video once.

[webm exception no audio.zip](https://github.com/user-attachments/files/17268236/webm.exception.no.audio.zip)
(same log as previous issue as it appears in this too)

**Comment by Mik-S-UMS** [comment]
This was something that only started to show up recently so I am not sure if it was something specific to the PS4.

I have also seen in some logs from several people that the renderer requests something like 9223372034707292159 bytes. [This](https://www.universalmediaserver.com/forum/viewtopic.php?p=48929#p48929) is one of the places I mentioned it on the forum.

I was thinking that UMS could be sending the incorrect range to the renderer but I could not find anything obvious in the sent messages.
```
============================= MEDIA HTTP SERVER RESPONSE BEGIN ===============================
HTTP/1.1 206 (non-chunked)

HEADER:
  Server: Windows_11-amd64-10.0, UPnP/1.0 DLNADOC/1.50, UMS/14.5.0
  Date: Sat, 28 Sep 2024 16:59:03 GMT
  TransferMode.DLNA.ORG: Streaming
  Content-Type: video/mpeg
  Content-Range: bytes 0-9223372034707292158/9223372034707292159
  Accept-Ranges: bytes
  Connection: keep-alive
============================= MEDIA HTTP SERVER RESPONSE END =================================
```

**Comment by Mik-S-UMS** [comment]
Updating with more info from #5810 
The first time this started happening was in 14.3.0

Edit Jetty was not made default until 14.3.0
It does show in 14.1.0 with Jetty enabled.

[ums_dbg_V14.1.0- PS4 exception with Jetty enabled.zip](https://github.com/user-attachments/files/25375342/ums_dbg_V14.1.0-.PS4.exception.with.Jetty.enabled.zip)
[ums_dbg_V14.2.1-No PS4 exception.zip](https://github.com/user-attachments/files/25375136/ums_dbg_V14.2.1-No.PS4.exception.zip)
[ums_dbg_V14.3.0-First PS4 exception.zip](https://github.com/user-attachments/files/25375137/ums_dbg_V14.3.0-First.PS4.exception.zip)
