### ISSUE TITLE
Videos often get stuck at 0:00 when attempting to resume - unable to fast forward when in this state - Must restart application to fix

### ISSUE THREAD

**Issue by KYFHO22** [UniversalMediaServer/UniversalMediaServer#5024]
TV - Samsung UN75RU9000FXZA

- When video gets stuck at 0:00, it isn't ACTUALLY at the start of the video (usually), but that is what shows in the progress bar on the TV, but when this happens, it can never be FF without restarting the app.
- Happening for the past 3-4 months or so (I attempted to figure out which version started this issue, without success)
- Issue persists regardless of video type
- The only way I have ever been able to fix was to stop and restart the application
- When testing with logging enabled, it didn't force the video back to 0:00, but it did go back to say 3:60 and would not allow to FF
- Sometimes he goes several days without an issue, sometimes it is multiple times per day, no rhyme or reason

[ums_dbg_2024-10-08-15-23.zip](https://github.com/user-attachments/files/17298969/ums_dbg_2024-10-08-15-23.zip)

**Comment by favorit5503** [comment]
Hi, a have the same issue.

I have a Samsung UE32H6200. 

The strange is that the log shows that the video started without the transcoding. After 80% of the video in my case it stops with a network error.

18:37:46 INFO  Stopped playing hdtv-friends.s05e14.bdrip.x264.hun.mkv on [TV]Samsung LED32
18:38:00 INFO  Started playing hdtv-friends.s05e14.bdrip.x264.hun.mkv (MEncoder Video) on your [TV]Samsung LED32
18:38:07 WARN  writeError: status=500, message=java.io.IOException: content-length 2 != 0 written, response=ErrorResponse@fdcce83{500,GET@4ade411c http://192.168.0.185:39001/ums/media/08f0d181-0096-1000-bf66-bc14850015be/2521/hdtv-friends.s05e14.bdrip.x264.hun.mkv HTTP/1.1}
java.io.IOException: content-length 2 != 0 written
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.succeeded(HttpChannelState.java:1534)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:765)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:426)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1507)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1500)
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.runInContext(ServletChannelState.java:1294)
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.complete(ServletChannelState.java:828)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.complete(AsyncContextState.java:61)
	at net.pms.network.HttpServletHelper.copyStream(HttpServletHelper.java:295)
	at net.pms.network.HttpServletHelper.lambda$copyStreamAsync$0(HttpServletHelper.java:305)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1507)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1500)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.lambda$start$0(AsyncContextState.java:138)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1513)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1530)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
18:38:10 WARN  Job failed
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -116914107 is negative

**Comment by Mik-S-UMS** [comment]
@KYFHO22 I think this is because you have the resume option enabled in UMS so it is starting a transcode from the last watched position for those renderers that do not keep track of played progress. Try turning this off so your TV can handle this.
```
# Enable video resuming
# ---------------------
# Whether to show virtual "Resume:" files to allow resuming videos.
# Default: true
resume =true
```
@SubJunk maybe the default value could be false as most modern devices don't need this.

@favorit5503 check this option too but the transcoding error may be what I have been seeing in several places like #5015 and #4919

**Comment by favorit5503** [comment]
> @KYFHO22 I think this is because you have the resume option enabled in UMS so it is starting a transcode from the last watched position for those renderers that do not keep track of played progress. Try turning this off so your TV can handle this.
> 
> ```
> # Enable video resuming
> # ---------------------
> # Whether to show virtual "Resume:" files to allow resuming videos.
> # Default: true
> resume =true
> ```
> 
> @SubJunk maybe the default value could be false as most modern devices don't need this.
> 
> @favorit5503 check this option too but the transcoding error may be what I have been seeing in several places like #5015 and #4919

Thanks i will check it and report back.

**Comment by favorit5503** [comment]
After some test it works. But now it dosnt mark the completed videos. And i saw a strange thing. Whit the resume =true there was a second file that was called resume: xxxx now its missing. Maybe that is the issue the two videos are overlapping?

**Comment by Mik-S-UMS** [comment]
That second resume:xxx file was the virtual file created by UMS's resume feature which would start a transcode at the last played position, but is not needed if you TV can keep track of played progress and can stream the video.

There was a bug #4887 not that long ago where UMS was not registering the stopped playing event so nothing streaming would be marked as played. This was fixed in 14.5.0

**Comment by favorit5503** [comment]
Sorry i forgot to mention i am on 14.6.0-snapshot

**Comment by SpitFire-666** [comment]
Experiencing the same issue. I get the same/similar error. Would paste the log here but it got overwritten by new entries 🤷

` java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -116914107 is negative`
