### ISSUE TITLE
Special characters in filenames causing exceptions (Malformed input or input contains unmappable characters)

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#5100]
Got a [report](https://www.universalmediaserver.com/forum/viewtopic.php?t=16253) that filenames with special characters (like é, ñ, ü etc) cause errors and prevent anything showing when browsing folders with these files.

```
ERROR 2024-11-08 21:35:24.006 [Media Scanner] net.pms.store.MediaScanner Unhandled exception during media scan: Malformed input or input contains unmappable characters: /muziekarchief/MUSIC/Bach/Bach complete org (MP3)/Clavier-��bung III (Bach 2000 v08CD06)
TRACE 2024-11-08 21:35:24.007 [Media Scanner] net.pms.store.MediaScanner 
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /muziekarchief/MUSIC/Bach/Bach complete org (MP3)/Clavier-��bung III (Bach 2000 v08CD06)
	at java.base/sun.nio.fs.UnixPath.encode(Unknown Source)
	at java.base/sun.nio.fs.UnixPath.<init>(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at net.pms.store.container.VirtualFolder.lambda$getFilesListForDirectories$0(VirtualFolder.java:154)
	at java.base/java.io.File.listFiles(Unknown Source)
	at net.pms.store.container.VirtualFolder.getFilesListForDirectories(VirtualFolder.java:153)
	at net.pms.store.container.VirtualFolder.discoverChildren(VirtualFolder.java:215)
	at net.pms.store.MediaScanner.scan(MediaScanner.java:141)
	at net.pms.store.MediaScanner.scan(MediaScanner.java:147)
	at net.pms.store.MediaScanner.scan(MediaScanner.java:147)
	at net.pms.store.MediaScanner.startScan(MediaScanner.java:98)
	at net.pms.store.MediaScanner.lambda$startMediaScan$0(MediaScanner.java:198)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR 2024-11-08 21:35:47.648 [webgui-server-40] net.pms.network.webguiserver.servlets.PlayerApiServlet Exception in PlayerApiServlet: Malformed input or input contains unmappable characters: /muziekarchief/MUSIC/Bach/Bach complete org (MP3)/Clavier-��bung III (Bach 2000 v08CD06)
TRACE 2024-11-08 21:35:47.649 [webgui-server-40] net.pms.network.webguiserver.servlets.PlayerApiServlet {}
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /muziekarchief/MUSIC/Bach/Bach complete org (MP3)/Clavier-��bung III (Bach 2000 v08CD06)
	at java.base/sun.nio.fs.UnixPath.encode(Unknown Source)
	at java.base/sun.nio.fs.UnixPath.<init>(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at net.pms.store.container.VirtualFolder.lambda$getFilesListForDirectories$0(VirtualFolder.java:154)
	at java.base/java.io.File.listFiles(Unknown Source)
	at net.pms.store.container.VirtualFolder.getFilesListForDirectories(VirtualFolder.java:153)
	at net.pms.store.container.VirtualFolder.discoverChildren(VirtualFolder.java:215)
	at net.pms.store.StoreContainer.discover(StoreContainer.java:696)
	at net.pms.store.MediaStore.getResources(MediaStore.java:664)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.getBrowsePage(PlayerApiServlet.java:339)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.doPost(PlayerApiServlet.java:153)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at net.pms.network.webguiserver.GuiHttpServlet.service(GuiHttpServlet.java:61)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server.Server.handle(Server.java:181)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:661)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:406)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR 2024-11-08 21:36:19.042 [webgui-server-38] net.pms.network.webguiserver.servlets.PlayerApiServlet Exception in PlayerApiServlet: Malformed input or input contains unmappable characters: /muziekarchief/MUSIC/Christmas/Andre Rieu/Merry Christmas/09 - Minuit Chr��tien.mp3
TRACE 2024-11-08 21:36:19.045 [webgui-server-38] net.pms.network.webguiserver.servlets.PlayerApiServlet {}
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /muziekarchief/MUSIC/Christmas/Andre Rieu/Merry Christmas/09 - Minuit Chr��tien.mp3
	at java.base/sun.nio.fs.UnixPath.encode(Unknown Source)
	at java.base/sun.nio.fs.UnixPath.<init>(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at net.pms.store.container.VirtualFolder.lambda$getFilesListForDirectories$0(VirtualFolder.java:154)
	at java.base/java.io.File.listFiles(Unknown Source)
	at net.pms.store.container.VirtualFolder.getFilesListForDirectories(VirtualFolder.java:153)
	at net.pms.store.container.VirtualFolder.discoverChildren(VirtualFolder.java:215)
	at net.pms.store.StoreContainer.discover(StoreContainer.java:696)
	at net.pms.store.MediaStore.getResources(MediaStore.java:664)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.getBrowsePage(PlayerApiServlet.java:339)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.doPost(PlayerApiServlet.java:153)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at net.pms.network.webguiserver.GuiHttpServlet.service(GuiHttpServlet.java:61)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
	at org.eclipse.jetty.server.Server.handle(Server.java:181)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:661)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:406)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Mik-S-UMS** [comment]
I saw an interesting [video](https://www.youtube.com/watch?v=QFAyxoGTgGE) recently that may be the same thing.

It showed their program not returning any results if there is a � symbol in the data. It had something to do with the encoding of the text being in extended ASCII (ISO-8859-1) instead of UTF-8 which is otherwise compatible for standard English characters, except the 8th bit used for accents and symbols which then throws an error when trying to read as UTF-8.

This is exactly what is showing in those logs `09 - Minuit Chr��tien.mp3`
Maybe somewhere in UMS it is using extended ASCII, or the filename/OS is using that format.

**Comment by LaTeteDansLesEtoiles** [comment]
That could be the problem, indeed. I'm Frenvch and "09 - Minuit Chr��tien.mp3" should read "09 - Minuit Chrétien.mp3" for me.

If it is relevant, please know that I use debian Bookworm with ext4 filesystems.

Any idea regarding what we could do, please?

**Comment by SurfaceS** [comment]
@Mik-S-UMS What UMS version ? What os ?

Seems to be only on linux.

```
TRACE 2024-11-08 21:35:24.007 [Media Scanner] net.pms.store.MediaScanner 
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /muziekarchief/MUSIC/Bach/Bach complete org (MP3)/Clavier-��bung III (Bach 2000 v08CD06)
```
This is before any browse. It is on parsing the file.

**Comment by Mik-S-UMS** [comment]
I checked the logs on the forum and those were from 14.6.0
`OS: GNU/Linux Debian GNU/Linux 11 (bullseye) build 5.10.0-26-amd64 64-bit`

It does seem to be a Linux issue as Boss on the forum mentioned the same thing but he just renamed any files that used special characters in the past, but this may not be practical if someone has many files that use these.

Rereading that thread on the forum it previously worked fine on 10.13. I don't know if this still happens in the current version.

@LaTeteDansLesEtoiles what version are you using? Could you post your logs too to confirm it is the same thing? See [this](https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556) on how to create them

**Comment by LaTeteDansLesEtoiles** [comment]
I use 14.11.0. Here is a log extract exhibiting the problem:

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.pms.store.MediaScanner.init(MediaScanner.java:79)
	at net.pms.PMS.init(PMS.java:269)
	at net.pms.PMS.createInstance(PMS.java:1009)
	at net.pms.PMS.main(PMS.java:960)
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/me/Vid?os`

Where the folder is /home/me/Vidéos

**Comment by SurfaceS** [comment]
I have a lot of accented folder without any problem (windows 11).

So it should have something to do with linux / java launch / etc

**Comment by LaTeteDansLesEtoiles** [comment]
Indeed. Any advice to keep me back on track, please?

**Comment by Mik-S-UMS** [comment]
Is there a function that can be used to switch to ISO-8859-1 for these � symbols and convert them to UTF-8?

At least these need to be safely handled so it does not throw an exception and prevent the folder contents from showing as this is a big problem for French and Spanish users for example.

@LaTeteDansLesEtoiles is it possible to change the text encoding for the OS in Linux? I know next to nothing about Linux.

I did notice in the original logs I got those errors from in the System information it did say `Encoding: UTF-8` so don't know why it is failing to read these characters unless something is reading them as ISO-8859-1

**Comment by Mik-S-UMS** [comment]
I did a bit more googling and it appears it is possible for filenames to be encoded in ISO-8859-1 even if the system is using UTF-8, mainly if they were created on an older OS.

I found some info about how to convert these filenames. The main problem is to know what encoding is being used first so it takes some hand-holding to get right as it is possible to double encode into one format.
https://askubuntu.com/questions/568565/how-to-rename-file-names-to-different-encoding
https://tr.opensuse.org/SDB:Converting_Files_or_File_Names_to_UTF-8_Encoding
https://linux.die.net/man/1/convmv
https://linux.die.net/man/1/detox

 @LaTeteDansLesEtoiles give this a try with some of the problematic files you have. This will confirm if it is the cause.
Best to set up a test folder you can copy the files into so you don't alter the original ones and set that as a shared folder. 
You may also need to disable your normal shared folders to stop them from interfering.

**Comment by SurfaceS** [comment]
@Mik-S-UMS things is I do not have the trace logs, so it is hard to know what is going on.

1st, check if the `LogSystemInformation` report the right encoding (`UTF-8`) :
```
INFO  2025-04-10 08:59:46.539 [System Information Logger] System information:
  OS: Microsoft Windows 11 build 26100 64-bit
  JVM: OpenJDK 64-Bit Server VM 17.0.14 (64-bit) by BellSoft
  Language: French
  Encoding: UTF-8
```

I added a PR #5455 to log the JVM flags at start, to be sure that `-Dfile.encoding=UTF-8` was passed as argument.

**Comment by SurfaceS** [comment]
> I did a bit more googling and it appears it is possible for filenames to be encoded in ISO-8859-1 even if the system is using UTF-8, mainly if they were created on an older OS.
> 
> I found some info about how to convert these filenames. The main problem is to know what encoding is being used first so it takes some hand-holding to get right as it is possible to double encode into one format. https://askubuntu.com/questions/568565/how-to-rename-file-names-to-different-encoding https://tr.opensuse.org/SDB:Converting_Files_or_File_Names_to_UTF-8_Encoding https://linux.die.net/man/1/convmv https://linux.die.net/man/1/detox
> 
> [@LaTeteDansLesEtoiles](https://github.com/LaTeteDansLesEtoiles) give this a try with some of the problematic files you have. This will confirm if it is the cause. Best to set up a test folder you can copy the files into so you don't alter the original ones and set that as a shared folder. You may also need to disable your normal shared folders to stop them from interfering.

@Mik-S-UMS what you suggest is about file **content** encoding.
This is not the case here and their is no need to convert the file content.

Here things are that java get the filename like `Vid?os`, and it is more likely just a java args things.
Java is responsible of interfacing system and virtual machine.

On the PR, I added an example output (my running debug).
`JVM args: -Dfile.encoding=UTF-8`
`Encoding: UTF-8 | resolved UTF-8 | native Cp1252 | jnu Cp1252 | stdout null | stderr null`

Here, you see that UMS (java virtual machine) is using UTF-8, and my OS is using Cp1252.
And I do not have any problem with filenames, accented or not.

Java will default to UTF-8 for versions after 17, so it will help if users remove the `-Dfile.encoding=UTF-8`.
> File encoding and UTF-8 as default charset. Java Platform Enhancement Proposal (JEP) 400 introduced UTF-8 as the default charset for standard Java APIs across all operating systems, starting with Java 18, except for the console input and output encoding.

**Comment by SurfaceS** [comment]
@Mik-S-UMS @LaTeteDansLesEtoiles 
The only files that need to be `UTF-8` are files for UMS (`UMS.conf`, `SHARED.conf`, `renderer.conf`, and so on).

That may break the parser if not `UTF-8`, and it seems to be the case for @LaTeteDansLesEtoiles (manual edit ?).

**Comment by SurfaceS** [comment]
@Mik-S-UMS You are right... On Linux filenames are not updated on locale change :worried:, and then can end using different encoding.
And they can mount disk with another encoding as well.
Java made the encoding translation from the current OS's encoding. That could end in a bad char.

So, your solution using `convmv` is valuable in case they done a mistake.

> At least these need to be safely handled so it does not throw an exception and prevent the folder contents from showing as this is a big problem for French and Spanish users for example.

@Mik-S-UMS added a PR #5100
It log if : 
- conf cannot be well loaded by a bad file encoding.
- should handle better bad filename encoding
- log if InvalidPathException instead of throw.

That may make the files that has bad filename encoding readable... I can't confirm.
But at least, that will not prevent user to use UMS.

That with the other PR, we will have a better log of what happen.

**Comment by Mik-S-UMS** [comment]
Thats great. We will need some Linux users to test this. Could you do a test build for @LaTeteDansLesEtoiles 

I updated the thread on the forum about the progress on this. Maybe Boss could do some testing too as he is the one with knowledge about Linux.

**Comment by SubJunk** [comment]
@LaTeteDansLesEtoiles do you want me to send you the fixed version?

**Comment by Fabien-35235** [comment]
Same issue here.
I'm using UMS hosted in a docker+compose (see bellow), hosted on a Linux server.
My audio files and directories are mounted on the UMS docker from the Linux server.
On the Linux server, I'm using (of course) UTF8 filename, without any issues.
The directories and files that use accentuated letters (éàèç...) do NOT appear on the embedded UMS UI (port 9002), and are not shown on any DNLA player that connect to UMS.
Any  other file/directory is fine.

For instance:
/musique/French/song1.mp3   is shown
/musique/French/à-chanter.mp3 is not shown
/musique/Français/song1.mp3 is not shown (no folder, no file)

Of course, the standard UMS.sh script is used, and it uses  `-Dfile.encoding=UTF-8`
I guess that can be easily tested by replicating the docker setup:

Docker/Compose file:
```
services:
  universalmediaserver:
    image: universalmediaserver/ums
    container_name: UMS
    network_mode: host
    environment:
      - UMS_PROFILE=/profile 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /opt/my-omv/UMS:/profile
      - /srv/dev-disk-by-uuid-96c47f8d-03d0-40a4-99e4-de9cce7679f1/Music:/musique
    restart: 'unless-stopped'
```

**Comment by Fabien-35235** [comment]
Building my own Docker compose file based on latest Ubuntu and 15.3.0 (see bellow).

The issue is still there: files and directories with accentuated letter are not shwon on the local UI, `http://omv.local:9001/player/browse/0` for instance _Delibes-Lakmé_ and _Verdi-71-Aïda_ are not visible.

Extract from the logs:
INFO  12:46:20.937 [main] Build: 33887b553 (2025-12-11)
INFO  12:46:20.937 [main] Working directory: /ums-15.3.0
...
INFO  12:46:21.178 [System Information Logger] System information:
  OS: GNU/Linux Ubuntu 24.04.3 LTS (Noble Numbat) build 6.12.57+deb12-amd64 64-bit
  JVM: OpenJDK 64-Bit Server VM 17.0.17 (64-bit) by BellSoft
  JVM args: -Xmx1280M -Xss2048k -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djna.nosys=true 
  Language: English (United States)
  Encoding: UTF-8 | resolved UTF-8 | native ANSI_X3.4-1968 | jnu ANSI_X3.4-1968 | stdout ANSI_X3.4-1968 | stderr ANSI_X3.4-1968
  CPU: Intel(R) N100 with 4 cores (unknown)
  Physical Memory: 15.4 GiB
  Free Memory: 11.9 GiB
  Maximum JVM Memory: 1.3 GiB

Docker Compose File:
```
services:
  ums:
    container_name: UMS2
    network_mode: host
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:latest
        RUN apt-get update
        RUN apt-get install nano
        RUN apt-get install -y default-jre 
        RUN apt-get install -y default-jre-headless
        RUN apt-get install -y mediainfo dcraw vlc mplayer mencoder
        # RUN apt-get install -y lib32z1 lib32ncurses5 libbz2-1.0:i386 libstdc++6:i386
        RUN apt-get install -y p7zip
        RUN apt-get install -y wget
        RUN wget https://github.com/UniversalMediaServer/UniversalMediaServer/releases/download/15.3.0/UMS-Linux-15.3.0-x86_64.tgz
        RUN tar xzvf UMS-Linux-15.3.0-x86_64.tgz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /srv/dev-disk-by-uuid-96c47f8d-03d0-40a4-99e4-de9cce7679f1/Video:/video:ro
      - /srv/dev-disk-by-uuid-96c47f8d-03d0-40a4-99e4-de9cce7679f1/Music:/musique
    command: /ums-15.3.0/UMS.sh
    restart: 'unless-stopped'
```

**Comment by Mik-S-UMS** [comment]
Could you post your logs so I can see if it is the same thing.
see https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556
