### ISSUE TITLE
Transcode not working

### ISSUE THREAD

**Issue by carrchri** [UniversalMediaServer/UniversalMediaServer#5143]
I try to set a new renderer and the streaming is OK but not the transcode.

I have this error in the log.

============================= MEDIA HTTP SERVER RESPONSE BEGIN ===============================
HTTP/1.1 206 (non-chunked)

HEADER:
  Server: Windows_10-amd64-10.0, UPnP/1.0 DLNADOC/1.50, UMS/14.6.0
  Date: Sun, 01 Dec 2024 15:49:26 GMT
  TransferMode.DLNA.ORG: Streaming
  Content-Type: audio/mpeg
  Content-Range: bytes 0-15/9223372034707292159
  ContentFeatures.DLNA.ORG: DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=01700000000000000000000000000000
  Accept-Ranges: bytes
  Connection: keep-alive
  Content-Length: 16
============================= MEDIA HTTP SERVER RESPONSE END =================================
DEBUG 2024-12-01 16:49:26.141 [jupnp-stream-server-553038] Sending stream with premature end: 0 bytes. Reason: written 32768 > 16 content-length
TRACE 2024-12-01 16:49:26.141 [jupnp-stream-server-553038] Stream Async Premature end: written 32768 > 16 content-length, duration: 1 ms
TRACE 2024-12-01 16:49:26.143 [jupnp-stream-server-553038] Ready to Stop: true
TRACE 2024-12-01 16:49:26.144 [jupnp-stream-server-553038] Stream Async Complete, uri: /ums/media/140479c0-58f3-1cef-84bf-0016f53f97a3/14844/A_Toi.mp3_transcoded_to.mp3, duration: 3 ms
WARN  2024-12-01 16:49:26.144 [jupnp-stream-server-553038] writeError: status=500, message=java.io.IOException: content-length 16 != 0 written, response=ErrorResponse@7c22f836{500,GET@30d14c24 http://192.168.33.3:5001/ums/media/140479c0-58f3-1cef-84bf-0016f53f97a3/14844/A_Toi.mp3_transcoded_to.mp3 HTTP/1.1}
java.io.IOException: content-length 16 != 0 written
	at org.eclipse.jetty.server.internal.HttpChannelState$ChannelCallback.succeeded(HttpChannelState.java:1533)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.onCompleted(ServletChannel.java:765)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:426)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1507)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1500)
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.runInContext(ServletChannelState.java:1294)
	at org.eclipse.jetty.ee10.servlet.ServletChannelState.complete(ServletChannelState.java:828)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.complete(AsyncContextState.java:61)
	at net.pms.network.HttpServletHelper.copyStream(HttpServletHelper.java:290)
	at net.pms.network.HttpServletHelper.lambda$copyStreamAsync$0(HttpServletHelper.java:300)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1507)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1500)
	at org.eclipse.jetty.ee10.servlet.AsyncContextState.lambda$start$0(AsyncContextState.java:138)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1513)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.lambda$execute$0(ContextHandler.java:1530)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by SubJunk** [comment]
@carrchri we need a full debug package for this, please follow the instructions at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/new

**Comment by carrchri** [comment]
[ums_dbg_2024-12-03-17-48.zip](https://github.com/user-attachments/files/17996322/ums_dbg_2024-12-03-17-48.zip)
