### ISSUE TITLE
Unhandled exception For input string: "CC1" and "CC3"

### ISSUE THREAD

**Issue by Mik-S-UMS** [UniversalMediaServer/UniversalMediaServer#5158]
I thought I had already made this but I must have forgotten. I saw this again in issue #4954 that reminded me.

```
19:27:51 WARN Unhandled exception while resolving The Phantom Menace: For input string: "CC3"
19:27:51 WARN Unhandled exception while resolving Revenge of the Sith: For input string: "CC3"
19:27:52 WARN Unhandled exception while resolving Stargate The Ark of Truth: For input string: "CC1"
```
I have seen these exceptions before when the subtitles use the CC1 or CC3 format.

I did see a mention of incorrect ID parsing for these [here](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1232#issuecomment-289019052) but I don't know if it is related.

**Comment by SubJunk** [comment]
@Mik-S-UMS do you have CC1 or CC3 subtitles I can test with? I will need to get the full error stack

**Comment by Mik-S-UMS** [comment]
I don't have any, I just saw this in others logs.

I think [this](https://www.universalmediaserver.com/forum/viewtopic.php?p=48972) was the first time I saw this but forgot to create the issue then.

In this case it came from DVD rips and added by the program that did the rip.
I don't think that user has been on the forum since to ask them for their files.

**Comment by Mik-S-UMS** [comment]
I got another couple of instances of this error on the forum [here](https://www.universalmediaserver.com/forum/viewtopic.php?t=16494) and [here](https://www.universalmediaserver.com/forum/viewtopic.php?p=49555#p49555).
This is the full error message and the rest can be found in the logs if I have missed something important.
```

TRACE 2025-02-19 16:32:00.696 [Media Scanner] net.pms.store.MediaInfoStore Store does not yet contain MediaInfo for I:\Séries\Magnum P I\Saison 5\Magnum P I 2018 S05E01 WEBRip x264-ION10.mp4
ERROR 2025-02-19 16:32:00.871 [Media Scanner] net.pms.store.MediaScanner Unhandled exception during media scan: For input string: "CC1"
TRACE 2025-02-19 16:32:00.872 [Media Scanner] net.pms.store.MediaScanner 
java.lang.NumberFormatException: For input string: "CC1"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Long.parseLong(Unknown Source)
	at java.base/java.lang.Long.valueOf(Unknown Source)
	at net.pms.parsers.MediaInfoParser.getSpecificID(MediaInfoParser.java:1090)
	at net.pms.parsers.MediaInfoParser.parse(MediaInfoParser.java:505)
	at net.pms.parsers.Parser.parse(Parser.java:79)
	at net.pms.store.MediaInfoStore.getMediaInfo(MediaInfoStore.java:152)
	at net.pms.store.item.RealFile.resolve(RealFile.java:254)
	at net.pms.store.StoreContainer.addChild(StoreContainer.java:122)
	at net.pms.store.container.VirtualFolder.manageFile(VirtualFolder.java:115)
	at net.pms.store.container.VirtualFolder.analyzeChildren(VirtualFolder.java:198)
	at net.pms.store.container.VirtualFolder.discoverChildren(VirtualFolder.java:323)
	at net.pms.store.MediaScanner.scan(MediaScanner.java:141)
	at net.pms.store.MediaScanner.scan(MediaScanner.java:147)
	at net.pms.store.MediaScanner.scan(MediaScanner.java:147)
	at net.pms.store.MediaScanner.startScan(MediaScanner.java:98)
	at net.pms.store.MediaScanner.lambda$startMediaScan$0(MediaScanner.java:198)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I have asked if they could upload that video somewhere so you are able to download it for testing.

**Comment by Mik-S-UMS** [comment]
They have sent me a link and I confirmed it has this. This is the MediaInfo of that video.

```
General
Complete name                  : C:\Users\user\Downloads\Video\Magnum P I 2018 S05E01 WEBRip x264-ION10.mp4
Format                         : MPEG-4
Format profile                 : Base Media
Codec ID                       : isom (isom/iso2/avc1/mp41)
File size                      : 417 MiB
Duration                       : 43 min 32 s
Overall bit rate               : 1 340 kb/s
Frame rate                     : 23.976 FPS
Movie name                     : RARBG - Magnum.P.I.2018.S05E01.WEBRip.x264-ION10
Encoded date                   : 2023-02-20 10:43:14 UTC
Tagged date                    : 2023-02-20 10:43:14 UTC
Writing application            : Lavf58.20.100
Comment                        : RARBG - Magnum.P.I.2018.S05E01.WEBRip.x264-ION10

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L3.1
Format settings                : CABAC / 5 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 5 frames
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 43 min 32 s
Bit rate                       : 1 100 kb/s
Width                          : 720 pixels
Height                         : 400 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.159
Stream size                    : 336 MiB (80%)
Title                          : RARBG - Magnum.P.I.2018.S05E01.WEBRip.x264-ION10
Writing library                : x264 core 152 rarbg
Encoding settings              : cabac=1 / ref=5 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=9 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=12 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=abr / mbtree=1 / bitrate=1100 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                   : 2023-02-20 10:43:14 UTC
Tagged date                    : 2023-02-20 10:43:14 UTC
Codec configuration box        : avcC

Audio
ID                             : 2
Format                         : AAC LC
Format/Info                    : Advanced Audio Codec Low Complexity
Codec ID                       : mp4a-40-2
Duration                       : 43 min 32 s
Duration_LastFrame             : -11 ms
Bit rate mode                  : Constant
Bit rate                       : 256 kb/s
Channel(s)                     : 2 channels
Channel layout                 : L R
Sampling rate                  : 48.0 kHz
Frame rate                     : 46.875 FPS (1024 SPF)
Compression mode               : Lossy
Stream size                    : 79.7 MiB (19%)
Title                          : RARBG - Magnum.P.I.2018.S05E01.WEBRip.x264-ION10
Language                       : English
Default                        : Yes
Alternate group                : 1
Encoded date                   : 2023-02-20 10:43:14 UTC
Tagged date                    : 2023-02-20 10:43:14 UTC

Text #1
ID                             : 1-CC1
Format                         : EIA-608
Muxing mode                    : SCTE 128 / DTVCC Transport
Muxing mode, more info         : Muxed in Video #1
Duration                       : 43 min 32 s
Start time                     : 1 s 43 ms
Bit rate mode                  : Constant
Stream size                    : 0.00 Byte (0%)
Count of frames before first e : 73
Type of the first event        : PopOn

Text #2
ID                             : 1-1
Format                         : EIA-708
Muxing mode                    : SCTE 128 / DTVCC Transport
Muxing mode, more info         : Muxed in Video #1
Duration                       : 43 min 32 s
Bit rate mode                  : Constant
Stream size                    : 0.00 Byte (0%)
```
I have sent you a PM with the link on the forum so you can test it yourself too.

**Comment by Mik-S-UMS** [comment]
This is a bit more serious than I thought.

I assumed when this exception happens the file is ignored, skipped and UMS carries on.  
But having a video with this breaks browsing of that folder so it appears empty. 
If this happens to be in a root folder then there will be no content shown at all. Removing it brings all the contents back.

This also breaks file scanning and it will stop after encountering it, however UMS thinks it is still scanning even if this video is removed and a manual scan started which brings up another error I forgot to copy.

This may also have messed up the transcode folder as they all appear empty too, but this may be an issue with V15a as deleting the database did not fix it and I had not needed to use this folder since installing v15a.

**Comment by SubJunk** [comment]
Oh damn, ok this should be prioritized

**Comment by SubJunk** [comment]
It's fixed now awaiting review

**Comment by Mik-S-UMS** [comment]
Thats great. Could you do a test build for Capiray on the [forum](https://www.universalmediaserver.com/forum/viewtopic.php?t=16494) to confirm this is the cause of their problems. 

There were other warning messages that you mentioned in #5292 in their logs too but this will confirm that I can ignore these.

**Comment by SubJunk** [comment]
Have replied on the forum. I have started checking if users are willing to test first, since sometimes they disappear and it was a waste of time 😆

**Comment by Capiray** [comment]
Hum! Hum! Please check forum. Don't forget this is open source.  ;)
