### ISSUE TITLE
Exception in result creation "null"

### ISSUE THREAD

**Issue by MrHappy** [UniversalMediaServer/UniversalMediaServer#5179]
Installed this today to use with my Pioneer radio and tried to integrate it into Home Assistant.
I've got no idea what to make of it.

```
INFO  17:37:26.797 [jupnp-sync-protocol 5329-1] Media renderer was not recognized. Possible identifying HTTP headers:
 User-Agent: HomeAssistant/2024.12.5 aiohttp/3.11.11 Python/3.13
 Soapaction: "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
ERROR 17:37:26.798 [jupnp-sync-protocol 5329-1] Exception in result creation "null"
 java.lang.UnsupportedOperationException: null
 	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
 	at java.base/java.util.ImmutableCollections$AbstractImmutableList.set(ImmutableCollections.java:260)
 	at java.base/java.util.Collections.swap(Collections.java:501)
 	at java.base/java.util.Collections.reverse(Collections.java:382)
 	at net.pms.store.utils.StoreResourceSorter.sortResources(StoreResourceSorter.java:66)
 	at net.pms.store.utils.StoreResourceSorter.sortResources(StoreResourceSorter.java:61)
 	at net.pms.network.mediaserver.jupnp.support.contentdirectory.UmsContentDirectoryService.browse(UmsContentDirectoryService.java:760)
 	at net.pms.network.mediaserver.jupnp.support.contentdirectory.UmsContentDirectoryService.browse(UmsContentDirectoryService.java:292)
 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
 	at org.jupnp.util.Reflections.invoke(Reflections.java:42)
 	at org.jupnp.model.action.MethodActionExecutor.execute(MethodActionExecutor.java:94)
 	at org.jupnp.model.action.AbstractActionExecutor$1.execute(AbstractActionExecutor.java:74)
 	at org.jupnp.model.DefaultServiceManager.execute(DefaultServiceManager.java:130)
 	at org.jupnp.model.action.AbstractActionExecutor.execute(AbstractActionExecutor.java:71)
 	at org.jupnp.protocol.sync.ReceivingAction.executeSync(ReceivingAction.java:104)
 	at org.jupnp.protocol.ReceivingSync.execute(ReceivingSync.java:65)
 	at org.jupnp.protocol.ReceivingAsync.run(ReceivingAsync.java:71)
 	at org.jupnp.transport.spi.UpnpStream.process(UpnpStream.java:83)
 	at net.pms.network.mediaserver.jupnp.transport.impl.JakartaServletUpnpStream.run(JakartaServletUpnpStream.java:70)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by SubJunk** [comment]
@MrHappy did the server work? This error might not be related

**Comment by transcaffeine** [comment]
@SubJunk What do you mean by 'did the server work'? Those are UMS server logs, i am seeing the same logs with HomeAssistant/2025.1.0

**Comment by magcode** [comment]
my interpretation of the issue:

This [line](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/baba40fe85775f734bf93f1d1917d2e7dc29045f/src/main/java/net/pms/store/utils/StoreResourceSorter.java#L65) creates an immutable list which cannot be sorted. 

Code fails as soon more than one sortCriterion is present.

**Comment by SubJunk** [comment]
Thanks for these reports, I'm looking into this now

**Comment by SubJunk** [comment]
It would be much easier to debug and fix if we had full debug logs, it would be good to see the network request that is triggering this to happen

**Comment by SubJunk** [comment]
I have a fix to test but I need to know which operating system one of you is using so I can upload the right file

**Comment by SubJunk** [comment]
Closing for lack of activity

**Comment by magcode** [comment]
I tested in branch 5179-null-result and it works fine. Thanks for fixing the issue.

**Comment by SubJunk** [comment]
@magcode thank you for testing, I will merge that branch now
