### ISSUE TITLE
UMS crashes while scanning folder with music

### ISSUE THREAD

**Issue by prescott66** [UniversalMediaServer/UniversalMediaServer#5192]
When UMS starts to scan freshly added folder with my music collection, it crashes.
I have 3 other fodlers with movies in my database, scanning was done without issues.
Maybe is problem with my files, but i think UMS should handle this kind of problem without crashing.

Steps to reproduce:
1.Run UMS
2.Add folder with music
3. Media scanner started
4. UMS crashes

Version of UMS: 14.8.0 (using built-in java on Arch linux 64bit)

Attached log:

[debug.log](https://github.com/user-attachments/files/18246202/debug.log)

**Comment by SubJunk** [comment]
@prescott66 can you please upload one of the files so I can reproduce it?

**Comment by prescott66** [comment]
[failing_mp_three.zip](https://github.com/user-attachments/files/18251692/failing_mp_three.zip)

Pass: "subjunk"

**Comment by SubJunk** [comment]
@prescott66 I do get the same error you see, but it doesn't cause a crash for me. The weird thing is that in your logs, there should also be TRACE logs after those two lines, but there isn't. On mine I see:

```
TRACE 2024-12-27 18:33:56.831 [MediaScanner File Parser] Waiting file 11-black_label_society-chupacabra.mp3 is fully written
DEBUG 2024-12-27 18:33:57.334 [MediaScanner File Parser] Analyzing file 11-black_label_society-chupacabra.mp3
TRACE 2024-12-27 18:33:57.334 [MediaScanner File Parser] Matched format MP3 to "11-black_label_society-chupacabra.mp3"
TRACE 2024-12-27 18:33:57.334 [MediaScanner File Parser] Store does not yet contain MediaInfo for 11-black_label_society-chupacabra.mp3
TRACE 2024-12-27 18:33:57.401 [MediaScanner File Parser] Converting byte array image source to SOURCE format and type DLNAThumbnail using the following parameters: ScaleType = MAX, Width = 640, Height = 480, PadToSize = False
TRACE 2024-12-27 18:33:57.418 [MediaScanner File Parser] Image conversion DLNA compliance check: The source image is compliant
TRACE 2024-12-27 18:33:57.453 [MediaScanner File Parser] Finished converting 600x595 PNG image. Output image resolution: 484x480, profile: PNG_LRG. Flags: Convert colors = False, Re-encode = False
TRACE 2024-12-27 18:33:57.457 [MediaScanner File Parser] Parsing image file "11-black_label_society-chupacabra.mp3"
DEBUG 2024-12-27 18:33:57.460 [MediaScanner File Parser] Error parsing image (11-black_label_society-chupacabra.mp3), switching to MediaInfo: Unable to recognize image format for "11-black_label_society-chupacabra.mp3" - parsing failed
TRACE 2024-12-27 18:33:57.460 [MediaScanner File Parser] 
net.pms.util.UnknownFormatException: Unable to recognize image format for "11-black_label_society-chupacabra.mp3" - parsing failed
	at net.pms.parsers.MetadataExtractorParser.parseStream(MetadataExtractorParser.java:212)
	at net.pms.parsers.MetadataExtractorParser.parse(MetadataExtractorParser.java:135)
	at net.pms.parsers.MediaInfoParser.parse(MediaInfoParser.java:456)
	at net.pms.parsers.Parser.parse(Parser.java:79)
	at net.pms.store.MediaInfoStore.getMediaInfo(MediaInfoStore.java:152)
	at net.pms.store.item.RealFile.resolve(RealFile.java:249)
	at net.pms.store.StoreItem.syncResolve(StoreItem.java:1464)
	at net.pms.store.item.RealFile.syncResolve(RealFile.java:328)
	at net.pms.store.MediaScanner.parseFileEntry(MediaScanner.java:431)
	at net.pms.store.MediaScanner.lambda$parseFileEntry$2(MediaScanner.java:384)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.pms.util.UnknownFormatException: Unable to find a suitable image reader
	at net.pms.parsers.MetadataExtractorParser.readImageInfo(MetadataExtractorParser.java:856)
	at net.pms.parsers.MetadataExtractorParser.parseStream(MetadataExtractorParser.java:209)
	... 10 common frames omitted
TRACE 2024-12-27 18:33:57.540 [MediaScanner File Parser] MediaInfo parsing results for "11-black_label_society-chupacabra.mp3":
  Title: "Chupacabra"           Format: "MPEG Audio"          Duration: 0:00:49.084         Overall Bitrate Mode: VBR
  Overall Bitrate: 219997       Cover: Yes                    Track: "Chupacabra"           Album: "Order Of The Black"
  Performer: "Black Label Society"                            Genre: "Heavy Metal"          Rec Date: "2010-08-10"
  - Audio track ID: 
    Format: "MPEG Audio"          Version: "Version 1"          Profile: "Layer 3"            Duration: 0:00:49.084
    BitRate Mode: VBR             Bitrate: 219997               Language: "en"                Channel(s): 2
    Samplerate: 44100             Track: 11
  - Image ID: 
    Format: "PNG"                 Width: 600                    Height: 595
INFO  2024-12-27 18:33:57.543 [MediaScanner File Parser] New file 11-black_label_society-chupacabra.mp3 was detected and added to the media store
```

What exactly do you mean by "crashing"?

**Comment by prescott66** [comment]
@SubJunk by crashing i mean terminatig java process, so ums is not running anymore. I thought it is a java problem. But behaviour is same with built-in java and jre17 or jre21 installed from arch repository.

**Comment by SubJunk** [comment]
@prescott66 can you please attach your UMS.conf file too?
