### ISSUE TITLE
NullPointer on renderer discovered

### ISSUE THREAD

**Issue by taconaut** [UniversalMediaServer/UniversalMediaServer#550]
Since some weeks I get this NullPointerException every time ums starts:

```
05-04 21:37:04  Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
05-04 21:37:04  	at net.pms.newgui.StatusTab$2.run(StatusTab.java:371)
05-04 21:37:04  	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
05-04 21:37:04  	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
05-04 21:37:04  	at java.awt.EventQueue.access$500(Unknown Source)
05-04 21:37:04  	at java.awt.EventQueue$3.run(Unknown Source)
05-04 21:37:04  	at java.awt.EventQueue$3.run(Unknown Source)
05-04 21:37:04  	at java.security.AccessController.doPrivileged(Native Method)
05-04 21:37:04  	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
05-04 21:37:04  	at java.awt.EventQueue.dispatchEvent(Unknown Source)
05-04 21:37:04  	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
05-04 21:37:04  	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
05-04 21:37:04  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
05-04 21:37:04  	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
05-04 21:37:04  	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
05-04 21:37:04  	at java.awt.EventDispatchThread.run(Unknown Source)
```

This happens when my Philips hue bridge is being discovered. It worked before (http://www.universalmediaserver.com/forum/viewtopic.php?t=2523). I can't tell if something changed on the ums or the hue bridge side (for which I've updated the firmeware).

**Comment by skeptical** [comment]
@taconaut is your build after this [fix](https://github.com/UniversalMediaServer/UniversalMediaServer/commit/c561b6c0fe844c1c123c325b47e8d90d604efd81#diff-f5b741a4eb8562a806ac6c6faef17ae5L373)? I was occasionally seeing the NPE too.

**Comment by taconaut** [comment]
@skeptical Hmm wondering if I mixed up logs. With the current master (6ef190a92ded63d2c91aceb8d6fc0bd5d6aaa860) I see following:

```
05-05 14:47:21  java.lang.NullPointerException
05-05 14:47:21  	at net.pms.newgui.StatusTab$RendererItem.<init>(StatusTab.java:69)
05-05 14:47:21  	at net.pms.newgui.StatusTab.addRenderer(StatusTab.java:332)
05-05 14:47:21  	at net.pms.newgui.LooksFrame.addRenderer(LooksFrame.java:559)
05-05 14:47:21  	at net.pms.PMS.setRendererFound(PMS.java:180)
05-05 14:47:21  	at net.pms.network.UPNPHelper.rendererFound(UPNPHelper.java:661)
05-05 14:47:21  	at net.pms.network.UPNPControl.addRenderer(UPNPControl.java:471)
05-05 14:47:21  	at net.pms.network.UPNPControl$2.remoteDeviceAdded(UPNPControl.java:292)
05-05 14:47:21  	at org.fourthline.cling.registry.RemoteItems$1.run(RemoteItems.java:111)
05-05 14:47:21  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
05-05 14:47:21  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
05-05 14:47:21  	at java.lang.Thread.run(Thread.java:745)
```

The other logs came from 5.1.0

**Comment by skeptical** [comment]
@taconaut seems like your device ```icon``` is somehow ending up ```null```.  Are either one of these logged prior to the exception?
```logtalk
DEBUG 08:49:09.195 [cling-36] Device icon: http://192.168.1.8:54199/icon120x120.png
```
```logtalk
DEBUG 08:49:09.195 [cling-36] Failed to read icon url: ...
```

**Comment by taconaut** [comment]
Nope,

Checking the debug log, I've got some more infos:

```
DEBUG 15:49:36.988 [cling-5] Reading MediaInfo: true (default: false)
DEBUG 15:49:36.989 [cling-5] Marking upnp renderer "Philippe's hue (192.168.1.101)" at /192.168.1.101 as unrecognized
DEBUG 15:49:36.989 [cling-5] Adding status button for Philippe's hue (192.168.1.101)
DEBUG 15:49:36.989 [cling-5] Device icon: http://192.168.1.101:80/hue_logo_3.png
DEBUG 15:49:37.001 [cling-5] Error initializing device Philippe's hue (192.168.1.101): java.lang.NullPointerException
INFO  15:49:37.002 [cling-5] java.lang.NullPointerException
INFO  15:49:37.005 [cling-5] 	at net.pms.newgui.StatusTab$RendererItem.<init>(StatusTab.java:69)
INFO  15:49:37.008 [cling-5] 	at net.pms.newgui.StatusTab.addRenderer(StatusTab.java:332)
INFO  15:49:37.015 [cling-5] 	at net.pms.newgui.LooksFrame.addRenderer(LooksFrame.java:559)
DEBUG 15:49:37.019 [cling-12] Renewing subscriptions to 
INFO  15:49:37.020 [cling-5] 	at net.pms.PMS.setRendererFound(PMS.java:180)
INFO  15:49:37.023 [cling-5] 	at net.pms.network.UPNPHelper.rendererFound(UPNPHelper.java:661)
INFO  15:49:37.023 [cling-5] 	at net.pms.network.UPNPControl.addRenderer(UPNPControl.java:471)
INFO  15:49:37.025 [cling-5] 	at net.pms.network.UPNPControl$2.remoteDeviceAdded(UPNPControl.java:292)
INFO  15:49:37.029 [cling-5] 	at org.fourthline.cling.registry.RemoteItems$1.run(RemoteItems.java:111)
INFO  15:49:37.031 [cling-5] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO  15:49:37.032 [cling-5] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO  15:49:37.035 [cling-5] 	at java.lang.Thread.run(Unknown Source)
DEBUG 15:49:37.037 [cling-5] Ignoring device: Basic (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:2f402f80-da50-11e1-9b23-00178809f755, Descriptor: http://192.168.1.101:80/description.xml, Root: true
```

Opening `http://192.168.1.101:80/hue_logo_3.png` in a browser displays the logo.

**Comment by skeptical** [comment]
@taconaut I added some logging to show whether we're actually fetching the icon (f1b442e), see if it shows anything useful.

**Comment by taconaut** [comment]
@skeptical There's no exception, only the message 'unable to read icon url...'. And no NPE anymore :)

**Comment by skeptical** [comment]
@taconaut then it probably means [no registered ImageReader claims to be able to read the png](http://docs.oracle.com/javase/7/docs/api/javax/imageio/ImageIO.html#read(java.net.URL)) and we got a null ```BufferedImage```.

**Comment by taconaut** [comment]
@skeptical The weird part is that it worked before. Anyway, it's not a biggie as the hue bridge isn't a real renderer anyway. Cheers

**Comment by skeptical** [comment]
yeah, moot but highlighted a potential bug :). Maybe the png in the new firmware is different.
