### ISSUE TITLE
A serious error occurred during PMS init

### ISSUE THREAD

**Issue by LMY** [UniversalMediaServer/UniversalMediaServer#577]
06-20 17:42:40  A serious error occurred during PMS init
java.lang.NullPointerException: null
	at net.pms.util.FileUtil.getExtension(FileUtil.java:161) ~[ums.jar:5.1.4]
	at net.pms.util.FileUtil.getUrlExtension(FileUtil.java:157) ~[ums.jar:5.1.4]
	at net.pms.dlna.PlaylistFolder.getPlaylist(PlaylistFolder.java:225) ~[ums.jar:5.1.4]
	at net.pms.dlna.RootFolder.addWebFolder(RootFolder.java:388) ~[ums.jar:5.1.4]
	at net.pms.dlna.RootFolder.loadWebConf(RootFolder.java:332) ~[ums.jar:5.1.4]
	at net.pms.dlna.RootFolder.discoverChildren(RootFolder.java:154) ~[ums.jar:5.1.4]
	at net.pms.configuration.RendererConfiguration.getRootFolder(RendererConfiguration.java:446) ~[ums.jar:5.1.4]
	at net.pms.PMS.getRootFolder(PMS.java:131) [ums.jar:5.1.4]
	at net.pms.PMS.init(PMS.java:728) [ums.jar:5.1.4]
	at net.pms.PMS.createInstance(PMS.java:1062) [ums.jar:5.1.4]
	at net.pms.PMS.main(PMS.java:1177) [ums.jar:5.1.4]

**Comment by LMY** [comment]
cause of this error, lines in Web.conf such as:

audiostream.Web,Digitally Imported,Ambient=http://pub7.di.fm/di_ambient
audiostream.Web,Digitally Imported,Big Room House=http://pub7.di.fm/di_bigroomhouse
audiostream.Web,Digitally Imported,Breaks=http://pub7.di.fm/di_breaks
audiostream.Web,Digitally Imported,Chillpop=http://pub7.di.fm/di_chillhop

**Comment by valib** [comment]
@LMY why do you set audiostream when it could be audiofeed?

**Comment by valib** [comment]
@LMY sorry, I checked the source code and the audiostream can be used and it sems to be a real bug.

**Comment by Sami32** [comment]
@LMY You need to format your "audiostream" line as below:
audiostream,web,DI Radio=Big Room House,http://pub3.di.fm:80/di_bigroomhouse
audiostream,web,DI Radio=Ambient,http://pub6.di.fm:80/di_ambient

That's said this error need not being there. Thanks for reporting that :+1: 
```
public static String getExtension(String f) {
		int point = f.lastIndexOf('.');

		if (point == -1) {
			return null;
		}

		return f.substring(point + 1);
	}
```
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/util/FileUtil.java#L229-L237

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/599

**Comment by ik666** [comment]
@SubJunk Same as #599. Should work now.
