### ISSUE TITLE
Failed to resume movie with 3D subtitle

### ISSUE THREAD

**Issue by adipiciu** [UniversalMediaServer/UniversalMediaServer#587]
The Panasonic as650 failed to resume the movie if it has 3D subtitle in idx format. The movie just exits. If the subtitle is 2D or no subtitle at all in the folder, the resume function works fine.

DEBUG 20:47:44.280 [ffmpeg64.exe-3-2]   Duration: N/A, bitrate: N/A
DEBUG 20:47:44.280 [ffmpeg64.exe-3-2]     Stream #1:0[0x0](ro): Subtitle: dvd_subtitle, 1920x1080 (default)
DEBUG 20:47:44.281 [ffmpeg64.exe-3-2] [AVFilterGraph @ 0000000004c3e1c0] Too many inputs specified for the "overlay" filter.
DEBUG 20:47:44.281 [ffmpeg64.exe-3-2] Error configuring filters.
TRACE 20:47:44.768 [nioEventLoopGroup-3-9] Did not send subtitle headers because mediaRenderer.getSubtitleHttpHeader returned either null or blank
..........
TRACE 20:47:45.290 [ffmpeg64.exe-3] EOF
INFO  20:47:45.290 [ffmpeg64.exe-3] Process C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe has a return code of 1! Maybe an error occurred... check the log file

**Comment by valib** [comment]
@adipiciu info you provided says nothig. Only that there is something wrong The full log is needed.

**Comment by Sami32** [comment]
@adipiciu Did the latest UMS version solved this issue ?

If not, please, post your log following these steps:
http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=556

As told, we need your full trace log to understand why this error was throwed; as for now we don't see the command line passed and your configuration parameters.

**Comment by adipiciu** [comment]
@Sami32 I stopped using UMS. The logs were provided here a long time ago, but no response:
[(http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3617&hilit=Failed+to+resume+movie+with+3D+subtitle)]

**Comment by Sami32** [comment]
@adipiciu Thanks for the link and feedback :-)

Sorry to learn that, but perhaps your log was just missed because not linked to this issue...because i think that @valib would have looked at it if it was attached here.

Lot of commits was done since then for 3D subtitles https://github.com/UniversalMediaServer/UniversalMediaServer/commit/b3d9f3cee4490ddc0aafedee752479762e56725b https://github.com/UniversalMediaServer/UniversalMediaServer/commit/4981ec19e4995143709e44a51e281c71c4299fb9 https://github.com/UniversalMediaServer/UniversalMediaServer/commit/60754ba2e6cd8c8265b5c5c824532bad9344b44e https://github.com/UniversalMediaServer/UniversalMediaServer/commit/5a4ea38744867f2ac4430b091699dd1dadb0aafe https://github.com/UniversalMediaServer/UniversalMediaServer/commit/8510c971f29ae0cae72b1e5ad1bd6eb033d87959

Hoping see you again ;-)
You feelback is welcome, but don't forget to attach your log on Github :wink: 

**P.S.**
> Failed to resume the movie if it has external 3D subtitle in idx format. The movie just exits. If the subtitle is 2D (.srt) or no subtitle at all in the folder, the resume function works fine.
> The movie plays ok from the beginning with 3D subtitle, but if I stop, then resume or when I seek forward, the movie just exits with no errors. I have attached the log files.

`-filter_complex setpts=PTS+1790.0/TB,[0:v][1:s]overlay,setpts=PTS-STARTPTS`
> DEBUG 13:54:35.290 [ffmpeg64.exe-3-2] [AVFilterGraph @ 000000000477f760] Too many inputs specified for the "overlay" filter.
> DEBUG 13:54:35.290 [ffmpeg64.exe-3-2] Error configuring filters.

...

> TRACE 13:54:19.924 [nioEventLoopGroup-3-8]   getCause: 
> java.io.IOException: An established connection was aborted by the software in your host machine
> 	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_45]
> 	at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_45]
> 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_45]
> 	at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_45]
> 	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_45]
> 	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:287) ~[ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:761) ~[ums.jar:5.1.4]
> 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:311) ~[ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:729) ~[ums.jar:5.1.4]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1127) ~[ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644) [ums.jar:5.1.4]
> 	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[ums.jar:5.1.4]
> 	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:197) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644) [ums.jar:5.1.4]
> 	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:311) ~[ums.jar:5.1.4]
> 	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:139) ~[ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:693) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:716) [ums.jar:5.1.4]
> 	at net.pms.network.RequestV2.answer(RequestV2.java:902) ~[ums.jar:5.1.4]
> 	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:296) [ums.jar:5.1.4]
> 	at net.pms.network.RequestHandlerV2.channelRead0(RequestHandlerV2.java:252) [ums.jar:5.1.4]
> 	at net.pms.network.RequestHandlerV2.channelRead0(RequestHandlerV2.java:47) [ums.jar:5.1.4]
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [ums.jar:5.1.4]
> 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [ums.jar:5.1.4]
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [ums.jar:5.1.4]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [ums.jar:5.1.4]
> 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [ums.jar:5.1.4]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [ums.jar:5.1.4]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [ums.jar:5.1.4]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [ums.jar:5.1.4]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [ums.jar:5.1.4]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [ums.jar:5.1.4]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [ums.jar:5.1.4]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [ums.jar:5.1.4]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [ums.jar:5.1.4]
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [ums.jar:5.1.4]
> 	at java.lang.Thread.run(Unknown Source) [na:1.8.0_45]

...

> TRACE 13:54:19.984 [nioEventLoopGroup-3-10] The channel future completed:
> TRACE 13:54:19.984 [nioEventLoopGroup-3-10]   isSuccess: false
> TRACE 13:54:19.984 [nioEventLoopGroup-3-10]   isCancelled: false
> TRACE 13:54:19.984 [nioEventLoopGroup-3-10]   getCause: 
> java.nio.channels.ClosedChannelException: null

**Comment by paulene-c** [comment]
Possibly the same issue as https://github.com/UniversalMediaServer/UniversalMediaServer/issues/659

**Comment by SubJunk** [comment]
This went stale
