### ISSUE TITLE
Netty 4 breaks direct streaming on Sony-Bluray

### ISSUE THREAD

**Issue by skeptical** [UniversalMediaServer/UniversalMediaServer#598]
I noticed yesterday that my (no longer used much for DLNA) Sony BDP-370 was giving a 'corrupt' error for any _streamed_ content (though transcoded stuff plays ok) and tracked the bug to 40d44a7, then verified by switching current code to netty 3 which solved the issue. Some notes:
- The quick fix, of course, is to set `http_engine_v2 = false`.
- This is a `ChunkedTransfer` renderer, so I'm wondering if anyone has noticed anything similar with other chunked renderers and http engine v2?
- I've tinkered with our netty4 implementation after studying the [netty3 rollback diff](https://gist.github.com/skeptical/b573b30889f2fe5cf262) for clues, but no luck so far. Please comment if anything catches your eye.

**Comment by SubJunk** [comment]
@skeptical darn!

**Comment by endymion0000** [comment]
I had discovered as well that I could no longer stream mp4 files to my Sony BDP-S790 with UMS 5.1.4 through 5.2.1. UMS 5.1.3 worked ok. I could still stream mkv files though. Details in this thread: http://www.universalmediaserver.com/forum/viewtopic.php?f=13&t=3612

Disabling HTTP Engine V2 fixed this issue.

However, I still need to disable all the Video File Transcoding Engines to stream since the "Skip transcoding for the following extensions) field doesn't work at all. I have mp4,mkv there yet it always wants to transcode my mp4 files unless I disable all the engines.

**Comment by SubJunk** [comment]
@skeptical I have a consistent crash with a MP4 file on my TV, I'll apply the diff and see if it makes a diff

**Comment by SubJunk** [comment]
I think we should rollback Netty 4 until we find a way to fix this, what do you think @skeptical ?

**Comment by skeptical** [comment]
@SubJunk I suppose revert for now, I don't have time to dig deeper anytime soon (but it should be fixable I would think with a little deep diving).  The issue with Netty 3 was that the send buffer would fill and block sometimes when transcoding gigantic files, according to @mfulgo (who does a great job of explicating the issue in his posts here and at netty too).  Off the top of my head such as it is :) in Netty 3 we may be able to avoid filling/choking the buffer by waiting until there's enough free space before pushing each chunk of data.

In the long run better to solve the Netty 4 issue instead, though.

**Comment by SubJunk** [comment]
@skeptical I wonder if they have fixed that issue in the latest Netty 3 releases. There have been about 4 3.x releases since the last one we used I think.

**Comment by skeptical** [comment]
@SubJunk I browsed the recent netty3 commits 10 days ago and didn't see anything that seemed relevant to this.  @mfulgo posted a handy little test program in netty issue [#3311](https://github.com/netty/netty/issues/3311) that would definitively answer the question, though.

**Comment by SubJunk** [comment]
Hmm okay, well it sucks that there are issues with both. Can you do the Netty 3 rollback? Then we can start another Netty 4 branch

**Comment by mfulgo** [comment]
I think the underlying problem was resolved as of Netty 3.10.2: https://github.com/netty/netty/commit/452df0454d34fdd5e0022f40c20ad7c45e7f1895

That's the only commit that made changes to the AbstractNioWorker since 3.10.0, and running the test application against 3.10.2, I see that the writeSuspended flag is set to true but is properly set back to false when the native channel can write again.

**Comment by skeptical** [comment]
@mfulgo great, and thx for verifying :-), at least netty 3 is healthy.

**Comment by ExSport** [comment]
Btw. can this PR help in communication with renderer for actual position on renderer side? (not implemented in v3 and v4.0.x):
https://github.com/netty/netty/pull/3661
https://github.com/netty/netty/pull/3663
https://github.com/netty/netty/issues/3636
https://github.com/netty/netty/commit/c4d861844c8821c1810b20d890f7858f874546e8
I suppose it is very dumb question but anyway asking... :)

**Comment by Nadahar** [comment]
@skeptical @SubJunk @SharkHunter I don't know if this is related to netty, but I've spent a lot of time looking through UMS logs, and one thing I've noticed is that the renderer handling seems to log most things twice. If a renderer connects or disconnects, it's as far as I can remember always at least two identical messages or set of messages. Why is this? I even get the exceptions twice from the same thread. I honestly don't understand how that's even possible. Is there something strange going on, or does this have a logical explanation?

I've also noticed that after the rollback to v3 the exceptions that's thrown every time a renderer disconnects, is much longer. I don't remember exactly how they looked with v4, but here's an example from my current log:
```
java.io.IOException: En eksisterende tilkobling ble tvangslukket av den eksterne verten
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.7.0_80]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51) ~[na:1.7.0_80]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.7.0_80]
	at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[na:1.7.0_80]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:492) ~[na:1.7.0_80]
	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203) ~[netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:146) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:725) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:280) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:121) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:704) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.write(Channels.java:671) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:348) [netty-3.10.4.Final.jar:na]
	at net.pms.network.RequestHandlerV2.sendError(RequestHandlerV2.java:348) [classes/:na]
	at net.pms.network.RequestHandlerV2.exceptionCaught(RequestHandlerV2.java:334) [classes/:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.exceptionCaught(SimpleChannelUpstreamHandler.java:153) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:74) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.4.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.4.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
```
That's one seriously long stacktrace, but that might be fine - but I don't remember them being like this in v4. It could just be that v4 didn't print the stacktrace?

Anyway, the strange thing is that these come in shortly after eachother from the same thread. Watch the milliseconds in the timestamps (I'm omitting the strack traces to make it readable):
```
02:46:30.232 [New I/O worker #1] DEBUG net.pms.network.RequestHandlerV2 - Connection error: java.io.IOException: En eksisterende tilkobling ble tvangslukket av den eksterne verten
02:46:30.232 [New I/O worker #1] DEBUG net.pms.network.RequestHandlerV2 - Premature end, stopping...
02:46:30.234 [New I/O worker #1] TRACE net.pms.network.RequestHandlerV2 - Caught exception
02:46:30.234 [New I/O worker #1] DEBUG net.pms.network.RequestHandlerV2 - Connection error: java.io.IOException: En eksisterende tilkobling ble tvangslukket av den eksterne verten
02:46:30.234 [New I/O worker #1] DEBUG net.pms.network.RequestHandlerV2 - Premature end, stopping...
02:46:30.237 [New I/O worker #1] TRACE net.pms.network.RequestHandlerV2 - Caught exception
```
The norwegian text simply means: "An existing connection was forcibly closed by the remote host"

A typical renderer connect looks like this (I'm using MediaMonkey and foobar2000 as software renderers while testing):
```
02:04:12.976 [New I/O worker #16] DEBUG n.p.c.RendererConfiguration - Matched media renderer "MediaMonkey" based on address /10.72.64.11
02:04:13.028 [New I/O worker #17] DEBUG n.p.c.RendererConfiguration - Matched media renderer "MediaMonkey" based on address /10.72.64.11
02:04:13.781 [New I/O worker #18] DEBUG n.p.c.RendererConfiguration - Matched media renderer "MediaMonkey" based on address /10.72.64.11
02:04:13.837 [New I/O worker #19] DEBUG n.p.c.RendererConfiguration - Matched media renderer "MediaMonkey" based on address /10.72.64.11
```
These are different threads, but why does 4 threads pick up what I assume to be the same discovery signal?

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/942

**Comment by SubJunk** [comment]
@Sami32 good find. We should make sure this is tested again before the 7.0.0 release

**Comment by Sami32** [comment]
@SubJunk I agree with that.
Good to know that trying reviewing all these issues are not only giving me headaches :-D

**Comment by atamariya** [comment]
In Netty 4 chunked transfer mode, it's required to to signal the end of content by EMPTY_LAST_CONTENT.

`ctx.write(LastHttpContent.EMPTY_LAST_CONTENT);`

**Comment by SubJunk** [comment]
@atamariya great catch, I'm really looking forward to getting your improvements merged :)

**Comment by SubJunk** [comment]
No longer relevant because we reverted Netty 4
