### ISSUE TITLE
Possible web audio issue

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#599]
Mentioned at http://www.universalmediaserver.com/forum/viewtopic.php?p=17159&sid=ca7462bd12c11c9ca8b1691d0c2cf9e7#p17168

**Comment by Nadahar** [comment]
@SubJunk I'm a bit confused - what exactly does "web audio" mean? Does it means to stream or transcode audio via a web browser (port 9001)? That's working perfectly for me at least with Firefox, both streaming and transcoding.

**Comment by jmollys** [comment]
Nadahar, 
I hope this helps explain the issue.  UMS works perfectly streaming web audio to PS3.  It is a no go for the PS4.
I listen to di.fm.  I have extracted the web audio URLs from the channels I enjoy and placed them in the web config file of UMS. The audio format used by di.fm is MP3.

So I stream the web audio to my laptop through the web config file via UMS then it is sent to the renderer (ps3/ps4). I can do this without a web browser being used. I just need UMS running.

Below is one of the URLs @ 96kbs:
audiostream.Web,DI Radio=Trance,http://pub6.di.fm:80/di_trance

Thanks,

jMollys

**Comment by Sami32** [comment]
@jmollys Did the renderer configuration improvements commited by @SubJunk since then have solved this issue ?

@atamariya Sorry to ask you that, but as you're the only one that i know owning a PS4 ;-)
Could you confirm that issue ?

**Comment by atamariya** [comment]
@Sami32 Nah, I don't PS4 - just xbox 360.

**Comment by Sami32** [comment]
@atamariya Oups...my bad ;-)

**Comment by Sami32** [comment]
> 00:06:57 TRACE Could not match any format to ".fm:80/di_trance"
> 00:06:57 DEBUG dumping media audio/mpeg WebAudioStream [id=20, name=Trance, full path=20, ext=WEB, discovered=false]
> 00:06:57 TRACE Asked stream chunk : ByteRange [start=0, end=9223372034707292159] of Trance and player null
> 00:06:57 TRACE Setting lastStartPosition from time-seeking: 0.0
> 00:06:57 DEBUG file req /files/menu-background-content.png
> 00:06:57 DEBUG Using resource: file:web/menu-background-content.png
> 00:06:57 DEBUG file req /files/menu-left-content.png
> 00:06:57 DEBUG Using resource: file:web/menu-left-content.png
> 00:06:57 INFO  Started playing Trance on your Firefox
> 00:06:57 DEBUG The full filename of which is: http://pub6.di.fm:80/di_trance and the address of the renderer is: 192.168.1.28
> 00:06:58 DEBUG file req /files/settings32.png
> 00:06:58 DEBUG Using resource: file:web/settings32.png
> 00:06:58 DEBUG file req /files/download.png
> 00:06:58 DEBUG Using resource: file:web/download.png
> 00:06:58 INFO  Exception in thread "Thread-101" java.lang.NullPointerException
> 00:06:58 INFO  	at net.pms.remote.RemoteUtil$1.run(RemoteUtil.java:105)
> 00:06:58 INFO  	at java.lang.Thread.run(Unknown Source)

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/remote/RemoteUtil.java#L103-L108
```
				} finally {
					try {
						in.close();
					} catch (IOException e) {
					}
				}
```

**Comment by ik666** [comment]
@SubJunk I believe audio web streams are working by now. We even have a native DI.FM (Audio Addict) support integrated.

**Comment by SubJunk** [comment]
So cool!
