### ISSUE TITLE
Error in Eclipse caused by git-commit-id-plugin

### ISSUE THREAD

**Issue by valib** [UniversalMediaServer/UniversalMediaServer#627]
I realized that after some Eclipse updates there is an error when I run UMS from Eclipse.
```java
INFO] --- git-commit-id-plugin:2.1.15:revision (default) @ ums ---
[ERROR] Caught exception in FS.readPipe()
java.io.IOException: Cannot run program "bash" (in directory "C:\Documents and Settings\Valal"): CreateProcess error=2, System cannot find the file
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.eclipse.jgit.util.FS.readPipe(FS.java:431)
	at org.eclipse.jgit.util.FS_Win32.discoverGitPrefix(FS_Win32.java:113)
	at org.eclipse.jgit.util.FS.gitPrefix(FS.java:517)
	at org.eclipse.jgit.util.SystemReader$Default.openSystemConfig(SystemReader.java:92)
	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:171)
	at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92)
	at pl.project13.maven.git.JGitProvider.getGitRepository(JGitProvider.java:265)
	at pl.project13.maven.git.JGitProvider.init(JGitProvider.java:79)
	at pl.project13.maven.git.GitDataProvider.loadGitData(GitDataProvider.java:91)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitDataWithJGit(GitCommitIdMojo.java:585)
	at pl.project13.maven.git.GitCommitIdMojo.loadGitData(GitCommitIdMojo.java:558)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:376)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:364)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: CreateProcess error=2, System cannot find the file
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 38 more
```
This is caused by git-commit-id-plugin and after testing I found that the last vorking version is 2.1.13 Tested on two PCs with the same result. One OS WIN XP second OS WIN 10 and two different Eclipse version (Luna and Mars). Does anybody else have the same problem?

**Comment by Nadahar** [comment]
I haven't noticed any problem, and I don't know if this is related, but a snippet from https://github.com/ktoso/maven-git-commit-id-plugin/issues/213 states (in the 3. post):
> version 2.1.13 as 14 and 15 aren't compatible with maven 3.0.5.

Could that have anything to do with the problem?

The error itself is quite simple, it can't run bash. Do you use JGit? There's a similar problem reported [here] (https://www.eclipse.org/forums/index.php/t/1031740/) but it's supposed to be fixed by https://github.com/eclipse/jgit/commit/ec6ec3b10fb1ef8dd73a499d0b1f7a7d711b84dd

**Comment by TheSnoozer** [comment]
@Nadahar:
I would like to note that the 3. post in this thread is from another user that uses the git-commit-id-plugin....I'm a Collaborator for this project...only trust on infos that are in the readme.

This issue is related to https://github.com/ktoso/maven-git-commit-id-plugin/issues/203
I'll get in touch with the project owner to get the latest version shipped.

**Comment by Nadahar** [comment]
@TheSnoozer Thank you for pointing out the correct issue.

@valib As a workaround until git-commit-id-plugin 2.2.0 is released, it should work if you make sure that the git bash executable is in your ```PATH``` as far as I can understand.

**Comment by valib** [comment]
Thanks @Nadahar the workaround works.
