### ISSUE TITLE
maven failed to resolve dependencies

### ISSUE THREAD

**Issue by trippleflux** [UniversalMediaServer/UniversalMediaServer#667]
I am on Windows XP Pro x64 SP2 running java jdk 1.7 update 80, and maven 3.3.3 when trying to resolve maven dependencies using "mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external" failed with this following error :
```
C:\Documents and Settings\Administrator\My Documents\Works\Compiling\UniversalMe
diaServer>mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve
-external -X
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T18:57:3
7+07:00)
Maven home: C:\Documents and Settings\Administrator\My Documents\Tools\apache-ma
ven-3.3.3
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.7.0_80\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows xp", version: "5.2", arch: "x86", family: "windows"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.cor
e
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < p
lexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.cor
e
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from C:\Documents and Settings\Administrator\My
Documents\Tools\apache-maven-3.3.3\conf\settings.xml
[DEBUG] Reading user settings from C:\Documents and Settings\Administrator\.m2\s
ettings.xml
[DEBUG] Reading global toolchains from C:\Documents and Settings\Administrator\M
y Documents\Tools\apache-maven-3.3.3\conf\toolchains.xml
[DEBUG] Reading user toolchains from C:\Documents and Settings\Administrator\.m2
\toolchains.xml
[DEBUG] Using local repository at C:\Documents and Settings\Administrator\.m2\re
pository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for C:\D
ocuments and Settings\Administrator\.m2\repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project net.pms:ums:jar:5.2.3-SNAPSHOT: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.co
re, parent: null]
[WARNING] The POM for com.savage7.maven.plugins:maven-external-dependency-plugin
:jar:0.5 is invalid, transitive dependencies (if any) will not be available: 4 p
roblems were encountered while building the effective model for ::
[ERROR] 'modelVersion' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[u
nknown-version]
[ERROR] 'groupId' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unknow
n-version]
[ERROR] 'artifactId' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unk
nown-version]
[ERROR] 'version' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unknow
n-version]

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.125 s
[INFO] Finished at: 2015-09-08T11:24:18+07:00
[INFO] Final Memory: 4M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin com.savage7.maven.plugins:maven-external-dependency-plugin:0.5 or
 one of its dependencies could not be resolved: Failed to read artifact descript
or for com.savage7.maven.plugins:maven-external-dependency-plugin:jar:0.5: 4 pro
blems were encountered while building the effective model for ::
[ERROR] [ERROR] 'modelVersion' is missing. @ [unknown-group-id]:[unknown-artifac
t-id]:[unknown-version]
[ERROR] [ERROR] 'groupId' is missing. @ [unknown-group-id]:[unknown-artifact-id]
:[unknown-version]
[ERROR] [ERROR] 'artifactId' is missing. @ [unknown-group-id]:[unknown-artifact-
id]:[unknown-version]
[ERROR] [ERROR] 'version' is missing. @ [unknown-group-id]:[unknown-artifact-id]
:[unknown-version]
[ERROR] -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin com.savage7.maven.plug
ins:maven-external-dependency-plugin:0.5 or one of its dependencies could not be
 resolved: Failed to read artifact descriptor for com.savage7.maven.plugins:mave
n-external-dependency-plugin:jar:0.5
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.re
solve(DefaultPluginDependenciesResolver.java:117)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginD
escriptor(DefaultMavenPluginManager.java:179)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDes
criptor(DefaultMavenPluginManager.java:298)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(D
efaultBuildPluginManager.java:241)
        at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDesc
riptor(MojoDescriptorCreator.java:239)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalcul
ator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:103)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalcul
ator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:83)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:89)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to
read artifact descriptor for com.savage7.maven.plugins:maven-external-dependency
-plugin:jar:0.5
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.
loadPom(DefaultArtifactDescriptorReader.java:358)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.
readArtifactDescriptor(DefaultArtifactDescriptorReader.java:218)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifact
Descriptor(DefaultRepositorySystem.java:287)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.re
solve(DefaultPluginDependenciesResolver.java:103)
        ... 21 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 4 problems we
re encountered while building the effective model for ::
[ERROR] 'modelVersion' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[u
nknown-version]
[ERROR] 'groupId' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unknow
n-version]
[ERROR] 'artifactId' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unk
nown-version]
[ERROR] 'version' is missing. @ [unknown-group-id]:[unknown-artifact-id]:[unknow
n-version]

        at org.apache.maven.model.building.DefaultModelProblemCollector.newModel
BuildingException(DefaultModelProblemCollector.java:197)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultMode
lBuilder.java:475)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultMode
lBuilder.java:417)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultMode
lBuilder.java:407)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.
loadPom(DefaultArtifactDescriptorReader.java:340)
        ... 24 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResoluti
onException
```
Before i don't have this kind of problems, any ideas on how to fix it?

**Comment by Nadahar** [comment]
@trippleflux I just tried this myself and my output matches your until the line
```
[WARNING] The POM for com.savage7.maven.plugins:maven-external-dependency-plugin
:jar:0.5 is invalid, transitive dependencies (if any) will not be available: 4 p
roblems were encountered while building the effective model for ::
```
Where mine instead says:
```
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: net.pms:ums:jar:5.2.3-SNAPSHOT
[DEBUG] Tasks:   [com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Universal Media Server 5.2.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
```
...and then carries on and succeeds.

I would try to pull the files again, in case some of your files are corrupt.

**Comment by Sami32** [comment]
@trippleflux Did you solved this issue already ?

I'm not able to reproduce it on Windows XP SP3 32-bit.

**Comment by Sami32** [comment]
@trippleflux Did you solved this issue already ?

I'm not able to reproduce it on Windows XP SP3 32-bit.
Feel free to reopen it if necessary.
