### ISSUE TITLE
ffmpeg64 missing on Archlinux 64bit - bin file simply named ffmpeg

### ISSUE THREAD

**Issue by Oxalin** [UniversalMediaServer/UniversalMediaServer#718]
While debugging a stability problem between UMS 5.3.0 and a Samsung bd-d5100, where UMS would simply die, I went on building UMS 5.3.1 snapshot. Looking at the log reveals an error where UMS is trying to use ffmpeg64. However, even on 64bit Linux version, there is no "ffmpeg64".

I'm using Archlinux 64bit
ffmpeg is simply called ffmpeg and not ffmpeg64
I'm using jre8-openJDK (not Oracle Java version)

Adding a symlink named ffmpeg64 linked to ffmpeg solves the error. After looking at it, it seems even Ubuntu doesn't name the ffmpeg binary "ffmpeg64" on its 64bit arch (http://packages.ubuntu.com/vivid/amd64/ffmpeg/filelist). I may be wrong here, but I think it is named ffmpeg64 (namely ffmpeg64.exe) only on Windows.

Here is the error from the log:
------
19:42:46 DEBUG Starting ffmpeg64 -ss 4 -i /run/media/ademers/XCHANGE/Downloads/Videos/Series/Stargate Atlantis/Season 1/Stargate Atlantis Season 01 Episode 20 - The Siege (Part 2).avi -an -an -vf scale='if(gt(a,1.78),320,-1)':'if(gt(a,1.78),-1,180)', pad=320:180:(320-iw)/2:(180-ih)/2 -vframes 1 -f image2 pipe:
19:42:46 ERROR Error initializing process: 
java.io.IOException: Cannot run program "ffmpeg64": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_65]
	at net.pms.io.ProcessWrapperImpl.run(ProcessWrapperImpl.java:163) [classes/:na]
	at net.pms.io.ProcessWrapperImpl.runInSameThread(ProcessWrapperImpl.java:284) [classes/:na]
	at net.pms.dlna.DLNAMediaInfo.getFFmpegThumbnail(DLNAMediaInfo.java:599) [classes/:na]
	at net.pms.dlna.DLNAMediaInfo.parse(DLNAMediaInfo.java:879) [classes/:na]
	at net.pms.dlna.DLNAMediaInfo.generateThumbnail(DLNAMediaInfo.java:511) [classes/:na]
	at net.pms.dlna.DLNAResource.checkThumbnail(DLNAResource.java:3081) [classes/:na]
	at net.pms.dlna.RealFile.checkThumbnail(RealFile.java:287) [classes/:na]
	at net.pms.network.RequestV2.answer(RequestV2.java:315) [classes/:na]
	at net.pms.network.RequestHandlerV2.writeResponse(RequestHandlerV2.java:300) [classes/:na]
	at net.pms.network.RequestHandlerV2.messageReceived(RequestHandlerV2.java:256) [classes/:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:142) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.5.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[na:1.8.0_65]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248) ~[na:1.8.0_65]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[na:1.8.0_65]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_65]
	... 39 common frames omitted

**Comment by SubJunk** [comment]
Applied in https://github.com/UniversalMediaServer/UniversalMediaServer/commit/61d1081d81a13bb8f64bd0a68b34c92c4b1f1331

Thanks!
