### ISSUE TITLE
connection problem java

### ISSUE THREAD

**Issue by themadzman** [UniversalMediaServer/UniversalMediaServer#728]
java.net.SocketException: error setting options
at java.net.TwoStacksPlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
at java.net.AbstractPlainDatagramSocketImpl.join(Unknown Source) ~[na:1.8.0_65]
at java.net.MulticastSocket.joinGroup(Unknown Source) ~[na:1.8.0_65]
at net.pms.network.UPNPHelper$2.run(UPNPHelper.java:426) ~[ums.jar:5.3.0]
at java.lang.Thread.run(Unknown Source) [na:1.8.0_65]

the  ums_dbg.zip
http://www.universalmediaserver.com/forum/download/file.php?id=2786

**Comment by Nadahar** [comment]
@themadzman An explanation of when the problem occurs, your network setup or any other relevant information would help.

**Comment by themadzman** [comment]
windows 7 professional n connected directly to the router running java 8 update 25 running UMS-5.3.0-Java7 tested a couple of different versions of java no dice.Universal Media Server fresh install no settings touched

**Comment by SubJunk** [comment]
This is likely fixed now because our connection code is very different
