### ISSUE TITLE
Can't properly start UMS on headless Debian with Systemd

### ISSUE THREAD

**Issue by DavidGangel** [UniversalMediaServer/UniversalMediaServer#734]
Hi,

I try to start UMS as a daemon on Debian Jessie. When the machine is started or rebooted I always get the below exceptions. I'm using SSH to access the machine so the network is already up when this error is coming. When I stop the service and start manually the error does not occurs.

Debian:
```
  Operating System: Debian GNU/Linux 8 (jessie)
  Kernel: Linux 3.16.0-4-amd64
  Architecture: x86-64
```

Java:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

ums.service:
```
[Unit]
Description=Universal Media Server
Wants=network.target
After=network-online.target

[Service]
Type=simple
Environment="UMS_PROFILE=/etc/ums/UMS.conf"
User=ums
Group=ums
WorkingDirectory=/opt/ums
ExecStart=/opt/ums/UMS.sh

[Install]
WantedBy=multi-user.target
```

Error:
```
DEBUG 2015-11-18 08:52:42.251 [main] Reading external_network: false (default: true)
DEBUG 2015-11-18 08:52:42.252 [main] Sending ALIVE...
DEBUG 2015-11-18 08:52:42.266 [main] Error sending ALIVE message
java.io.IOException: No usable network interface found for UPnP multicast
        at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:248) ~[ums.jar:5.3.0]
        at net.pms.network.UPNPHelper.sendAlive(UPNPHelper.java:192) ~[ums.jar:5.3.0]
        at net.pms.PMS.init(PMS.java:767) [ums.jar:5.3.0]
        at net.pms.PMS.createInstance(PMS.java:1028) [ums.jar:5.3.0]
        at net.pms.PMS.main(PMS.java:1177) [ums.jar:5.3.0]
INFO  2015-11-18 08:52:42.521 [main] The server is now available for renderers to find
ERROR 2015-11-18 08:52:42.527 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
DEBUG 2015-11-18 08:52:43.428 [mplayer-0-Cleanup] Stopping Unix process 892: mplayer-0
ERROR 2015-11-18 08:52:43.535 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
ERROR 2015-11-18 08:52:44.538 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
ERROR 2015-11-18 08:52:45.540 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
```

**Comment by Nadahar** [comment]
@DavidGangel There must be something that isn't ready. UMS gets this information from the Java Virtual Machine so I doubt there is much we can do in UMS to remedy this. It's the aquirement of multicast address that fails, maybe that's initialized a bit later than the "core network"?

**Comment by DavidGangel** [comment]
How can I check this or how can I change the systemd service to wait for it?

Thank you.

**Comment by Nadahar** [comment]
@DavidGangel I have no idea. This is a Debian/Linux issue. I don't know what those targets represent, but if it's other services I don't have any target named ```network``` or ```network-online``` on my debian computer. I do have ```networking" service though. Maybe you should wait for that?

**Comment by DavidGangel** [comment]
That also does not change anything.
I also did try to add IP and eth0 to the ums config.
Then I have this in my debug log:
```
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
DEBUG 2015-11-18 11:31:19.070 [mplayer-0-Cleanup] Stopping Unix process 892: mplayer-0
ERROR 2015-11-18 11:31:19.209 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
ERROR 2015-11-18 11:31:20.211 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
ERROR 2015-11-18 11:31:21.214 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
ERROR 2015-11-18 11:31:22.217 [UPNPHelper] UPNP network exception
java.net.SocketException: No such device
        at java.net.PlainDatagramSocketImpl.join(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:179) ~[na:1.8.0_65]
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[na:1.8.0_65]
        at net.pms.network.UPNPHelper.lambda$listen$20(UPNPHelper.java:421) ~[ums.jar:5.3.0]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]
DEBUG 2015-11-18 11:31:28.191 [UPNP-AliveMessageSender] Sending ALIVE...
DEBUG 2015-11-18 11:31:28.195 [UPNP-AliveMessageSender] Reading uuid: "3891c7a3-6528-4515-bc3a-b2f8fe9c7443" (default: null)
INFO  2015-11-18 11:31:28.195 [UPNP-AliveMessageSender] Using the following UUID configured in UMS.conf: 3891c7a3-6528-4515-bc3a-b2f8fe9c7443
DEBUG 2015-11-18 11:31:48.199 [UPNP-AliveMessageSender] Sending ALIVE...

```

**Comment by Nadahar** [comment]
There is no way to solve this by configuring UMS, you have to get it to wait until the network is ready before starting. When you see (native method) in the stack trace, that means that the reply comes from the OS itself. It's Linux, not UMS, that says that the sockets doesn't exist.

**Comment by DavidGangel** [comment]
Ok, raised a question here:
http://forums.debian.net/viewtopic.php?f=5&t=125801

Let's see what will be the outcome.

**Comment by Nadahar** [comment]
By reading [the man page] (http://linuxmanpages.net/manpages/fedora20/man5/systemd.unit.5.html) I can see that there's several potential useful options. ```network.target``` is the correct name for network, but you also have interesting things like ```sysinit.target``` or ```.socket```. You can tell it to wait until a [specific socket] (http://linuxmanpages.net/manpages/fedora20/man5/systemd.socket.5.html) is estabilished. 

Another thing is that it's the ```after=``` part that mattes in this respect, and it seems that ```network-online.target``` is broken on Debian in that it fires as soon as the network is up but before it is fully configured. [Here] (http://unix.stackexchange.com/questions/209832/debian-systemd-network-online-target-not-working) is a proposed fix.

**Comment by DavidGangel** [comment]
I tried the solution but does not works for me. Anyway thank you for the proposal.

**Comment by Oxalin** [comment]
@DavidGangel , you may want to have a look here (http://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/) for more details. As @Nadahar said, your service is starting and trying to grab a network interface before any is ready | up (IP not attributed yet). On the other hand, that is why the problem doesn't occur when you stop and restart UMS from a ssh connection: your network interface is then "up", that is completely configured with an IP address. At that point, UMS is able to use that interface when it is restarted.

**Comment by Sami32** [comment]
@DavidGangel Did you finally find a way to make it start correctly ?

**Comment by Sami32** [comment]
> Attention! Just figured out it on a Raspbian Jessie : remove ALL commented lines in /etc/network interfaces and it will work! It seems to be a parsing bug =) In my specific case I've left commented iface eth0 inet dhcp and just forgot about it eons ago, but after upgrade to Raspbian Jessie and rebuilding a kernel I've got very odd behaviour : it used DHCP and refused to make a tuning from /etc/network/interfaces. So I've stripped it out of any comments - just working lines, reboot - and it works! NO SCRIPT PATCHING/EDITING NEEDED!
