### ISSUE TITLE
Java Exception in arch linux

### ISSUE THREAD

**Issue by basedheaven** [UniversalMediaServer/UniversalMediaServer#788]
Got this error after installing from AUR and trying to run sh /opt/ums/UMS.sh

[heaven@hp ~]$ sh /opt/ums/UMS.sh
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/pms/PMS : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by Nadahar** [comment]
@basedheaven Are you using Java 7 or later? Java 6 is no longer supported, and this error generally means that the wrong Java version is being used.

**Comment by basedheaven** [comment]
java -version returns
[heaven@hp ~]$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (Arch Linux build 7.u91_2.6.3-3-x86_64)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

**Comment by basedheaven** [comment]
Fixed! Downloaded this one instead https://aur.archlinux.org/packages/umsjava7/
Closed
