### ISSUE TITLE
Unsupported major.minor version 51.0 on Debian Wheezy

### ISSUE THREAD

**Issue by gerroon** [UniversalMediaServer/UniversalMediaServer#824]
Hi 
I am getting this error on Debian Wheezy. I am guessing that it is something to do with Java?

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/pms/PMS : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: net.pms.PMS.  Program will exit.

**Comment by Nadahar** [comment]
Wrong Java version - use Java 7 or Java 8 depending on what version of UMS you downloaded.

**Comment by SubJunk** [comment]
I sometimes get that error randomly too, very rarely, so it could be worth restarting it if you haven't

**Comment by gerroon** [comment]
I change the default to openjdk7. It seems to work. 

Do you feel like Oracle's java will have better performance? Is it worth trouble getting it?

**Comment by Nadahar** [comment]
I very much doubt it - as far as I understand openjdk and Oracle Java is pretty much the same code.

**Comment by gerroon** [comment]
@Nadahar 

Thanks for the insight. Openjdk on Debian Wheezy is  working fine with Ums so far.

thanks

**Comment by Nadahar** [comment]
@gerroon That's good to hear
