### ISSUE TITLE
Renderer's gui panel not working after UMS 5.5.0

### ISSUE THREAD

**Issue by Sami32** [UniversalMediaServer/UniversalMediaServer#880]
Hello,

sorry to first posting this report to the wrong place in the "Support General Help and Support" of your Website.
So here are the photos and logs :
![capture-5 5 0](https://cloud.githubusercontent.com/assets/18471069/14613993/fcc58c0a-0596-11e6-82dd-f0953b84c9c7.jpg)
![capture-6 2 0](https://cloud.githubusercontent.com/assets/18471069/14613991/fbd60c02-0596-11e6-9f00-f79033c88f93.jpg)

For the UMS log i am not able to upload them as ZIP as i get "Unfortunately, we don't support that file type" ???
Whatever, i post them on your website support part. I hope that will help you.

**Comment by Sami32** [comment]
I tested with latest JAVA 7u101 and JAVA 8u92, and with UMS 6.0.0a1 and i get same broken "Player Control Panel".

**Comment by Sami32** [comment]
![capture-1](https://cloud.githubusercontent.com/assets/18471069/15193874/ec549d24-17b7-11e6-9126-1fe51de22b8e.gif)

The _Unknow renderer_ is a family laptop downstair, but the _VIERA E6 Series_ and  _Panasonic TX-L32E6E_ are the same TV !
As you can see, the _Panasonic TX-L32E6E_ give a one line _Player Control panel_ when the _VIERA E6 Series_ give Java error as mentioned before.
Sometimes this kind of display can happen, so i am not sure it could help to debug the problem but just in case...i leave the debug file as well :
[http://www.universalmediaserver.com/forum/download/file.php?id=3222](url)

**Comment by valib** [comment]
@Sami32 recognition of the Panasonic TVs is a little bit tricky. They use basicly the same User-Agent header so simply disable the Panasonic TX-L32V10E if it is not in your net.

**Comment by Sami32** [comment]
@valib OK, thank you. When i don't make tests, normally disable all other drivers...but your UMS and programming skill are much better than mine so i appreciate your notice, advice :-)

About a new test run with UMS 6.3.0 and Java 1.8u92, here are the log :

14:11:14 INFO  Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: net.pms.configuration.RendererConfiguration$PlaybackTimer cannot be cast to net.pms.util.BasicPlayer$Logical
14:11:14 INFO  	at net.pms.newgui.PlayerControlPanel.<init>(PlayerControlPanel.java:41)
14:11:14 INFO  	at net.pms.newgui.RendererPanel.buildPanel(RendererPanel.java:70)
14:11:14 INFO  	at net.pms.newgui.RendererPanel.update(RendererPanel.java:264)
14:11:14 INFO  	at net.pms.newgui.StatusTab$1.lambda$actionPerformed$0(StatusTab.java:348)
14:11:14 INFO  	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
14:11:14 INFO  	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
14:11:14 INFO  	at java.awt.EventQueue.access$500(Unknown Source)
14:11:14 INFO  	at java.awt.EventQueue$3.run(Unknown Source)
14:11:14 INFO  	at java.awt.EventQueue$3.run(Unknown Source)
14:11:14 INFO  	at java.security.AccessController.doPrivileged(Native Method)
14:11:14 INFO  	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
14:11:14 INFO  	at java.awt.EventQueue.dispatchEvent(Unknown Source)
14:11:14 INFO  	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
14:11:14 INFO  	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
14:11:14 INFO  	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
14:11:14 INFO  	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
14:11:14 INFO  	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
14:11:14 INFO  	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by valib** [comment]
@Sami32 I see that you are running UMS 6.3.0 Java 8 version and Java 1.8u92 on WIN XP. Maybe this is the problem. I recommend to use the last supported Java 1.7u80 for WIN XP and the UMS 6.3.0 Java 7 version. Or try clean reinstall of Java and UMS.

**Comment by skeptical** [comment]
@valib hi there :-). The ClassCastException is due to 296a941 Viera hack in ```UPNPControl.java```, which breaks the overall player control logic.

@Sami32 out of curiosity, do the player controls (pause/play etc) in the gui actually work for your Viera in 5.5.0? Afaik @SubJunk couldn't get them to work on his Viera.

**Comment by valib** [comment]
@skeptical nice to hear you again. I started to think that only @SubJunk and me remained in this project :-)
I have also Viera TV but unfortunately due to my WiFi net configuration the UPNP support doesn't work so I've never seen such error.

**Comment by skeptical** [comment]
@valib shh... I'm not really here... :~). As I recall the wifi explanation for your missing upnp support was just a theory, have you ever tested by connecting your Viera via ethernet? Also I think you were the earliest experimenter with Cling among us, does [testing with latest cling workbench](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/761#issuecomment-208077259) now give you the same results as UMS?

**Comment by SharkHunter** [comment]
I thought I saw a ghost....It might have been my own reflection in the mirror :)

**Comment by skeptical** [comment]
hey, it's a hall of mirrors now :-).

**Comment by SharkHunter** [comment]
hehe :)

**Comment by valib** [comment]
@skeptical unfortunately I am lazy enough to wire my flat :-) Maybe I should do it for testing purpose.
The problem is that due to some restrictions in my net the Cling Workbench doesn't see my TV which can only communicate at the DLNA level. I use Cling Workbench quite often to test what is the UMS sending during browsing. For me it is much more readable than check the XML interpretation in the log :-)

**Comment by Sami32** [comment]
Hello every body, sorry for my late answers but i was testing ;-)

@valib Like i told first, i tried many UMS versions and Java versions as well and i got the same problem.
I joint you the debug log for UMS 6.3.0 and Java 1.7u80.
http://www.universalmediaserver.com/forum/download/file.php?id=3226

@skeptical You give a doubt, so i tried it and discovered that it was not streaming to the TV, so i tried so many versions of UMS...same results.
I remember when i discovered UMS some months ago, i tried the _Player Control Panel_ on a old laptop with Windows 7, die already :-( , and it was working fine.
So did it mean that not be to work with Windows XP ?

**Comment by skeptical** [comment]
@Sami32 thx for testing + logs :+1:.

You are on ethernet and your Viera's upnp services including AVT appear to be alive and well, which is a good sign :-). The exceptions in your logs are due to a separate issue which was fixed since 5.5.0, so for definitive results please test again with 6.3.0 plus this update (which should override the Viera hack and allow upnp services to be active as they were before).

Put the enclosed *update.jar* next to *ums.jar* in your UMS 6.3.0 program folder, test again and post logs (and remove the *update.jar* if it doesn't help).
[update-ums-6.3.1-SNAPSHOT-disable-viera-hack.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/265141/update-ums-6.3.1-SNAPSHOT-disable-viera-hack.zip)

**Comment by Sami32** [comment]
@skeptical You did it :-D :+1: 
Here the debug log :
http://www.universalmediaserver.com/forum/download/file.php?id=3229
Sadly i don't have any Java skill so i don't really understand what was the trick, but thank you very much for your help !
The **_Player Control Panel_ is working now**, but it doesn't stream to my TV yet, i will try adding your tip in my renderer conf and tell you back.

**Comment by skeptical** [comment]
@Sami32 as you say, no streaming, logs show errors for the AVTransport commands sent to the Viera:
```logtalk
DEBUG 2016-05-15 21:33:00.968 [AWT-EventQueue-0] Sending upnp AVTransport.SetAVTransportURI [CurrentURI, http://192.168.1.28:5001/get/27$Temp/C%3A%5CDOCUME%7E1%5CPhilippe%5CMESDOC%7E1%5CT%C3%89L%C3%89CH%7E1%5CPEAKYB%7E1.X26%5CPEAKYB%7E1.MKV, CurrentURIMetaData, <item id="27$Temp" parentID="Temp" restricted="true"><dc:title>peaky.blinders.s03e02.hdtv.x264-tla[ettv].mkv {Sub:SubRip}</dc:title><res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_OP=01" pv:subtitleFileType="SRT" pv:subtitleFileUri="http://192.168.1.28:5001/get/27$Temp/subtitle0000peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.srt" size="331326273" duration="00:58:11.00" resolution="720x388" bitrate="94895" nrAudioChannels="2" sampleFrequency="48000">http://192.168.1.28:5001/get/27$Temp/peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.mkv</res><res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_OP=01" pv:subtitleFileType="SRT" pv:subtitleFileUri="http://192.168.1.28:5001/get/27$Temp/subtitle0000peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.srt" size="331326273" duration="00:58:11.00" resolution="720x388" bitrate="94895" nrAudioChannels="2" sampleFrequency="48000">http://192.168.1.28:5001/get/27$Temp/peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.mkv</res><res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_OP=01" pv:subtitleFileType="SRT" pv:subtitleFileUri="http://192.168.1.28:5001/get/27$Temp/subtitle0000peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.srt" size="331326273" duration="00:58:11.00" resolution="720x388" bitrate="94895" nrAudioChannels="2" sampleFrequency="48000">http://192.168.1.28:5001/get/27$Temp/peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.mkv</res><res protocolInfo="http-get:*:text/srt:*">http://192.168.1.28:5001/get/27$Temp/subtitle0000peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.srt</res><upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://192.168.1.28:5001/get/27$Temp/thumbnail0000peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.mkv</upnp:albumArtURI><upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://192.168.1.28:5001/get/27$Temp/thumbnail0000peaky.blinders.s03e02.hdtv.x264-tla%5Bettv%5D.mkv</upnp:albumArtURI><upnp:class>object.item.videoItem</upnp:class></item>] to VIERA E6 Series[0]
...
DEBUG 2016-05-15 21:33:01.031 [AWT-EventQueue-0] Action failed: Error: Illegal MIME-type (HTTP response was: 500 Internal Server Error)
DEBUG 2016-05-15 21:33:01.031 [AWT-EventQueue-0] Sending upnp AVTransport.Play [Speed, 1] to VIERA E6 Series[0]
...
DEBUG 2016-05-15 21:33:01.593 [AWT-EventQueue-0] Action failed: Error: Read error (HTTP response was: 500 Internal Server Error)
```
Question: if you play something directly from the Viera instead of the control panel, does the time display under the viera icon in the status tab work correctly?

**Comment by Sami32** [comment]
@skeptical Yes, you are right, when i play movies from my TV i didn't see the time display under the VIERA E6 icon only the title pinning, only volume control work while i open the _Player Control Panel_.

When i use _Stop_ command from the _Player Control Panel_, while playing movie from my TV, it's just stop the title to pin around in the Statut bar under the _VIERA E6_ icon.
http://www.universalmediaserver.com/forum/download/file.php?id=3232

**Comment by skeptical** [comment]
@Sami32 You are able to manipulate the volume, which means the Viera's *RenderingControl* service is working ok. The problem is mainly with the Viera's *AVTransport* service and not UMS itself (same unsolved bug appears to be reported [here](https://github.com/ampache/ampache/issues/1185) too, btw). It may be possible to get the Viera to accept AVT commands by manipulating the xml data being sent from UMS via AVTransport, but it would need a programmer with access to a Viera to debug that effectively.

I don't think it would point to any easy solution, but I would be interested to see logs showing a movie being streamed from your tv for at least 30 seconds using this update (it's the same as the previous one but with more detailed logging):
[update-ums-6.3.1-SNAPSHOT-disable-viera-hack-2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/266884/update-ums-6.3.1-SNAPSHOT-disable-viera-hack-2.zip)

**Comment by Sami32** [comment]
Thanks for helping :-)

I did it, so here the LOG :
[ums_dbg_Skeptical.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/267062/ums_dbg_Skeptical.zip.txt)
If it could be useful, i joint UPnP analyse as well :
[UPNP_Analyse.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/267064/UPNP_Analyse.txt)

**Comment by skeptical** [comment]
@Sami32 Unfortunately I don't see anything really useful in the extended log either. One more independant test you can try is via cling workbench, as shown [here](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/761#issuecomment-208077259).  Download the standalone workbench jar and double-click it to start, then play a movie on your tv, and in workbench (as shown in the picture):

1. Highlight the Viera _MediaRenderer_ icon.
2. Select *AVTransport*.
3. Press *Use Service* to open up the AVTransport popup window.
4. See if there is any feedback showing from the tv as to playback, or whether any of the controls work. Try all the instance tabs (0-7) at the top.

Let me know what you find.  If there's no feedback then there's no obvious fix for us to try.

**Comment by Sami32** [comment]
@skeptical Thank you for the report, and make me discover Cling stuff ;-)

I tried but using the version 1.0.5, since the later one are not working on Windows XP...
Only the instance 0 was working, but i get no feedback, and when i used the _Play_ command from _Cling Workbench_ it making my TV displaying the default channel, so discarding my streaming movie.
The _Reward_ and _Forward_ command it make my TV on black screen, like _Remote_...

**N.B**. The Media Controller from the last _Twonky Server_ is working fine though, so i guess that your assumption made in anterior post is correct, it's something to do with UPnP/DLNA implementation. But like told @valib before, Panasonic Viera is maybe a little tricky...
I have again 5 day free Twonky trial, maybe i can try to spy a little more on their DLNA implementation...any ideas, suggestions are welcome ;-)

I don't know if theses datas will give any help but...
[CLING_WORKBENCH_1.0.5.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/269472/CLING_WORKBENCH_1.0.5.txt)

**Comment by skeptical** [comment]
@Sami32 do UMS and workbench both give you the same failures (play->default channel, ff/rew-> black screen)?  Ums uses cling, so whatever you can get to work in workbench would also be fixable in UMS. Some things to try:
- In workbench you can try copying resource uris from the twonky/ums *ContentDirectory* popup and pasting them into the Viera *AVTransport* uri box and seeing if you can get anything to play.
![selection_005](https://cloud.githubusercontent.com/assets/1594203/15366408/29dfc4fe-1cf2-11e6-97c3-c7d0bebd32d1.png)
- The first error thrown by your tv when you try to push a uri (when ```PushMetadata=true```) is '*Illegal MIME-type*'.  This could just be a coincidence, i.e. caused by xml parsing problems, or it could actually be true and maybe some files are playable depending on mimetype. Try a lot of filetypes, or see if you can spot critical differences in the mimetypes in the *Protocol Info*  between UMS and twonky for the same video.

If you enjoy headaches :-) and want to sniff AVTransport commands going to your tv from twonky (or any server),  note the Viera's descriptor port in workbench:
![cling workbench_006](https://cloud.githubusercontent.com/assets/1594203/15375096/69f724d2-1d1b-11e6-86bb-2f6d955c2752.png)
and capture the network traffic.

In [wireshark](https://www.wireshark.org/) this filter worked for me (```ip.src``` is your pc address, ```ip.dst``` is your tv address, ```tcp.port``` is the descriptor port):
```sh
(ip.src==192.168.1.7 and ip.dst==192.168.1.5 and tcp.port==60537)
```
or you can use [WinDump](https://www.winpcap.org/windump/install/default.htm) (aka  tcpdump in linux, which is what I actually used) from the command line like in the bug report I linked above (again using your correct tv port)
```sh
windump -A -s 0 'tcp port 60537 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)' > tcpdump.log
```
we are interested in SOAP data for ```AVTransport``` commands, e.g. ```SetAVTransportURI```
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
      <InstanceID>0</InstanceID>
      <CurrentURI>http://192.168.1.7:9000/disk/DLNA-PNAVC_MP4_HP_HD-OP01-FLAGS01700000/O0$3$27I60427.mp4</CurrentURI>
      <CurrentURIMetaData>&lt;DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:pv="http://www.pv.com/pvns/" xmlns:dtcp="urn:schemas-dtcp-com:metadata-1-0/" xmlns:arib="urn:schemas-arib-or-jp:elements-1-0/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:dc="http://purl.org/dc/elements/1.1/"&gt;&lt;item restricted="1" parentID="0$3$35$192" refID="0$3$27I60427" id="0$3$35$192R60427"&gt;&lt;pv:supported&gt;true&lt;/pv:supported&gt;&lt;pv:duration&gt;0:29:03&lt;/pv:duration&gt;&lt;dc:title&gt;Episode 1&lt;/dc:title&gt;&lt;dc:date&gt;2015-08-07&lt;/dc:date&gt;&lt;upnp:genre&gt;Entertainment&lt;/upnp:genre&gt;&lt;upnp:album&gt;The Great British Bake Off: An Extra Slice: Series 2&lt;/upnp:album&gt;&lt;upnp:originalTrackNumber&gt;1&lt;/upnp:originalTrackNumber&gt;&lt;dc:creator&gt;BBC Two&lt;/dc:creator&gt;&lt;upnp:albumArtURI&gt;http://192.168.1.7:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/V/O0$3$27I60427.jpg?scale=org&lt;/upnp:albumArtURI&gt;&lt;upnp:artist&gt;BBC Two&lt;/upnp:artist&gt;&lt;upnp:albumArtist&gt;BBC TV&lt;/upnp:albumArtist&gt;&lt;dc:description&gt;Jo and her panel give their take on the 12 brand new bakers and their baking attempts.&lt;/dc:description&gt;&lt;pv:modificationTime&gt;1451443395&lt;/pv:modificationTime&gt;&lt;pv:addedTime&gt;1463572530&lt;/pv:addedTime&gt;&lt;pv:extension&gt;mp4&lt;/pv:extension&gt;&lt;upnp:author role="Composer"&gt;BBC iPlayer&lt;/upnp:author&gt;&lt;upnp:artist role="Composer"&gt;BBC iPlayer&lt;/upnp:artist&gt;&lt;PersistentBookmark&gt;uuid:55076f6e-6b79-1d65-a4db-90e6baa50bc6,-L2cvdmlkL2diYi9ULkcuQnJpdGlzaC5CYWtlLk9mZi1TMDYtQ29tcGxldGUudy5FeHRyYS5TbGljZS03MjBwL1RHQkJPLVMwNkUwMS1Bbi5FeHRyYS5TbGljZS1TMDJFMDEtNzIwcC5tcDQ=&lt;/PersistentBookmark&gt;&lt;res protocolInfo="http-get:*:video/mp4:DLNA.ORG_PN=AVC_MP4_HP_HD;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01700000000000000000000000000000" pv:subtitleFileUri="http://192.168.1.7:9000/disk/SUBTITLE/O0$3$35$192R60427.srt" pv:subtitleFileType="SRT" resolution="1280x720" size="521747010" duration="00:29:03"&gt;http://192.168.1.7:9000/disk/DLNA-PNAVC_MP4_HP_HD-OP01-FLAGS01700000/O0$3$27I60427.mp4&lt;/res&gt;&lt;res protocolInfo="http-get:*:application/x-srt:*"&gt;http://192.168.1.7:9000/disk/NON-DLNA-OP01-FLAGS00d00000/SUBTITLE/O0$3$35$192R60427.srt&lt;/res&gt;&lt;res protocolInfo="http-get:*:image/jpeg:*"&gt;http://192.168.1.7:9000/disk/DLNA-PNJPEG_TN-CI1-FLAGS00d00000/defaa/V/O0$3$27I60427.jpg?scale=org&lt;/res&gt;&lt;upnp:class&gt;object.item.videoItem.movie&lt;/upnp:class&gt;&lt;pv:supported&gt;true&lt;/pv:supported&gt;&lt;pv:pushSource&gt;192.168.1.7&lt;/pv:pushSource&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</CurrentURIMetaData>
    </u:SetAVTransportURI>
  </s:Body>
</s:Envelope>
```


PS @valib @SubJunk feel free to jump in with a temporary cat5 cable and **your actual Vieras** anytime, I may be drifting off into the ether again soon  :-)

**Comment by Sami32** [comment]
@skeptical For now i will give you the infos obtain with _UPNP Inspector_(Play, Pause, Stop worked) and _Twonky_, but sadly, like in Cling i din't find a way to save the full Log :-(
And later i will test more kind of videos with _Cling Workbench_ and try sniffing with Wireshark.
[UPnP_Skeptical.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/271595/UPnP_Skeptical.txt)

**N.B.** Not that i really need this feature, but i like when things are working fine and not use many applications when one could do the job; maybe i like headaches after all :-D

**Comment by Sami32** [comment]
@skeptical  By the way, when i was testing for trying to find what was wrong with in the AVTransport, i discover that not only WAV music files was parsed with audio/mpeg:DLNA.ORG_PN=MP3 but all the music files OGG, FLAC, AAC !

**Comment by skeptical** [comment]
@Sami32 you've been a busy bee :+1:. I'll look at the data, but first please try the UMS control panel with this update and send logs for ```PushMetadata=true``` and also ```PushMetadata=false```. This update tries to look at some possible simpler causes of the issue:

[update-ums-6.3.1-SNAPSHOT-viera-avt-fixes.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/275437/update-ums-6.3.1-SNAPSHOT-viera-avt-fixes.zip)

**Comment by Sami32** [comment]
@skeptical Yeahh you are the guy with the good question, remark :+1: 
PushMetadata=False will make the things working fine; i will do more testing later as well learn how to use Web interface...
[ums_dbg_PushMetadata=False.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/275851/ums_dbg_PushMetadata.False.zip.txt)
[ums_dbg_PushMetadata_TRUE.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/275850/ums_dbg_PushMetadata_TRUE.zip.txt)

**Comment by skeptical** [comment]
@Sami32  it's a much simpler reason than we imagined :-D.  The resource uris that UMS sends often include url-encoded characters (e.g ```%5C``` for ```\```, etc), which the Viera rejects because it's being stricter about this than other devices.  For ```PushMetadata=false``` I patched UMS to send a uri without url-encoded characters:
```logtalk
TRACE 2016-05-21 14:08:38.218 [AWT-EventQueue-0] simplified 'C%3A%5CDOCUME%7E1%5CPhilippe%5CMESDOC%7E1%5CT%C3%89L%C3%89CH%7E1%5CPEAKYB%7E1.X26%5CPEAKYB%7E1.MKV' to 'resource.MKV'
```
and voila! Twonky wasn't doing anything special, its uris were just simpler than UMS.

To narrow the issue some more try this update with both ```PushMetadata``` states.

[update-ums-6.3.1-SNAPSHOT-viera-avt-fixes-2.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/275889/update-ums-6.3.1-SNAPSHOT-viera-avt-fixes-2.zip)

**Comment by Sami32** [comment]
@skeptical Here are the new LOGs updates, PushMetadata=False is the only one working.
[ums_dbg_PushMetadata=TRUE2.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276277/ums_dbg_PushMetadata.TRUE2.zip.txt)
[ums_dbg_PushMetadata=False2.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276276/ums_dbg_PushMetadata.False2.zip.txt)

With **PushMetadata=False** it is working but...
1) **Subtitles** are not displayed.
2) **REWIND & FORWARD seeking** commands are doing a one time 60s jump...not continuously.
3) This **error** is displaying in the _Cling Workbench_ LOG :

> WARNING - 13:09:55:359 - cling-47 : support.lastchange.LastChangeParser$InstanceIDHandler.startElement : Error reading event XML, ignoring value: java.lang.IllegalArgumentException: No enum constant org.teleal.cling.support.model.TransportAction.X_DLNA_PS=-300,-150,-70,-30,-5,5,30,70,150,300

**Comment by skeptical** [comment]
@Sami32 
1. when ```PushMetadata=false``` there's no metadata, which means no subtitle info is sent (this is the same as when you push a twonky/ums uri via workbench).
2. Rew/Fwd is defined in ums upnp support as one 60 second jump, so that's normal.
3. The error is insignificant, I think.

Try this update with ```PushMetadata=true```, which tries to send a proper DLNA.ORG_PN flag for mkv, which may have been the problem.  Also, try pushing other file types.
[update-ums-6.3.1-SNAPSHOT-viera-avt-fixes-3.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276335/update-ums-6.3.1-SNAPSHOT-viera-avt-fixes-3.zip)

**Comment by Sami32** [comment]
@skeptical Thank you for your explanation and your patience ;-)

It is not working, but i did tried many different kind of files as asked :
[ums_dbg_PushMetadata=True3.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276481/ums_dbg_PushMetadata.True3.zip.txt)

**N.B.** About the point 2 i was not clear. I was trying to tell that we cannot change the time seeking 30,70,150,300s by clicking more time on _FWD_ (same for _RWD_) and that when we click on the button (_FWD/RWD_) it take action only one time, not continuously until we click on _Play_ button (like in _TWONKY Server_, if i am not able to explain well with my poor english...)
It's just about this seeking UMS  implementation that i find not very useful.

**Comment by skeptical** [comment]
@Sami32 thx for explaining point 2 :-). Let's call it a feature request and slightly off-topic here, where the main issue is fixing the Viera avt commands.

Another try at fixing ```PushMetadata=true``` scenario, please send logs again:
[update-ums-6.3.1-SNAPSHOT-viera-avt-fixes-4.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276519/update-ums-6.3.1-SNAPSHOT-viera-avt-fixes-4.zip)

**Comment by Sami32** [comment]
Your are the queen bee :+1: 

Sorry not working yet...but i feel that will be soon ;-)
[ums_dbg_PushMetadata=TRUE4.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276533/ums_dbg_PushMetadata.TRUE4.zip.txt)

**N.B**. Sorry about the point 2, i was just thinking that it was the normal/standard way...don't forget i am just an old newbie :-)

**Comment by skeptical** [comment]
@Sami32 I'm only a worker bee :P.  It seems you are doing something different between test 3 and 4.  Can you please try several files, both from player control panel and web interface?

**Comment by Sami32** [comment]
@skeptical Different ? no...but i discover a weir comportment...sometimes the same movie was working and sometimes not ! It's look like it is time to take Paracetamol :-D
[ums_dbg_PushMetadata=TRUE4bis.zip.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/276573/ums_dbg_PushMetadata.TRUE4bis.zip.txt)

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/818
